In [ ]:
from pathlib import Path
import pandas as pd

TEST_DIR = Path("TEST")

s1_file = TEST_DIR / "test_source1.tsv"
s2_file = TEST_DIR / "test_source2.tsv"
s3_file = TEST_DIR / "test_source3.tsv"

print("S1 exists:", s1_file.exists())
print("S2 exists:", s2_file.exists())
print("S3 exists:", s3_file.exists())

S1 exists: True
S2 exists: True
S3 exists: True

In [ ]:
s1 = pd.read_csv(
    s1_file,
    sep="\t",
    dtype=str,
    nrows=1000
)

print("S1 test rows:", len(s1))
print(s1.head())
print(s1.columns.tolist())

EmptyDataError: No columns to parse from file

In [ ]:
from pathlib import Path
import pandas as pd

TEST_DIR = Path("TEST")

for file in TEST_DIR.glob("*.tsv"):
    print(file.name, file.stat().st_size, "bytes")

test_source2.tsv 0 bytes
test_source3.tsv 0 bytes
test_source1.tsv 0 bytes

In [ ]:
TEST_DIR = Path("TEST")

NameError: name 'Path' is not defined

In [ ]:
from pathlib import Path

In [ ]:
TEST_DIR = Path.home() / "Downloads/student_resource/dataset/test"

print("Folder exists:", TEST_DIR.exists())

for file in TEST_DIR.glob("*.tsv"):
    print(file.name, file.stat().st_size, "bytes")

Folder exists: True
test_source2.tsv 0 bytes
test_source3.tsv 506002772 bytes
test_source1.tsv 175022086 bytes

In [ ]:
Downloads/student_resource/dataset/test/test_source2.tsv

NameError: name 'Downloads' is not defined

In [ ]:
from pathlib import Path

TEST_DIR = Path.home() / "Downloads/student_resource/dataset/test"

for file in TEST_DIR.glob("*.tsv"):
    print(file.name, file.stat().st_size, "bytes")

test_source2.tsv 0 bytes
test_source3.tsv 506002772 bytes
test_source1.tsv 175022086 bytes

In [ ]:
from pathlib import Path

In [ ]:
TEST_DIR = Path.home() / "Downloads/student_resource/dataset/test"

print(TEST_DIR)

/Users/apple/Downloads/student_resource/dataset/test

In [ ]:
for file in TEST_DIR.glob("*.tsv"):
    print(file.name, file.stat().st_size, "bytes")

test_source2.tsv 0 bytes
test_source3.tsv 506002772 bytes
test_source1.tsv 175022086 bytes

In [ ]:
from pathlib import Path

TEST_DIR = Path.home() / "Downloads/student_resource/dataset/test"

for file in TEST_DIR.glob("*.tsv"):
    print(file.name, round(file.stat().st_size / (1024**2), 2), "MB")

test_source2.tsv 0.0 MB
test_source3.tsv 482.56 MB
test_source1.tsv 166.91 MB

In [ ]:
import pandas as pd

s2 = pd.read_csv(
    TEST_DIR / "test_source2.tsv",
    sep="\t",
    dtype=str,
    nrows=5
)

print(s2)
print(s2.columns.tolist())

EmptyDataError: No columns to parse from file

In [ ]:
from pathlib import Path

TEST_DIR = Path.home() / "Downloads/student_resource 2/dataset/test"

print(TEST_DIR)

/Users/apple/Downloads/student_resource 2/dataset/test

In [ ]:
for file in TEST_DIR.glob("*.tsv"):
    print(file.name, file.stat().st_size, "bytes")

test_source2.tsv 509456422 bytes
test_source3.tsv 506002772 bytes
test_source1.tsv 175022086 bytes

In [ ]:
from pathlib import Path

TEST_DIR = Path.home() / "Downloads/student_resource 2/dataset/test"

In [ ]:
import pandas as pd

for name in ["test_source1.tsv", "test_source2.tsv", "test_source3.tsv"]:
    df = pd.read_csv(
        TEST_DIR / name,
        sep="\t",
        dtype=str,
        nrows=3
    )
    
    print("\n", name)
    print("Columns:", df.columns.tolist())
    print(df.head(2))

 test_source1.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']
      entity_id         business_name                        business_address  \
0  S1-714132312       Zephay Labs Inc             2621 Cotten Road, Tyler, TX
1  S1-106407869  Vision Partners Corp  IA, Iowa City, 1064 Newton Rd, Unit 11

  country
0      US
1      US

 test_source2.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']
      entity_id             business_name  \
0  S2-192345572           Brahma Infosoft
1  S2-566025912  Marina Ecole France Sarl

                                    business_address country
0  COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...   India
1            63 R. DE DIEPPE, LILLE, Hauts-de-France  France

 test_source3.tsv
Columns: ['entity_id', 'business_name', 'business_address', 'country']
      entity_id          business_name  \
0  S3-462677478         मॉडर्न फाइनेंस
1  S3-374810425  Shri Sai Infratech Co

                                    business_address country
0  No 10 Enkay Square, 448A, Udyog Vihar Phase V,...   India
1                              3/115, East Delhi, DL   India

In [ ]:
import pandas as pd
import re
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

TEST_DIR = Path.home() / "Downloads/student_resource 2/dataset/test"

# Read only 1,000 S1 records
s1 = pd.read_csv(
    TEST_DIR / "test_source1.tsv",
    sep="\t",
    dtype=str,
    nrows=1000
)

# Read a manageable sample from S2 and S3
s2 = pd.read_csv(
    TEST_DIR / "test_source2.tsv",
    sep="\t",
    dtype=str,
    nrows=100000
)

s3 = pd.read_csv(
    TEST_DIR / "test_source3.tsv",
    sep="\t",
    dtype=str,
    nrows=100000
)

print("S1:", len(s1))
print("S2 sample:", len(s2))
print("S3 sample:", len(s3))

S1: 1000
S2 sample: 100000
S3 sample: 100000

In [ ]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors


def normalize_name(x):
    if pd.isna(x):
        return ""

    x = str(x).lower()

    replacements = {
        "private limited": "pvt ltd",
        "private ltd": "pvt ltd",
        "corporation": "corp",
        "incorporated": "inc",
        "limited": "ltd",
        "company": "co"
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = re.sub(r"[^a-z0-9\s]", " ", x)
    x = re.sub(r"\s+", " ", x).strip()

    return x


s1["name_norm"] = s1["business_name"].map(normalize_name)
s2["name_norm"] = s2["business_name"].map(normalize_name)
s3["name_norm"] = s3["business_name"].map(normalize_name)


# Combine S2 and S3 for one candidate index
candidate_pool = pd.concat(
    [
        s2[["entity_id", "name_norm", "country"]].assign(source="S2"),
        s3[["entity_id", "name_norm", "country"]].assign(source="S3")
    ],
    ignore_index=True
)

print("Candidate pool:", len(candidate_pool))

Candidate pool: 200000

In [ ]:
vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2,
    max_features=200000,
    sublinear_tf=True
)

candidate_matrix = vectorizer.fit_transform(
    candidate_pool["name_norm"]
)

s1_matrix = vectorizer.transform(
    s1["name_norm"]
)

print("S1 matrix:", s1_matrix.shape)
print("Candidate matrix:", candidate_matrix.shape)

S1 matrix: (1000, 200000)
Candidate matrix: (200000, 200000)

In [ ]:

TOP_K = 10

nn = NearestNeighbors(
    n_neighbors=TOP_K,
    metric="cosine",
    algorithm="brute",
    n_jobs=-1
)

nn.fit(candidate_matrix)

distances, indices = nn.kneighbors(s1_matrix)

print("Candidate search complete.")
print("Distance shape:", distances.shape)
print("Index shape:", indices.shape)

Candidate search complete.
Distance shape: (1000, 10)
Index shape: (1000, 10)

In [ ]:

i = 0

print("S1:")
print(s1.iloc[i][["entity_id", "business_name", "business_address", "country"]])

print("\nTop candidates:")

for rank in range(TOP_K):
    idx = indices[i, rank]

    print(
        rank + 1,
        "|",
        candidate_pool.iloc[idx]["entity_id"],
        "|",
        candidate_pool.iloc[idx]["source"],
        "| similarity:",
        round(1 - distances[i, rank], 4),
        "|",
        candidate_pool.iloc[idx]["name_norm"]
    )

S1:
entity_id                          S1-714132312
business_name                   Zephay Labs Inc
business_address    2621 Cotten Road, Tyler, TX
country                                      US
Name: 0, dtype: str

Top candidates:
1 | S3-757443618 | S3 | similarity: 0.522 | zephay land valley
2 | S3-993383744 | S3 | similarity: 0.4223 | pacific labs inc
3 | S3-13661993 | S3 | similarity: 0.4012 | zephavi
4 | S2-779171736 | S2 | similarity: 0.3766 | ily labs pvt ltd
5 | S3-720378680 | S3 | similarity: 0.3733 | all chemical labs inc
6 | S3-234842027 | S3 | similarity: 0.3724 | regional labs inc services
7 | S3-198890764 | S3 | similarity: 0.3702 | the gulf labs inc
8 | S2-798160947 | S2 | similarity: 0.3686 | lopez labs inc service
9 | S3-13893318 | S3 | similarity: 0.3641 | pune labs industries co
10 | S3-699113319 | S3 | similarity: 0.3595 | unified trading labs inc

In [ ]:
def normalize_text(x):
    if pd.isna(x):
        return ""

    x = str(x).lower()

    replacements = {
        "private limited": "pvt ltd",
        "private ltd": "pvt ltd",
        "corporation": "corp",
        "incorporated": "inc",
        "limited": "ltd",
        "company": "co",
        "street": "st",
        "road": "rd",
        "avenue": "ave",
        "boulevard": "blvd",
        "drive": "dr",
        "lane": "ln",
        "highway": "hwy",
        "parkway": "pkwy",
        "apartment": "apt",
        "suite": "ste"
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = re.sub(r"[^a-z0-9\s]", " ", x)
    x = re.sub(r"\s+", " ", x).strip()

    return x

In [ ]:
s1["match_text"] = (
    s1["business_name"].map(normalize_text)
    + " "
    + s1["business_address"].map(normalize_text)
)

s2["match_text"] = (
    s2["business_name"].map(normalize_text)
    + " "
    + s2["business_address"].map(normalize_text)
)

s3["match_text"] = (
    s3["business_name"].map(normalize_text)
    + " "
    + s3["business_address"].map(normalize_text)
)

In [ ]:
candidate_pool = pd.concat(
    [
        s2[["entity_id", "match_text", "country"]].assign(source="S2"),
        s3[["entity_id", "match_text", "country"]].assign(source="S3")
    ],
    ignore_index=True
)

s1_text = s1["match_text"]
candidate_text = candidate_pool["match_text"]

In [ ]:
vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2,
    max_features=200000,
    sublinear_tf=True
)

candidate_matrix = vectorizer.fit_transform(candidate_text)
s1_matrix = vectorizer.transform(s1_text)

print(candidate_matrix.shape)
print(s1_matrix.shape)

(200000, 200000)
(1000, 200000)

In [ ]:
vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2,
    max_features=200000,
    sublinear_tf=True
)

candidate_matrix = vectorizer.fit_transform(candidate_text)
s1_matrix = vectorizer.transform(s1_text)

print(candidate_matrix.shape)
print(s1_matrix.shape)

(200000, 200000)
(1000, 200000)

In [ ]:
TOP_K = 10

nn = NearestNeighbors(
    n_neighbors=TOP_K,
    metric="cosine",
    algorithm="brute",
    n_jobs=-1
)

nn.fit(candidate_matrix)

distances, indices = nn.kneighbors(s1_matrix)

print("Candidate search complete.")

Candidate search complete.

In [ ]:
i = 0

print("S1:")
print(s1.iloc[i][[
    "entity_id",
    "business_name",
    "business_address",
    "country"
]])

print("\nTop candidates:")

for rank in range(TOP_K):
    idx = indices[i, rank]

    print(
        rank + 1,
        "|",
        candidate_pool.iloc[idx]["entity_id"],
        "|",
        candidate_pool.iloc[idx]["source"],
        "| country:",
        candidate_pool.iloc[idx]["country"],
        "| similarity:",
        round(1 - distances[i, rank], 4),
        "|",
        candidate_pool.iloc[idx]["match_text"]
    )

S1:
entity_id                          S1-714132312
business_name                   Zephay Labs Inc
business_address    2621 Cotten Road, Tyler, TX
country                                      US
Name: 0, dtype: str

Top candidates:
1 | S2-867293831 | S2 | country: US | similarity: 0.2455 | cesonia valley inc 158 238 tyler tx
2 | S3-148354258 | S3 | country: US | similarity: 0.2396 | buon h ldings group inc 12533 hill rd tyler texas
3 | S3-658695987 | S3 | country: US | similarity: 0.233 | greer pinnacle labs inc
4 | S2-726246713 | S2 | country: US | similarity: 0.2312 | dental care east inc 13397 4134 tyler tx
5 | S2-639723224 | S2 | country: US | similarity: 0.229 | mercado center 15520 14 tyler tx
6 | S2-702525855 | S2 | country: US | similarity: 0.2263 | pl pioneer sneac inc 2822 front st tyler tx
7 | S2-123059539 | S2 | country: US | similarity: 0.2212 | metropolitan consumer 2502 2506 new copeland rd tyler tx
8 | S2-290270322 | S2 | country: US | similarity: 0.2154 | maid tattoo inc 1604 trail rdg tyler tx
9 | S2-364865093 | S2 | country: US | similarity: 0.2143 | veltecsoft center 1105 4th st tyler tx
10 | S3-429813193 | S3 | country: US | similarity: 0.2135 | corp fresh wealth labs 161 tyler rd bear delaware

In [ ]:
# Separate name and address candidate generation

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

# ---------------------------------
# 1. Normalize name and address
# ---------------------------------

s1["name_norm"] = s1["business_name"].map(normalize_text)
s2["name_norm"] = s2["business_name"].map(normalize_text)
s3["name_norm"] = s3["business_name"].map(normalize_text)

s1["address_norm"] = s1["business_address"].map(normalize_text)
s2["address_norm"] = s2["business_address"].map(normalize_text)
s3["address_norm"] = s3["business_address"].map(normalize_text)


# ---------------------------------
# 2. NAME TF-IDF
# ---------------------------------

name_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2,
    max_features=200000,
    sublinear_tf=True
)

name_pool = pd.concat(
    [
        s2[["entity_id", "name_norm", "country"]].assign(source="S2"),
        s3[["entity_id", "name_norm", "country"]].assign(source="S3")
    ],
    ignore_index=True
)

name_matrix = name_vectorizer.fit_transform(
    name_pool["name_norm"]
)

s1_name_matrix = name_vectorizer.transform(
    s1["name_norm"]
)

name_nn = NearestNeighbors(
    n_neighbors=10,
    metric="cosine",
    algorithm="brute",
    n_jobs=-1
)

name_nn.fit(name_matrix)

name_distances, name_indices = name_nn.kneighbors(
    s1_name_matrix
)

print("Name candidates generated.")

Name candidates generated.

In [ ]:
# ---------------------------------
# 3. ADDRESS TF-IDF
# ---------------------------------

address_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(3, 5),
    min_df=2,
    max_features=200000,
    sublinear_tf=True
)

address_pool = name_pool.copy()

address_pool["address_norm"] = pd.concat(
    [
        s2["address_norm"],
        s3["address_norm"]
    ],
    ignore_index=True
)

address_matrix = address_vectorizer.fit_transform(
    address_pool["address_norm"]
)

s1_address_matrix = address_vectorizer.transform(
    s1["address_norm"]
)

address_nn = NearestNeighbors(
    n_neighbors=10,
    metric="cosine",
    algorithm="brute",
    n_jobs=-1
)

address_nn.fit(address_matrix)

address_distances, address_indices = address_nn.kneighbors(
    s1_address_matrix
)

print("Address candidates generated.")

Address candidates generated.

In [ ]:
# ---------------------------------
# 4. UNION NAME + ADDRESS CANDIDATES
# ---------------------------------

candidate_rows = []

for i in range(len(s1)):

    s1_id = s1.iloc[i]["entity_id"]

    # Name candidates
    for rank in range(10):

        idx = name_indices[i, rank]

        candidate_rows.append({
            "source1_entity_id": s1_id,
            "candidate_entity_id": name_pool.iloc[idx]["entity_id"],
            "candidate_source": name_pool.iloc[idx]["source"],
            "channel": "name",
            "similarity": 1 - name_distances[i, rank]
        })

    # Address candidates
    for rank in range(10):

        idx = address_indices[i, rank]

        candidate_rows.append({
            "source1_entity_id": s1_id,
            "candidate_entity_id": address_pool.iloc[idx]["entity_id"],
            "candidate_source": address_pool.iloc[idx]["source"],
            "channel": "address",
            "similarity": 1 - address_distances[i, rank]
        })


candidates = pd.DataFrame(candidate_rows)

# Remove duplicate S1-candidate pairs
candidates = (
    candidates
    .sort_values("similarity", ascending=False)
    .drop_duplicates(
        ["source1_entity_id", "candidate_entity_id"]
    )
)

print("Total candidate pairs:", len(candidates))
print(candidates.head(20))

Total candidate pairs: 19916
      source1_entity_id candidate_entity_id candidate_source  channel  \
19920      S1-831250685         S2-17473212               S2     name
20         S1-106407869         S2-47475427               S2     name
11950      S1-743413952        S2-112419183               S2  address
15400      S1-450337428        S2-638393180               S2     name
3240       S1-762839052        S3-854245605               S3     name
3220       S1-650304466        S2-786787970               S2     name
3800       S1-455827432        S3-321062813               S3     name
3801       S1-455827432         S2-88690729               S2     name
3802       S1-455827432        S3-641257868               S3     name
3820       S1-527611593        S2-626821575               S2     name
16980      S1-822292739        S3-300820527               S3     name
16981      S1-822292739        S2-872285328               S2     name
12120      S1-743701929        S3-149796619               S3     name
12140      S1-554606367        S2-199676050               S2     name
11840      S1-874756885        S2-497867787               S2     name
11860      S1-930629318          S3-3653544               S3     name
11363      S1-202627015        S2-662952744               S2     name
11364      S1-202627015        S3-751048481               S3     name
11365      S1-202627015        S3-154207439               S3     name
11366      S1-202627015        S2-371555068               S2     name

       similarity
19920         1.0
20            1.0
11950         1.0
15400         1.0
3240          1.0
3220          1.0
3800          1.0
3801          1.0
3802          1.0
3820          1.0
16980         1.0
16981         1.0
12120         1.0
12140         1.0
11840         1.0
11860         1.0
11363         1.0
11364         1.0
11365         1.0
11366         1.0

In [ ]:
zephay = candidates[
    candidates["source1_entity_id"] == "S1-714132312"
]

print(zephay.to_string(index=False))

source1_entity_id candidate_entity_id candidate_source channel  similarity
     S1-714132312        S3-757443618               S3    name    0.522042
     S1-714132312        S3-993383744               S3    name    0.421801
     S1-714132312        S2-867293831               S2 address    0.416954
     S1-714132312         S3-13661993               S3    name    0.400665
     S1-714132312        S2-354095420               S2 address    0.398962
     S1-714132312        S2-389653136               S2 address    0.397807
     S1-714132312        S3-148354258               S3 address    0.396130
     S1-714132312        S2-339060039               S2 address    0.392110
     S1-714132312        S2-294421300               S2 address    0.377436
     S1-714132312        S2-639723224               S2 address    0.376711
     S1-714132312        S2-779171736               S2    name    0.376412
     S1-714132312        S3-720378680               S3    name    0.372912
     S1-714132312        S2-726246713               S2 address    0.372485
     S1-714132312        S3-234842027               S3    name    0.372015
     S1-714132312        S3-198890764               S3    name    0.369878
     S1-714132312        S2-798160947               S2    name    0.367735
     S1-714132312        S2-364865093               S2 address    0.363734
     S1-714132312         S3-13893318               S3    name    0.363596
     S1-714132312        S3-699113319               S3    name    0.359152
     S1-714132312        S2-123059539               S2 address    0.357507

In [ ]:
print("Current sample candidate count:", len(candidates))
print("Average candidates per S1:",
      len(candidates) / candidates["source1_entity_id"].nunique())

Current sample candidate count: 19916
Average candidates per S1: 19.916

In [ ]:
import pandas as pd

TRAIN_DIR = Path.home() / "Downloads/student_resource 2/dataset/train"

gt = pd.read_csv(
    TRAIN_DIR / "train_ground_truth.tsv",
    sep="\t",
    dtype=str
)

print(gt.columns.tolist())
print(gt.head())
print("Rows:", len(gt))

['source1_entity_id', 'matched_entity_ids']
  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
Rows: 2206821

In [ ]:
print(gt["matched_entity_ids"].head(10).tolist())

['S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364', 'S2-249013014,S2-197070651,S3-478195123,S3-384364074', 'S2-790675320,S2-479876582,S3-878454467', 'S2-153058913,S2-24659151,S3-679606215', 'S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785', 'S2-755677256,S3-187831601,S3-641489370,S3-476250621', 'S2-660036492,S3-804600254', 'S3-274817120,S3-312496301', 'S2-648035184,S3-588502663', 'S2-383871912,S3-74481402,S3-576451439']

In [ ]:
# Calculate blocking recall

# Create lookup:
# S1 ID -> set of true matched S2/S3 IDs
ground_truth = {}

for _, row in gt.iterrows():
    s1_id = row["source1_entity_id"]
    
    if pd.isna(row["matched_entity_ids"]):
        ground_truth[s1_id] = set()
    else:
        ground_truth[s1_id] = set(
            str(row["matched_entity_ids"]).split(",")
        )

# Candidate lookup
candidate_lookup = (
    candidates
    .groupby("source1_entity_id")["candidate_entity_id"]
    .apply(set)
    .to_dict()
)

# Calculate recall
total_true = 0
found_true = 0

for s1_id, true_ids in ground_truth.items():
    
    # Only evaluate S1s present in our current sample
    if s1_id not in candidate_lookup:
        continue
    
    predicted_candidates = candidate_lookup[s1_id]
    
    total_true += len(true_ids)
    found_true += len(true_ids & predicted_candidates)

recall = found_true / total_true if total_true > 0 else 0

print("True matches evaluated:", total_true)
print("True matches found:", found_true)
print("Blocking Recall:", round(recall, 4))
print("Blocking Recall %:", round(recall * 100, 2), "%")

True matches evaluated: 0
True matches found: 0
Blocking Recall: 0
Blocking Recall %: 0 %

In [ ]:
import pandas as pd
from pathlib import Path

TRAIN_DIR = Path.home() / "Downloads/student_resource 2/dataset/train"

train_s1 = pd.read_csv(
    TRAIN_DIR / "train_source1.tsv",
    sep="\t",
    dtype=str,
    nrows=1000
)

train_s2 = pd.read_csv(
    TRAIN_DIR / "train_source2.tsv",
    sep="\t",
    dtype=str,
    nrows=100000
)

train_s3 = pd.read_csv(
    TRAIN_DIR / "train_source3.tsv",
    sep="\t",
    dtype=str,
    nrows=100000
)

print("Train S1:", len(train_s1))
print("Train S2 sample:", len(train_s2))
print("Train S3 sample:", len(train_s3))

Train S1: 1000
Train S2 sample: 100000
Train S3 sample: 100000

In [ ]:
# Normalize training data

train_s1["name_norm"] = train_s1["business_name"].map(normalize_text)
train_s2["name_norm"] = train_s2["business_name"].map(normalize_text)
train_s3["name_norm"] = train_s3["business_name"].map(normalize_text)

train_s1["address_norm"] = train_s1["business_address"].map(normalize_text)
train_s2["address_norm"] = train_s2["business_address"].map(normalize_text)
train_s3["address_norm"] = train_s3["business_address"].map(normalize_text)

print("Normalization complete.")

Normalization complete.

In [ ]:
# Create training candidate pool

train_pool = pd.concat(
    [
        train_s2[["entity_id", "name_norm", "address_norm", "country"]]
        .assign(source="S2"),

        train_s3[["entity_id", "name_norm", "address_norm", "country"]]
        .assign(source="S3")
    ],
    ignore_index=True
)

print("Training candidate pool:", len(train_pool))

Training candidate pool: 200000

In [ ]:

name_vectorizer_train = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2,
    max_features=200000,
    sublinear_tf=True
)

name_matrix_train = name_vectorizer_train.fit_transform(
    train_pool["name_norm"]
)

train_s1_name_matrix = name_vectorizer_train.transform(
    train_s1["name_norm"]
)

name_nn_train = NearestNeighbors(
    n_neighbors=10,
    metric="cosine",
    algorithm="brute",
    n_jobs=-1
)

name_nn_train.fit(name_matrix_train)

name_dist_train, name_idx_train = name_nn_train.kneighbors(
    train_s1_name_matrix
)

print("Training name candidates generated.")

Training name candidates generated.

In [ ]:
address_vectorizer_train = TfidfVectorizer(
    analyzer="char",
    ngram_range=(3, 5),
    min_df=2,
    max_features=200000,
    sublinear_tf=True
)

address_matrix_train = address_vectorizer_train.fit_transform(
    train_pool["address_norm"]
)

train_s1_address_matrix = address_vectorizer_train.transform(
    train_s1["address_norm"]
)

address_nn_train = NearestNeighbors(
    n_neighbors=10,
    metric="cosine",
    algorithm="brute",
    n_jobs=-1
)

address_nn_train.fit(address_matrix_train)

address_dist_train, address_idx_train = address_nn_train.kneighbors(
    train_s1_address_matrix
)

print("Training address candidates generated.")

Training address candidates generated.

In [ ]:
train_candidates = []

for i in range(len(train_s1)):

    s1_id = train_s1.iloc[i]["entity_id"]

    # Name channel
    for rank in range(10):
        idx = name_idx_train[i, rank]

        train_candidates.append({
            "source1_entity_id": s1_id,
            "candidate_entity_id": train_pool.iloc[idx]["entity_id"],
            "channel": "name"
        })

    # Address channel
    for rank in range(10):
        idx = address_idx_train[i, rank]

        train_candidates.append({
            "source1_entity_id": s1_id,
            "candidate_entity_id": train_pool.iloc[idx]["entity_id"],
            "channel": "address"
        })

train_candidates = pd.DataFrame(train_candidates)

train_candidates = train_candidates.drop_duplicates(
    ["source1_entity_id", "candidate_entity_id"]
)

print("Training candidate pairs:", len(train_candidates))

Training candidate pairs: 19936

In [ ]:
print("Training S1 sample:", len(train_s1))
print("Training S2 sample:", len(train_s2))
print("Training S3 sample:", len(train_s3))
print("Candidate pairs:", len(train_candidates))

Training S1 sample: 1000
Training S2 sample: 100000
Training S3 sample: 100000
Candidate pairs: 19936

In [ ]:
# Inspect the training ground truth for the first 100 S1 records

sample_s1_ids = set(train_s1["entity_id"].head(100))

gt_sample = gt[
    gt["source1_entity_id"].isin(sample_s1_ids)
].copy()

print("Ground-truth S1 records:", len(gt_sample))

print(
    gt_sample[
        ["source1_entity_id", "matched_entity_ids"]
    ].head(10).to_string(index=False)
)

Ground-truth S1 records: 100
source1_entity_id                                                                         matched_entity_ids
     S1-746273151                                                                                        NaN
     S1-993527714                                                                  S3-250788566,S3-623091575
     S1-236312382                                                      S2-734049056,S2-69010626,S3-591515133
     S1-630223771                                        S2-494260820,S3-697578371,S3-815538600,S3-587424087
      S1-17666546                                                     S2-341313901,S3-144249320,S3-358598397
     S1-315450523                                                                               S2-945125430
     S1-629417405 S2-522538408,S2-928426462,S3-613837325,S3-606982601,S3-962449159,S3-438606634,S3-786131946
     S1-970518712                                                     S2-239226917,S3-849723066,S3-460357940
     S1-965549055                                          S2-71831978,S2-147779226,S3-537422052,S3-47511318
     S1-309349399                                                                                        NaN

In [ ]:
# Count how many true matches these 100 S1 records have

total_true_matches = 0

for value in gt_sample["matched_entity_ids"].dropna():
    total_true_matches += len(str(value).split(","))

print("True matches for first 100 S1:", total_true_matches)

True matches for first 100 S1: 322

In [ ]:
# Use the first 100 training S1 records
recall_s1 = train_s1.head(100).copy()

print("S1 records:", len(recall_s1))

S1 records: 100

In [ ]:
# Ground truth lookup for these 100 S1s

gt_lookup = {}

for _, row in gt_sample.iterrows():

    s1_id = row["source1_entity_id"]

    if pd.isna(row["matched_entity_ids"]):
        gt_lookup[s1_id] = set()
    else:
        gt_lookup[s1_id] = set(
            str(row["matched_entity_ids"]).split(",")
        )

print("Ground-truth S1s:", len(gt_lookup))
print("Total true matches:", sum(len(v) for v in gt_lookup.values()))

Ground-truth S1s: 100
Total true matches: 322

In [ ]:
candidate_lookup_train = (
    train_candidates
    .groupby("source1_entity_id")["candidate_entity_id"]
    .apply(set)
    .to_dict()
)

found = 0
total = 0

for s1_id, true_ids in gt_lookup.items():

    total += len(true_ids)

    predicted = candidate_lookup_train.get(s1_id, set())

    found += len(true_ids & predicted)

print("True matches:", total)
print("Found in current candidates:", found)

if total > 0:
    print("Sample blocking recall:",
          round(found / total * 100, 2), "%")

True matches: 322
Found in current candidates: 6
Sample blocking recall: 1.86 %

In [ ]:
# Check how many of the 322 true matches are even present
# in our 100k + 100k sampled candidate pool.

sample_candidate_ids = set(train_pool["entity_id"])

available_true = 0
missing_true = 0

for s1_id, true_ids in gt_lookup.items():
    for entity_id in true_ids:
        if entity_id in sample_candidate_ids:
            available_true += 1
        else:
            missing_true += 1

print("Total true matches:", available_true + missing_true)
print("True matches present in 200k sample:", available_true)
print("True matches outside 200k sample:", missing_true)

if available_true + missing_true > 0:
    print(
        "Maximum possible recall with this sample:",
        round(available_true / (available_true + missing_true) * 100, 2),
        "%"
    )

Total true matches: 322
True matches present in 200k sample: 6
True matches outside 200k sample: 316
Maximum possible recall with this sample: 1.86 %

In [ ]:
import pandas as pd
import re
from rapidfuzz import process, fuzz

# Full training file paths
TRAIN_DIR = Path.home() / "Downloads/student_resource 2/dataset/train"

# First 100 S1 records
recall_s1 = train_s1.head(100).copy()

recall_s1["name_norm"] = recall_s1["business_name"].map(normalize_text)
recall_s1["address_norm"] = recall_s1["business_address"].map(normalize_text)

# Store best candidates found across ALL chunks
best_candidates = {
    row["entity_id"]: {}
    for _, row in recall_s1.iterrows()
}

# Process S2 and S3 separately
source_files = [
    ("S2", TRAIN_DIR / "train_source2.tsv"),
    ("S3", TRAIN_DIR / "train_source3.tsv")
]

CHUNK_SIZE = 100_000
TOP_K = 20

for source_name, file_path in source_files:

    print(f"\nProcessing {source_name}...")

    for chunk_no, chunk in enumerate(
        pd.read_csv(
            file_path,
            sep="\t",
            dtype=str,
            chunksize=CHUNK_SIZE
        )
    ):

        chunk["name_norm"] = chunk["business_name"].map(normalize_text)
        chunk["address_norm"] = chunk["business_address"].map(normalize_text)

        # Remove empty names/addresses
        name_choices = dict(
            zip(
                chunk["entity_id"],
                chunk["name_norm"]
            )
        )

        address_choices = dict(
            zip(
                chunk["entity_id"],
                chunk["address_norm"]
            )
        )

        for _, s1row in recall_s1.iterrows():

            s1_id = s1row["entity_id"]

            # -------------------------
            # NAME BLOCKING
            # -------------------------

            if s1row["name_norm"]:

                matches = process.extract(
                    s1row["name_norm"],
                    name_choices,
                    scorer=fuzz.ratio,
                    limit=TOP_K
                )

                for _, score, entity_id in matches:

                    old = best_candidates[s1_id].get(entity_id, 0)

                    if score > old:
                        best_candidates[s1_id][entity_id] = score


            # -------------------------
            # ADDRESS BLOCKING
            # -------------------------

            if s1row["address_norm"]:

                matches = process.extract(
                    s1row["address_norm"],
                    address_choices,
                    scorer=fuzz.ratio,
                    limit=TOP_K
                )

                for _, score, entity_id in matches:

                    old = best_candidates[s1_id].get(entity_id, 0)

                    if score > old:
                        best_candidates[s1_id][entity_id] = score

        if (chunk_no + 1) % 10 == 0:
            print(
                f"  processed {(chunk_no + 1) * CHUNK_SIZE:,} rows"
            )

    print(f"{source_name} complete.")

Processing S2...
  processed 1,000,000 rows
  processed 2,000,000 rows
  processed 3,000,000 rows
  processed 4,000,000 rows
  processed 5,000,000 rows
S2 complete.

Processing S3...
  processed 1,000,000 rows
  processed 2,000,000 rows
  processed 3,000,000 rows
  processed 4,000,000 rows
  processed 5,000,000 rows
S3 complete.

In [ ]:
# Calculate full-source blocking recall

found = 0
total = 0

recall_details = []

for s1_id, true_ids in gt_lookup.items():

    candidates_for_s1 = set(
        best_candidates.get(s1_id, {}).keys()
    )

    matched = true_ids & candidates_for_s1

    found += len(matched)
    total += len(true_ids)

    recall_details.append({
        "s1_id": s1_id,
        "true_matches": len(true_ids),
        "found": len(matched),
        "missed": len(true_ids - candidates_for_s1)
    })

print("====================================")
print("FULL-SOURCE BLOCKING RECALL")
print("====================================")
print("True matches:", total)
print("Found:", found)
print("Missed:", total - found)

if total:
    print(
        "Blocking Recall:",
        round(found / total, 4)
    )

    print(
        "Blocking Recall %:",
        round(found / total * 100, 2),
        "%"
    )

====================================
FULL-SOURCE BLOCKING RECALL
====================================
True matches: 322
Found: 305
Missed: 17
Blocking Recall: 0.9472
Blocking Recall %: 94.72 %

In [ ]:
# Find the 17 missed true matches

missed_rows = []

for s1_id, true_ids in gt_lookup.items():

    candidate_ids = set(
        best_candidates.get(s1_id, {}).keys()
    )

    missed_ids = true_ids - candidate_ids

    for entity_id in missed_ids:
        missed_rows.append({
            "source1_entity_id": s1_id,
            "missed_entity_id": entity_id
        })

missed_df = pd.DataFrame(missed_rows)

print("Missed true pairs:", len(missed_df))
print(missed_df.to_string(index=False))

Missed true pairs: 17
source1_entity_id missed_entity_id
     S1-630223771     S3-697578371
     S1-630223771     S3-815538600
     S1-630223771     S3-587424087
     S1-970518712     S3-460357940
     S1-912508322     S2-276782865
     S1-377745466      S3-70942743
     S1-216181354     S3-317748253
     S1-216181354     S3-685337179
     S1-851869949     S2-915265864
     S1-597762257     S3-426660831
     S1-134898809     S2-156312637
     S1-970972284     S3-807299919
     S1-800482427     S3-355590735
     S1-976369483     S2-546179661
     S1-666876590     S2-975207252
     S1-666876590     S2-185860935
     S1-277072715     S2-276736886

In [ ]:
# Find the 17 missed true matches

missed_rows = []

for s1_id, true_ids in gt_lookup.items():

    candidate_ids = set(
        best_candidates.get(s1_id, {}).keys()
    )

    missed_ids = true_ids - candidate_ids

    for entity_id in missed_ids:
        missed_rows.append({
            "source1_entity_id": s1_id,
            "missed_entity_id": entity_id
        })

missed_df = pd.DataFrame(missed_rows)

print("Missed true pairs:", len(missed_df))
print(missed_df.to_string(index=False))

Missed true pairs: 17
source1_entity_id missed_entity_id
     S1-630223771     S3-697578371
     S1-630223771     S3-815538600
     S1-630223771     S3-587424087
     S1-970518712     S3-460357940
     S1-912508322     S2-276782865
     S1-377745466      S3-70942743
     S1-216181354     S3-317748253
     S1-216181354     S3-685337179
     S1-851869949     S2-915265864
     S1-597762257     S3-426660831
     S1-134898809     S2-156312637
     S1-970972284     S3-807299919
     S1-800482427     S3-355590735
     S1-976369483     S2-546179661
     S1-666876590     S2-975207252
     S1-666876590     S2-185860935
     S1-277072715     S2-276736886

In [ ]:
# Show the S1 records corresponding to the misses

missed_s1_ids = missed_df["source1_entity_id"].unique()

print(
    recall_s1[
        recall_s1["entity_id"].isin(missed_s1_ids)
    ][
        ["entity_id", "business_name", "business_address", "country"]
    ].to_string(index=False)
)

   entity_id                      business_name                                                                                                               business_address country
S1-377745466                      B+ Retail Inc                                                                                            1712 Montebello Avenue, Phoenix, AZ      US
S1-851869949         Custom Wealth Services LLC                                                                                              OH, Columbus, 5559 Orville Avenue      US
S1-597762257    Green Logistics Private Limited                                                                               E-7, Second Floor, New Delhi, South Delhi, Delhi   India
S1-976369483                      FUE Pgim Care                                                                                                    211 Dewey Road, IL, Rockton      US
S1-134898809                    Corner Hypnosis                                                                                           26 Stone Street, Unit 3, Beverly, MA      US
S1-277072715   Shiva Management Private Limited                               D No. 20-6-3/12, Dantuluri Vari Street, Ayodyanagar, Vijayawada (Urban), Krishna, Andhra Pradesh   India
S1-666876590                 Ss Systems Limited                                                       A-1, Malad (West), Mumbai, Maharashtra, 401, Rahul Apartment, Marve Road   India
S1-216181354 United Consultants Private Limited                                              1/522A, Survey No 52, Rajput Associates, Kolkhe, Panvel, Raigarh(Mh), Maharashtra   India
S1-630223771              All International LLP Office 105, Flr-1, Sujata Chambers, Abhaychand Gandhi Marg, Mirchi Gully Masjid Stn Man, Dvi, Mumbai, Mumbai City, Maharashtra   India
S1-970518712            Trident Welfare Society                                                                 9/2113, Gali No.-7 Kailash Nagar, New Delhi, East Delhi, Delhi   India
S1-912508322              Shiv Technologies LLP                                                    42, 16Th Cross, 8Th Main Road, Malleswaram, Bengaluru, Bangalore, Karnataka   India
S1-970972284  Gujarat Guru Agro Private Limited                                Bihar, Pakki Sarai Road, Muzaffarpur, Near Abbda High School Azad Market, 3Rd Floor, Mithanpura   India
S1-800482427             B+ Biotechnologies LLC                                                                                  328 Buckingham Street, Unit 414, Columbus, OH      US

In [ ]:
# Show every missed S1 together with the TRUE entity ID that was missed

missed_details = []

for s1_id, true_ids in gt_lookup.items():

    candidate_ids = set(
        best_candidates.get(s1_id, {}).keys()
    )

    for true_id in (true_ids - candidate_ids):

        s1_row = recall_s1[
            recall_s1["entity_id"] == s1_id
        ].iloc[0]

        missed_details.append({
            "s1_id": s1_id,
            "s1_name": s1_row["business_name"],
            "s1_address": s1_row["business_address"],
            "country": s1_row["country"],
            "TRUE_MATCH": true_id
        })

missed_details_df = pd.DataFrame(missed_details)

print(
    missed_details_df.to_string(index=False)
)

       s1_id                            s1_name                                                                                                                     s1_address country   TRUE_MATCH
S1-630223771              All International LLP Office 105, Flr-1, Sujata Chambers, Abhaychand Gandhi Marg, Mirchi Gully Masjid Stn Man, Dvi, Mumbai, Mumbai City, Maharashtra   India S3-697578371
S1-630223771              All International LLP Office 105, Flr-1, Sujata Chambers, Abhaychand Gandhi Marg, Mirchi Gully Masjid Stn Man, Dvi, Mumbai, Mumbai City, Maharashtra   India S3-815538600
S1-630223771              All International LLP Office 105, Flr-1, Sujata Chambers, Abhaychand Gandhi Marg, Mirchi Gully Masjid Stn Man, Dvi, Mumbai, Mumbai City, Maharashtra   India S3-587424087
S1-970518712            Trident Welfare Society                                                                 9/2113, Gali No.-7 Kailash Nagar, New Delhi, East Delhi, Delhi   India S3-460357940
S1-912508322              Shiv Technologies LLP                                                    42, 16Th Cross, 8Th Main Road, Malleswaram, Bengaluru, Bangalore, Karnataka   India S2-276782865
S1-377745466                      B+ Retail Inc                                                                                            1712 Montebello Avenue, Phoenix, AZ      US  S3-70942743
S1-216181354 United Consultants Private Limited                                              1/522A, Survey No 52, Rajput Associates, Kolkhe, Panvel, Raigarh(Mh), Maharashtra   India S3-317748253
S1-216181354 United Consultants Private Limited                                              1/522A, Survey No 52, Rajput Associates, Kolkhe, Panvel, Raigarh(Mh), Maharashtra   India S3-685337179
S1-851869949         Custom Wealth Services LLC                                                                                              OH, Columbus, 5559 Orville Avenue      US S2-915265864
S1-597762257    Green Logistics Private Limited                                                                               E-7, Second Floor, New Delhi, South Delhi, Delhi   India S3-426660831
S1-134898809                    Corner Hypnosis                                                                                           26 Stone Street, Unit 3, Beverly, MA      US S2-156312637
S1-970972284  Gujarat Guru Agro Private Limited                                Bihar, Pakki Sarai Road, Muzaffarpur, Near Abbda High School Azad Market, 3Rd Floor, Mithanpura   India S3-807299919
S1-800482427             B+ Biotechnologies LLC                                                                                  328 Buckingham Street, Unit 414, Columbus, OH      US S3-355590735
S1-976369483                      FUE Pgim Care                                                                                                    211 Dewey Road, IL, Rockton      US S2-546179661
S1-666876590                 Ss Systems Limited                                                       A-1, Malad (West), Mumbai, Maharashtra, 401, Rahul Apartment, Marve Road   India S2-975207252
S1-666876590                 Ss Systems Limited                                                       A-1, Malad (West), Mumbai, Maharashtra, 401, Rahul Apartment, Marve Road   India S2-185860935
S1-277072715   Shiva Management Private Limited                               D No. 20-6-3/12, Dantuluri Vari Street, Ayodyanagar, Vijayawada (Urban), Krishna, Andhra Pradesh   India S2-276736886

In [ ]:
# Show the candidate scores for each missed S1

for s1_id in missed_details_df["s1_id"].unique():

    print("\n" + "=" * 100)
    print("S1:", s1_id)

    print(
        missed_details_df[
            missed_details_df["s1_id"] == s1_id
        ][["s1_name", "s1_address", "TRUE_MATCH"]]
        .to_string(index=False)
    )

    print("\nBest candidates found:")

    candidate_dict = best_candidates.get(s1_id, {})

    top_candidates = sorted(
        candidate_dict.items(),
        key=lambda x: x[1],
        reverse=True
    )[:10]

    for entity_id, score in top_candidates:
        print(entity_id, round(score, 2))

====================================================================================================
S1: S1-630223771
              s1_name                                                                                                                     s1_address   TRUE_MATCH
All International LLP Office 105, Flr-1, Sujata Chambers, Abhaychand Gandhi Marg, Mirchi Gully Masjid Stn Man, Dvi, Mumbai, Mumbai City, Maharashtra S3-697578371
All International LLP Office 105, Flr-1, Sujata Chambers, Abhaychand Gandhi Marg, Mirchi Gully Masjid Stn Man, Dvi, Mumbai, Mumbai City, Maharashtra S3-815538600
All International LLP Office 105, Flr-1, Sujata Chambers, Abhaychand Gandhi Marg, Mirchi Gully Masjid Stn Man, Dvi, Mumbai, Mumbai City, Maharashtra S3-587424087

Best candidates found:
S2-461511926 97.56
S3-592434928 97.56
S3-632094114 97.56
S3-88826988 97.56
S2-494260820 97.05
S2-327912797 95.24
S3-640430666 95.24
S3-950169162 95.24
S3-744610138 93.02
S3-617062320 93.02

====================================================================================================
S1: S1-970518712
                s1_name                                                     s1_address   TRUE_MATCH
Trident Welfare Society 9/2113, Gali No.-7 Kailash Nagar, New Delhi, East Delhi, Delhi S3-460357940

Best candidates found:
S3-274560833 100.0
S3-849723066 100.0
S3-844683426 93.33
S2-522871970 91.3
S2-382984512 91.3
S3-740708797 91.3
S2-239226917 91.23
S2-286902096 90.91
S3-529289587 88.89
S3-670426842 88.89

====================================================================================================
S1: S1-912508322
              s1_name                                                                  s1_address   TRUE_MATCH
Shiv Technologies LLP 42, 16Th Cross, 8Th Main Road, Malleswaram, Bengaluru, Bangalore, Karnataka S2-276782865

Best candidates found:
S2-749136639 100.0
S2-732911972 100.0
S3-471697968 100.0
S3-164901300 100.0
S2-777849726 97.67
S2-334957677 95.45
S2-265073681 95.45
S2-361992349 95.45
S3-56599744 95.45
S3-796422850 95.0

====================================================================================================
S1: S1-377745466
      s1_name                          s1_address  TRUE_MATCH
B+ Retail Inc 1712 Montebello Avenue, Phoenix, AZ S3-70942743

Best candidates found:
S2-981963456 93.33
S2-722817677 93.33
S2-992224961 92.31
S3-836170816 92.31
S3-695053245 92.31
S2-880281305 91.67
S2-322197590 91.67
S3-402918963 91.67
S2-808950576 91.53
S2-346552302 90.91

====================================================================================================
S1: S1-216181354
                           s1_name                                                                        s1_address   TRUE_MATCH
United Consultants Private Limited 1/522A, Survey No 52, Rajput Associates, Kolkhe, Panvel, Raigarh(Mh), Maharashtra S3-317748253
United Consultants Private Limited 1/522A, Survey No 52, Rajput Associates, Kolkhe, Panvel, Raigarh(Mh), Maharashtra S3-685337179

Best candidates found:
S2-498484682 100.0
S2-675797911 100.0
S2-653496117 100.0
S2-393523895 100.0
S2-28294847 100.0
S3-540528800 100.0
S3-542285423 100.0
S3-174511368 100.0
S3-786567104 100.0
S3-22116727 100.0

====================================================================================================
S1: S1-851869949
                   s1_name                        s1_address   TRUE_MATCH
Custom Wealth Services LLC OH, Columbus, 5559 Orville Avenue S2-915265864

Best candidates found:
S3-807524060 100.0
S2-801813753 91.67
S2-255987479 87.27
S2-672449411 87.27
S3-790904689 86.79
S2-446383065 84.62
S2-936663244 84.62
S2-244924533 84.62
S2-8792402 84.62
S3-149558865 84.62

====================================================================================================
S1: S1-597762257
                        s1_name                                       s1_address   TRUE_MATCH
Green Logistics Private Limited E-7, Second Floor, New Delhi, South Delhi, Delhi S3-426660831

Best candidates found:
S2-781225628 100.0
S2-713066236 100.0
S2-17865229 100.0
S2-797785555 100.0
S2-966326724 100.0
S2-750318376 100.0
S2-696903537 100.0
S2-733706791 100.0
S2-538234477 100.0
S2-25860300 100.0

====================================================================================================
S1: S1-134898809
        s1_name                           s1_address   TRUE_MATCH
Corner Hypnosis 26 Stone Street, Unit 3, Beverly, MA S2-156312637

Best candidates found:
S2-605743649 100.0
S2-844739727 100.0
S2-738906877 100.0
S2-261413077 100.0
S2-112921551 100.0
S2-77278822 100.0
S2-227443036 100.0
S2-740975299 100.0
S2-628884920 100.0
S2-453783472 100.0

====================================================================================================
S1: S1-970972284
                          s1_name                                                                                      s1_address   TRUE_MATCH
Gujarat Guru Agro Private Limited Bihar, Pakki Sarai Road, Muzaffarpur, Near Abbda High School Azad Market, 3Rd Floor, Mithanpura S3-807299919

Best candidates found:
S2-579880840 100.0
S2-381030114 88.89
S2-905034230 88.89
S2-808553104 88.89
S2-3184074 88.89
S2-836252692 88.89
S3-712345863 88.89
S3-493261339 88.89
S3-222544235 88.89
S3-47760090 88.89

====================================================================================================
S1: S1-800482427
               s1_name                                    s1_address   TRUE_MATCH
B+ Biotechnologies LLC 328 Buckingham Street, Unit 414, Columbus, OH S3-355590735

Best candidates found:
S3-338689364 97.44
S3-321919925 95.24
S2-754778296 93.02
S3-410809547 93.02
S2-187567643 91.3
S2-472242194 90.91
S2-146732736 90.91
S2-317655362 90.91
S2-986107233 90.91
S2-512134984 90.91

====================================================================================================
S1: S1-976369483
      s1_name                  s1_address   TRUE_MATCH
FUE Pgim Care 211 Dewey Road, IL, Rockton S2-546179661

Best candidates found:
S3-960615760 92.31
S2-984109039 86.96
S2-896291492 86.96
S2-268873536 86.96
S2-856609454 86.67
S2-106027155 84.62
S2-330772737 84.62
S3-803105346 84.62
S2-552765718 80.0
S2-759636115 78.57

====================================================================================================
S1: S1-666876590
           s1_name                                                               s1_address   TRUE_MATCH
Ss Systems Limited A-1, Malad (West), Mumbai, Maharashtra, 401, Rahul Apartment, Marve Road S2-975207252
Ss Systems Limited A-1, Malad (West), Mumbai, Maharashtra, 401, Rahul Apartment, Marve Road S2-185860935

Best candidates found:
S3-991776952 100.0
S3-644650299 100.0
S3-20969768 100.0
S3-847656632 100.0
S2-469601959 92.86
S2-300382601 92.86
S2-878618531 92.86
S2-985110581 92.86
S2-550619096 92.86
S3-735753371 92.86

====================================================================================================
S1: S1-277072715
                         s1_name                                                                                       s1_address   TRUE_MATCH
Shiva Management Private Limited D No. 20-6-3/12, Dantuluri Vari Street, Ayodyanagar, Vijayawada (Urban), Krishna, Andhra Pradesh S2-276736886

Best candidates found:
S2-927462812 100.0
S2-9236175 100.0
S2-903666409 100.0
S2-927450412 100.0
S2-446328301 100.0
S2-440507245 100.0
S2-520642235 100.0
S3-202888207 100.0
S3-968286433 100.0
S3-658771019 100.0

In [ ]:
# Find the actual records for the 17 missed true matches

missed_ids = set(missed_df["missed_entity_id"])

missed_records = []

for source_name, file_path in [
    ("S2", TRAIN_DIR / "train_source2.tsv"),
    ("S3", TRAIN_DIR / "train_source3.tsv")
]:
    
    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        dtype=str,
        chunksize=100_000
    ):
        
        found_rows = chunk[
            chunk["entity_id"].isin(missed_ids)
        ]
        
        if len(found_rows):
            found_rows = found_rows.copy()
            found_rows["source"] = source_name
            missed_records.append(found_rows)

missed_records = pd.concat(
    missed_records,
    ignore_index=True
)

print(
    missed_records[
        [
            "entity_id",
            "business_name",
            "business_address",
            "country",
            "source"
        ]
    ].to_string(index=False)
)

   entity_id                         business_name                                                                            business_address country source
S2-915265864            Custom Wealth LLC Partners                                               555 ORVILLE AVENUE, PO BOX 3877, COLUMBUS, OH      US     S2
S2-975207252                 एसएस सिस्टम्स लिमिटेड            A-3, 401, RAHUL APARTMENT, MARVE ROAD, MUMBAI SUBURBAN, MALAD (WEST), महाराष्ट्र   India     S2
S2-156312637                              Brixlyra                                                        PMB 9599, MA, BEVERLY, 0026 STONE ST      US     S2
S2-185860935                 एसएस सिस्टम्स लिमिटेड                                  A-3, 401, RAHUL APARTMENT, MARVE ROAD, MUMBAI, Maharashtra   India     S2
S2-546179661                    FUE Care (Service)                                                                   IL, ROCKTON, 211 DEWEY RD      US     S2
S2-276782865            ಶಿವ್ ಟೆಕ್ನಾಲಜೀಸ್ ಎಲ್ಎಲ್‌ಪಿ                                                         Karnataka, BENGALURU, 42, BANGALORE   India     S2
S2-276736886    శివ మేనేజ్‌మెంట్ ప్రైవేట్ లిమిటెడ్ #20-6-3/12, KRISHNA, VIJAYAWADA (URBAN), Andhra Pradesh, DANTULURI VARI STREET, AYODYANAGAR   India     S2
S3-587424087                        All LLP Center                                                                 Office C-105, Mumbai Ii, MH   India     S3
S3-815538600                   ऑल इंटरनेशनल एलएलपी                                                                 Office C-105, Mumbai Ii, MH   India     S3
S3-317748253 यूनाइटेड कंसल्टेंट्स प्राइवेट लिमिटेड                                                                001/522A, Panvel, महाराष्ट्र   India     S3
S3-355590735                       B+ LLC Services                                                                                         NaN      US     S3
S3-460357940               Trident Society Welfare                                                           9/2113, Delhi, East Delhi, दिल्ली   India     S3
S3-697578371                   ऑल इंटरनेशनल एलएलपी                                            Office C-105, Mumbai (SUBURBAN), MH, Mumbai City   India     S3
S3-426660831    ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड                                                     South Delhi, No. 225 E-7, DL, New Delhi   India     S3
S3-685337179 यूनाइटेड कंसल्टेंट्स प्राइवेट लिमिटेड                                                           001/522A, Panvel, Raigarh(mh), MH   India     S3
 S3-70942743                       B+ Inc Services                                                    Arizona, Phoenix, 1712 Montebello Avenue      US     S3
S3-807299919    गुजरात गुरु एग्रो प्राइवेट लिमिटेड                                               Muzaffarpur, Mithanpura, Pakki Sarai Road, BR   India     S3

In [ ]:
# Compare each missed true match with its S1 record

for _, row in missed_df.iterrows():

    s1_id = row["source1_entity_id"]
    true_id = row["missed_entity_id"]

    s1_row = recall_s1[
        recall_s1["entity_id"] == s1_id
    ].iloc[0]

    true_row = missed_records[
        missed_records["entity_id"] == true_id
    ].iloc[0]

    print("\n" + "=" * 100)
    print("S1:", s1_id)
    print("S1 NAME   :", s1_row["business_name"])
    print("S1 ADDRESS:", s1_row["business_address"])
    print("S1 COUNTRY:", s1_row["country"])

    print("\nTRUE:", true_id)
    print("TRUE NAME   :", true_row["business_name"])
    print("TRUE ADDRESS:", true_row["business_address"])
    print("TRUE COUNTRY:", true_row["country"])

====================================================================================================
S1: S1-630223771
S1 NAME   : All International LLP
S1 ADDRESS: Office 105, Flr-1, Sujata Chambers, Abhaychand Gandhi Marg, Mirchi Gully Masjid Stn Man, Dvi, Mumbai, Mumbai City, Maharashtra
S1 COUNTRY: India

TRUE: S3-697578371
TRUE NAME   : ऑल इंटरनेशनल एलएलपी
TRUE ADDRESS: Office C-105, Mumbai (SUBURBAN), MH, Mumbai City
TRUE COUNTRY: India

====================================================================================================
S1: S1-630223771
S1 NAME   : All International LLP
S1 ADDRESS: Office 105, Flr-1, Sujata Chambers, Abhaychand Gandhi Marg, Mirchi Gully Masjid Stn Man, Dvi, Mumbai, Mumbai City, Maharashtra
S1 COUNTRY: India

TRUE: S3-815538600
TRUE NAME   : ऑल इंटरनेशनल एलएलपी
TRUE ADDRESS: Office C-105, Mumbai Ii, MH
TRUE COUNTRY: India

====================================================================================================
S1: S1-630223771
S1 NAME   : All International LLP
S1 ADDRESS: Office 105, Flr-1, Sujata Chambers, Abhaychand Gandhi Marg, Mirchi Gully Masjid Stn Man, Dvi, Mumbai, Mumbai City, Maharashtra
S1 COUNTRY: India

TRUE: S3-587424087
TRUE NAME   : All LLP Center
TRUE ADDRESS: Office C-105, Mumbai Ii, MH
TRUE COUNTRY: India

====================================================================================================
S1: S1-970518712
S1 NAME   : Trident Welfare Society
S1 ADDRESS: 9/2113, Gali No.-7 Kailash Nagar, New Delhi, East Delhi, Delhi
S1 COUNTRY: India

TRUE: S3-460357940
TRUE NAME   : Trident Society Welfare
TRUE ADDRESS: 9/2113, Delhi, East Delhi, दिल्ली
TRUE COUNTRY: India

====================================================================================================
S1: S1-912508322
S1 NAME   : Shiv Technologies LLP
S1 ADDRESS: 42, 16Th Cross, 8Th Main Road, Malleswaram, Bengaluru, Bangalore, Karnataka
S1 COUNTRY: India

TRUE: S2-276782865
TRUE NAME   : ಶಿವ್ ಟೆಕ್ನಾಲಜೀಸ್ ಎಲ್ಎಲ್‌ಪಿ
TRUE ADDRESS: Karnataka, BENGALURU, 42, BANGALORE
TRUE COUNTRY: India

====================================================================================================
S1: S1-377745466
S1 NAME   : B+ Retail Inc
S1 ADDRESS: 1712 Montebello Avenue, Phoenix, AZ
S1 COUNTRY: US

TRUE: S3-70942743
TRUE NAME   : B+ Inc Services
TRUE ADDRESS: Arizona, Phoenix, 1712 Montebello Avenue
TRUE COUNTRY: US

====================================================================================================
S1: S1-216181354
S1 NAME   : United Consultants Private Limited
S1 ADDRESS: 1/522A, Survey No 52, Rajput Associates, Kolkhe, Panvel, Raigarh(Mh), Maharashtra
S1 COUNTRY: India

TRUE: S3-317748253
TRUE NAME   : यूनाइटेड कंसल्टेंट्स प्राइवेट लिमिटेड
TRUE ADDRESS: 001/522A, Panvel, महाराष्ट्र
TRUE COUNTRY: India

====================================================================================================
S1: S1-216181354
S1 NAME   : United Consultants Private Limited
S1 ADDRESS: 1/522A, Survey No 52, Rajput Associates, Kolkhe, Panvel, Raigarh(Mh), Maharashtra
S1 COUNTRY: India

TRUE: S3-685337179
TRUE NAME   : यूनाइटेड कंसल्टेंट्स प्राइवेट लिमिटेड
TRUE ADDRESS: 001/522A, Panvel, Raigarh(mh), MH
TRUE COUNTRY: India

====================================================================================================
S1: S1-851869949
S1 NAME   : Custom Wealth Services LLC
S1 ADDRESS: OH, Columbus, 5559 Orville Avenue
S1 COUNTRY: US

TRUE: S2-915265864
TRUE NAME   : Custom Wealth LLC Partners
TRUE ADDRESS: 555 ORVILLE AVENUE, PO BOX 3877, COLUMBUS, OH
TRUE COUNTRY: US

====================================================================================================
S1: S1-597762257
S1 NAME   : Green Logistics Private Limited
S1 ADDRESS: E-7, Second Floor, New Delhi, South Delhi, Delhi
S1 COUNTRY: India

TRUE: S3-426660831
TRUE NAME   : ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड
TRUE ADDRESS: South Delhi, No. 225 E-7, DL, New Delhi
TRUE COUNTRY: India

====================================================================================================
S1: S1-134898809
S1 NAME   : Corner Hypnosis
S1 ADDRESS: 26 Stone Street, Unit 3, Beverly, MA
S1 COUNTRY: US

TRUE: S2-156312637
TRUE NAME   : Brixlyra
TRUE ADDRESS: PMB 9599, MA, BEVERLY, 0026 STONE ST
TRUE COUNTRY: US

====================================================================================================
S1: S1-970972284
S1 NAME   : Gujarat Guru Agro Private Limited
S1 ADDRESS: Bihar, Pakki Sarai Road, Muzaffarpur, Near Abbda High School Azad Market, 3Rd Floor, Mithanpura
S1 COUNTRY: India

TRUE: S3-807299919
TRUE NAME   : गुजरात गुरु एग्रो प्राइवेट लिमिटेड
TRUE ADDRESS: Muzaffarpur, Mithanpura, Pakki Sarai Road, BR
TRUE COUNTRY: India

====================================================================================================
S1: S1-800482427
S1 NAME   : B+ Biotechnologies LLC
S1 ADDRESS: 328 Buckingham Street, Unit 414, Columbus, OH
S1 COUNTRY: US

TRUE: S3-355590735
TRUE NAME   : B+ LLC Services
TRUE ADDRESS: nan
TRUE COUNTRY: US

====================================================================================================
S1: S1-976369483
S1 NAME   : FUE Pgim Care
S1 ADDRESS: 211 Dewey Road, IL, Rockton
S1 COUNTRY: US

TRUE: S2-546179661
TRUE NAME   : FUE Care (Service)
TRUE ADDRESS: IL, ROCKTON, 211 DEWEY RD
TRUE COUNTRY: US

====================================================================================================
S1: S1-666876590
S1 NAME   : Ss Systems Limited
S1 ADDRESS: A-1, Malad (West), Mumbai, Maharashtra, 401, Rahul Apartment, Marve Road
S1 COUNTRY: India

TRUE: S2-975207252
TRUE NAME   : एसएस सिस्टम्स लिमिटेड
TRUE ADDRESS: A-3, 401, RAHUL APARTMENT, MARVE ROAD, MUMBAI SUBURBAN, MALAD (WEST), महाराष्ट्र
TRUE COUNTRY: India

====================================================================================================
S1: S1-666876590
S1 NAME   : Ss Systems Limited
S1 ADDRESS: A-1, Malad (West), Mumbai, Maharashtra, 401, Rahul Apartment, Marve Road
S1 COUNTRY: India

TRUE: S2-185860935
TRUE NAME   : एसएस सिस्टम्स लिमिटेड
TRUE ADDRESS: A-3, 401, RAHUL APARTMENT, MARVE ROAD, MUMBAI, Maharashtra
TRUE COUNTRY: India

====================================================================================================
S1: S1-277072715
S1 NAME   : Shiva Management Private Limited
S1 ADDRESS: D No. 20-6-3/12, Dantuluri Vari Street, Ayodyanagar, Vijayawada (Urban), Krishna, Andhra Pradesh
S1 COUNTRY: India

TRUE: S2-276736886
TRUE NAME   : శివ మేనేజ్‌మెంట్ ప్రైవేట్ లిమిటెడ్
TRUE ADDRESS: #20-6-3/12, KRISHNA, VIJAYAWADA (URBAN), Andhra Pradesh, DANTULURI VARI STREET, AYODYANAGAR
TRUE COUNTRY: India

In [ ]:
def extract_numbers(text):
    if pd.isna(text):
        return set()

    text = str(text)

    # Capture useful numbers including forms like:
    # 105, 20-6-3/12, 1522A, etc.
    tokens = re.findall(
        r'\d+(?:[-/]\d+)*(?:[A-Za-z])?',
        text
    )

    return set(tokens)


recall_s1["number_tokens"] = (
    recall_s1["business_address"]
    .map(extract_numbers)
)

print(
    recall_s1[
        ["entity_id", "business_address", "number_tokens"]
    ].head(10).to_string(index=False)
)

   entity_id                                                                                                          business_address number_tokens
S1-925783039                                                                                    1795 Westchester Drive, High Point, NC        {1795}
S1-773889195                                                                                           17560 Ellis Road, Tahlequah, OK       {17560}
S1-377745466                                                                                       1712 Montebello Avenue, Phoenix, AZ        {1712}
S1-133037285                                                                         2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD        {2100}
S1-755362802                                                                      797, Lake Town Block A, Kolkata, Howrah, West Bengal         {797}
S1-851869949                                                                                         OH, Columbus, 5559 Orville Avenue        {5559}
S1-785847572 2505, Tower 1, Oakwood, Runwal Greens, Mulund Goreagon Link Road, Near Fortis Hospital, Bhandup West, Mumbai, Maharashtra     {2505, 1}
 S1-27541239                                                                              1111 Church Street, Unit 2007, Nashville, TN  {1111, 2007}
S1-629417405                                                                                     337 Oakland Avenue, Michigan City, IN         {337}
 S1-22305073                                                               294 Meadowcreek Drive, Unit Unit 2, Village Of Pewaukee, WI      {2, 294}

In [ ]:
for _, row in missed_df.iterrows():

    s1_id = row["source1_entity_id"]
    true_id = row["missed_entity_id"]

    s1_row = recall_s1[
        recall_s1["entity_id"] == s1_id
    ].iloc[0]

    true_row = missed_records[
        missed_records["entity_id"] == true_id
    ].iloc[0]

    s1_numbers = extract_numbers(
        s1_row["business_address"]
    )

    true_numbers = extract_numbers(
        true_row["business_address"]
    )

    common_numbers = s1_numbers & true_numbers

    print(
        s1_id,
        "→",
        true_id,
        "| common numbers:",
        common_numbers
    )

S1-630223771 → S3-697578371 | common numbers: {'105'}
S1-630223771 → S3-815538600 | common numbers: {'105'}
S1-630223771 → S3-587424087 | common numbers: {'105'}
S1-970518712 → S3-460357940 | common numbers: {'9/2113'}
S1-912508322 → S2-276782865 | common numbers: {'42'}
S1-377745466 → S3-70942743 | common numbers: {'1712'}
S1-216181354 → S3-317748253 | common numbers: set()
S1-216181354 → S3-685337179 | common numbers: set()
S1-851869949 → S2-915265864 | common numbers: set()
S1-597762257 → S3-426660831 | common numbers: {'7'}
S1-134898809 → S2-156312637 | common numbers: set()
S1-970972284 → S3-807299919 | common numbers: set()
S1-800482427 → S3-355590735 | common numbers: set()
S1-976369483 → S2-546179661 | common numbers: {'211'}
S1-666876590 → S2-975207252 | common numbers: {'401'}
S1-666876590 → S2-185860935 | common numbers: {'401'}
S1-277072715 → S2-276736886 | common numbers: {'20-6-3/12'}

In [ ]:
re.sub(r"[^a-z0-9\s]", " ", x)

NameError: name 'x' is not defined

In [ ]:
def normalize_text_unicode(x):
    if pd.isna(x):
        return ""

    x = str(x).lower()

    replacements = {
        "private limited": "pvt ltd",
        "private ltd": "pvt ltd",
        "corporation": "corp",
        "incorporated": "inc",
        "limited": "ltd",
        "company": "co",
        "street": "st",
        "road": "rd",
        "avenue": "ave",
        "boulevard": "blvd",
        "drive": "dr",
        "lane": "ln",
        "highway": "hwy",
        "parkway": "pkwy",
        "apartment": "apt",
        "suite": "ste"
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    # Keep Unicode letters/numbers
    x = re.sub(r"[^\w\s]", " ", x, flags=re.UNICODE)
    x = re.sub(r"\s+", " ", x).strip()

    return x

In [ ]:

for _, row in missed_df.iterrows():

    s1_id = row["source1_entity_id"]
    true_id = row["missed_entity_id"]

    s1_row = recall_s1[
        recall_s1["entity_id"] == s1_id
    ].iloc[0]

    true_row = missed_records[
        missed_records["entity_id"] == true_id
    ].iloc[0]

    s1_numbers = extract_numbers(
        s1_row["business_address"]
    )

    true_numbers = extract_numbers(
        true_row["business_address"]
    )

    common_numbers = s1_numbers & true_numbers

    print(
        s1_id,
        "→",
        true_id,
        "| common numbers:",
        common_numbers
    )

S1-630223771 → S3-697578371 | common numbers: {'105'}
S1-630223771 → S3-815538600 | common numbers: {'105'}
S1-630223771 → S3-587424087 | common numbers: {'105'}
S1-970518712 → S3-460357940 | common numbers: {'9/2113'}
S1-912508322 → S2-276782865 | common numbers: {'42'}
S1-377745466 → S3-70942743 | common numbers: {'1712'}
S1-216181354 → S3-317748253 | common numbers: set()
S1-216181354 → S3-685337179 | common numbers: set()
S1-851869949 → S2-915265864 | common numbers: set()
S1-597762257 → S3-426660831 | common numbers: {'7'}
S1-134898809 → S2-156312637 | common numbers: set()
S1-970972284 → S3-807299919 | common numbers: set()
S1-800482427 → S3-355590735 | common numbers: set()
S1-976369483 → S2-546179661 | common numbers: {'211'}
S1-666876590 → S2-975207252 | common numbers: {'401'}
S1-666876590 → S2-185860935 | common numbers: {'401'}
S1-277072715 → S2-276736886 | common numbers: {'20-6-3/12'}

In [ ]:
# Test whether address-number blocking can recover the missed matches

number_recovered = 0

for _, row in missed_df.iterrows():

    s1_id = row["source1_entity_id"]
    true_id = row["missed_entity_id"]

    s1_row = recall_s1[
        recall_s1["entity_id"] == s1_id
    ].iloc[0]

    true_row = missed_records[
        missed_records["entity_id"] == true_id
    ].iloc[0]

    s1_numbers = extract_numbers(
        s1_row["business_address"]
    )

    true_numbers = extract_numbers(
        true_row["business_address"]
    )

    if s1_numbers & true_numbers:
        number_recovered += 1
        print(
            "RECOVERABLE:",
            s1_id,
            "→",
            true_id,
            "|",
            s1_numbers & true_numbers
        )

print("\n================================")
print("NUMBER BLOCKING TEST")
print("================================")
print("Missed true matches:", len(missed_df))
print("Recoverable by shared number:", number_recovered)
print(
    "Potential recovery:",
    round(number_recovered / len(missed_df) * 100, 2),
    "%"
)

RECOVERABLE: S1-630223771 → S3-697578371 | {'105'}
RECOVERABLE: S1-630223771 → S3-815538600 | {'105'}
RECOVERABLE: S1-630223771 → S3-587424087 | {'105'}
RECOVERABLE: S1-970518712 → S3-460357940 | {'9/2113'}
RECOVERABLE: S1-912508322 → S2-276782865 | {'42'}
RECOVERABLE: S1-377745466 → S3-70942743 | {'1712'}
RECOVERABLE: S1-597762257 → S3-426660831 | {'7'}
RECOVERABLE: S1-976369483 → S2-546179661 | {'211'}
RECOVERABLE: S1-666876590 → S2-975207252 | {'401'}
RECOVERABLE: S1-666876590 → S2-185860935 | {'401'}
RECOVERABLE: S1-277072715 → S2-276736886 | {'20-6-3/12'}

================================
NUMBER BLOCKING TEST
================================
Missed true matches: 17
Recoverable by shared number: 11
Potential recovery: 64.71 %

In [ ]:
# Add address-number candidates to the existing candidates

number_candidates = []

# Build number index from full S2 + S3
number_index = {}

for source_name, file_path in [
    ("S2", TRAIN_DIR / "train_source2.tsv"),
    ("S3", TRAIN_DIR / "train_source3.tsv")
]:
    print(f"Indexing {source_name}...")

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        dtype=str,
        chunksize=100_000
    ):
        chunk["number_tokens"] = chunk["business_address"].map(
            extract_numbers
        )

        for _, row in chunk.iterrows():
            for num in row["number_tokens"]:
                if num not in number_index:
                    number_index[num] = []

                number_index[num].append(row["entity_id"])

print("Number index created.")
print("Unique number keys:", len(number_index))

Indexing S2...
Indexing S3...
Number index created.
Unique number keys: 415754

In [ ]:
number_candidate_lookup = {}

for _, row in recall_s1.iterrows():
    s1_id = row["entity_id"]
    numbers = extract_numbers(row["business_address"])

    candidates = set()

    for num in numbers:
        candidates.update(number_index.get(num, []))

    number_candidate_lookup[s1_id] = candidates

print("S1 records:", len(number_candidate_lookup))

S1 records: 100

In [ ]:
improved_candidates = {}

for s1_id in gt_lookup:
    old = set(best_candidates.get(s1_id, {}).keys())
    new = number_candidate_lookup.get(s1_id, set())

    improved_candidates[s1_id] = old | new

found = sum(
    len(true_ids & improved_candidates.get(s1_id, set()))
    for s1_id, true_ids in gt_lookup.items()
)

total = sum(len(v) for v in gt_lookup.values())

print("True matches:", total)
print("Found:", found)
print("Missed:", total - found)
print("Blocking recall:", round(100 * found / total, 2), "%")

counts = [len(v) for v in improved_candidates.values()]
print("Average candidates per S1:", round(sum(counts) / len(counts), 2))
print("Maximum candidates for one S1:", max(counts))

True matches: 322
Found: 316
Missed: 6
Blocking recall: 98.14 %
Average candidates per S1: 50918.16
Maximum candidates for one S1: 377434

In [ ]:
# Check how frequent the numbers are for the missed matches

print("NUMBER FREQUENCY FOR MISSED TRUE MATCHES")
print("=" * 70)

for _, row in missed_df.iterrows():

    s1_id = row["source1_entity_id"]
    true_id = row["missed_entity_id"]

    s1_row = recall_s1[
        recall_s1["entity_id"] == s1_id
    ].iloc[0]

    true_row = missed_records[
        missed_records["entity_id"] == true_id
    ].iloc[0]

    s1_numbers = extract_numbers(
        s1_row["business_address"]
    )

    true_numbers = extract_numbers(
        true_row["business_address"]
    )

    common = s1_numbers & true_numbers

    if common:
        print(
            s1_id,
            "→",
            true_id,
            "| numbers:",
            common
        )

        for num in common:
            print(
                "   ",
                num,
                "=>",
                len(number_index.get(num, [])),
                "candidate records"
            )

NUMBER FREQUENCY FOR MISSED TRUE MATCHES
======================================================================
S1-630223771 → S3-697578371 | numbers: {'105'}
    105 => 21582 candidate records
S1-630223771 → S3-815538600 | numbers: {'105'}
    105 => 21582 candidate records
S1-630223771 → S3-587424087 | numbers: {'105'}
    105 => 21582 candidate records
S1-970518712 → S3-460357940 | numbers: {'9/2113'}
    9/2113 => 4 candidate records
S1-912508322 → S2-276782865 | numbers: {'42'}
    42 => 22073 candidate records
S1-377745466 → S3-70942743 | numbers: {'1712'}
    1712 => 1123 candidate records
S1-597762257 → S3-426660831 | numbers: {'7'}
    7 => 80328 candidate records
S1-976369483 → S2-546179661 | numbers: {'211'}
    211 => 11547 candidate records
S1-666876590 → S2-975207252 | numbers: {'401'}
    401 => 18672 candidate records
S1-666876590 → S2-185860935 | numbers: {'401'}
    401 => 18672 candidate records
S1-277072715 → S2-276736886 | numbers: {'20-6-3/12'}
    20-6-3/12 => 1 candidate records

In [ ]:
MAX_NUMBER_FREQUENCY = 100

for num in s1_numbers:
    matches = number_index.get(num, [])

    # Only use rare numbers for blocking
    if 0 < len(matches) <= MAX_NUMBER_FREQUENCY:
        candidate_ids.update(matches)

In [ ]:
# Rebuild candidates using ONLY rare numbers
candidate_ids = set()

MAX_NUMBER_FREQUENCY = 100

for num in s1_numbers:
    matches = number_index.get(num, [])

    if 0 < len(matches) <= MAX_NUMBER_FREQUENCY:
        candidate_ids.update(matches)

print("Number-blocking candidates:", len(candidate_ids))

Number-blocking candidates: 1

In [ ]:
# Check how many true matches are recovered

true_set = set(true_matches)

found = true_set.intersection(candidate_ids)
missed = true_set - candidate_ids

print("====================================")
print("NUMBER BLOCKING RECALL")
print("====================================")
print("True matches:", len(true_set))
print("Found:", len(found))
print("Missed:", len(missed))
print(
    "Blocking Recall:",
    round(len(found) / len(true_set), 4)
)
print(
    "Blocking Recall %:",
    round(len(found) / len(true_set) * 100, 2),
    "%"
)
print("Candidate count:", len(candidate_ids))

NameError: name 'true_matches' is not defined

In [ ]:
# Recreate true matches from the training ground truth

import pandas as pd

gt = pd.read_csv(
    TRAIN_DIR / "train_ground_truth.tsv",
    sep="\t",
    dtype=str
)

# Use the same 100 S1 records used for the blocking test
gt_sample = gt[gt["source1_entity_id"].isin(s1_sample["entity_id"])].copy()

true_matches = set()

for ids in gt_sample["matched_entity_ids"].dropna():
    for entity_id in ids.split(","):
        entity_id = entity_id.strip()
        if entity_id:
            true_matches.add(entity_id)

print("True matches:", len(true_matches))

NameError: name 's1_sample' is not defined

In [ ]:
import pandas as pd

# Load ground truth
gt = pd.read_csv(
    TRAIN_DIR / "train_ground_truth.tsv",
    sep="\t",
    dtype=str
)

# Take the first 100 S1 records directly from ground truth
gt_sample = gt.head(100).copy()

# Recreate all true matched S2/S3 IDs
true_matches = set()

for ids in gt_sample["matched_entity_ids"].dropna():
    for entity_id in ids.split(","):
        entity_id = entity_id.strip()
        if entity_id:
            true_matches.add(entity_id)

print("Ground-truth S1 records:", len(gt_sample))
print("True matches:", len(true_matches))

Ground-truth S1 records: 100
True matches: 343

In [ ]:
found = true_matches.intersection(candidate_ids)
missed = true_matches - candidate_ids

print("====================================")
print("NUMBER BLOCKING RECALL")
print("====================================")
print("True matches:", len(true_matches))
print("Found:", len(found))
print("Missed:", len(missed))
print("Blocking Recall:", round(len(found) / len(true_matches), 4))
print("Blocking Recall %:", round(len(found) / len(true_matches) * 100, 2), "%")
print("Candidate count:", len(candidate_ids))

====================================
NUMBER BLOCKING RECALL
====================================
True matches: 343
Found: 0
Missed: 343
Blocking Recall: 0.0
Blocking Recall %: 0.0 %
Candidate count: 1

In [ ]:
print("number_index exists:", "number_index" in globals())

if "number_index" in globals():
    print("Number index keys:", len(number_index))
    print("Example keys:", list(number_index.keys())[:10])

print("candidate_ids:", len(candidate_ids))

if "s1_numbers" in globals():
    print("s1_numbers type:", type(s1_numbers))
    print("s1_numbers:", s1_numbers)

number_index exists: True
Number index keys: 415754
Example keys: ['570/13', '105', '3/571', '19', '1/2', '914', '1702', '204', '63/2275/7', '282']
candidate_ids: 1
s1_numbers type: <class 'set'>
s1_numbers: {'20-6-3/12'}

In [ ]:
print(gt_sample[["source1_entity_id"]].head(10).to_string(index=False))
print("S1 records:", len(gt_sample))

source1_entity_id
        S1-965667
      S1-55344266
     S1-343815751
     S1-656753428
     S1-102811957
      S1-18727616
     S1-318373630
      S1-86989137
      S1-29845983
     S1-789009573
S1 records: 100

In [ ]:
import re

def extract_numbers(text):
    if pd.isna(text):
        return set()

    text = str(text)

    # Captures numbers such as:
    # 105
    # 9/2113
    # 20-6-3/12
    # 1712
    return set(re.findall(r'\d+(?:[/-]\d+)*', text))


# Get the 100 S1 IDs used in the ground-truth sample
sample_s1_ids = set(gt_sample["source1_entity_id"])

# Get the corresponding S1 records
s1_sample = s1[s1["entity_id"].isin(sample_s1_ids)].copy()

print("S1 sample records:", len(s1_sample))


# Rebuild candidates for ALL 100 S1 records
all_number_candidates = set()

for _, row in s1_sample.iterrows():

    # Extract numbers from BOTH name and address
    text = (
        str(row.get("business_name", "")) + " " +
        str(row.get("business_address", ""))
    )

    numbers = extract_numbers(text)

    for num in numbers:

        matches = number_index.get(num, [])

        # Only use rare numbers
        if 0 < len(matches) <= MAX_NUMBER_FREQUENCY:
            all_number_candidates.update(matches)


print("====================================")
print("NUMBER BLOCKING RECALL")
print("====================================")

found = true_matches.intersection(all_number_candidates)
missed = true_matches - all_number_candidates

print("True matches:", len(true_matches))
print("Found:", len(found))
print("Missed:", len(missed))

print(
    "Blocking Recall:",
    round(len(found) / len(true_matches), 4)
)

print(
    "Blocking Recall %:",
    round(len(found) / len(true_matches) * 100, 2),
    "%"
)

print("Candidate count:", len(all_number_candidates))

S1 sample records: 0
====================================
NUMBER BLOCKING RECALL
====================================
True matches: 343
Found: 0
Missed: 343
Blocking Recall: 0.0
Blocking Recall %: 0.0 %
Candidate count: 0

In [ ]:
# Load the TRAINING Source 1 explicitly
train_s1 = pd.read_csv(
    TRAIN_DIR / "train_source1.tsv",
    sep="\t",
    dtype=str
)

# Get the 100 S1 IDs from the ground truth
sample_s1_ids = set(gt_sample["source1_entity_id"])

# Select those exact training S1 records
s1_sample = train_s1[
    train_s1["entity_id"].isin(sample_s1_ids)
].copy()

print("Training S1 rows:", len(train_s1))
print("S1 sample records:", len(s1_sample))
print(s1_sample[["entity_id", "business_name"]].head())

Training S1 rows: 2206821
S1 sample records: 100
           entity_id                   business_name
80049   S1-262997549  Gabriella's Preferred Security
95863   S1-244810289        Celestial Memorial Trust
100976  S1-389414274            Benzer Intelli Group
104557  S1-439203009    Ace Producer Private Limited
114018  S1-862038247      Waters & Millar Aimei P.C.

In [ ]:
all_number_candidates = set()

for _, row in s1_sample.iterrows():

    text = (
        str(row["business_name"]) + " " +
        str(row["business_address"])
    )

    numbers = extract_numbers(text)

    for num in numbers:
        matches = number_index.get(num, [])

        if 0 < len(matches) <= MAX_NUMBER_FREQUENCY:
            all_number_candidates.update(matches)


found = true_matches.intersection(all_number_candidates)
missed = true_matches - all_number_candidates

print("====================================")
print("NUMBER BLOCKING RECALL")
print("====================================")
print("True matches:", len(true_matches))
print("Found:", len(found))
print("Missed:", len(missed))
print("Blocking Recall:", round(len(found) / len(true_matches), 4))
print("Blocking Recall %:", round(len(found) / len(true_matches) * 100, 2), "%")
print("Candidate count:", len(all_number_candidates))

====================================
NUMBER BLOCKING RECALL
====================================
True matches: 343
Found: 23
Missed: 320
Blocking Recall: 0.0671
Blocking Recall %: 6.71 %
Candidate count: 365

In [ ]:
# Diagnose why true matches are not being recovered

train_s2 = pd.read_csv(
    TRAIN_DIR / "train_source2.tsv",
    sep="\t",
    dtype=str
)

train_s3 = pd.read_csv(
    TRAIN_DIR / "train_source3.tsv",
    sep="\t",
    dtype=str
)

# Combine S2 + S3 for lookup
s23 = pd.concat([train_s2, train_s3], ignore_index=True)

s23_lookup = s23.set_index("entity_id")

print("S2 rows:", len(train_s2))
print("S3 rows:", len(train_s3))


# Check the first 20 missed true matches
diagnostic_rows = []

for s1_id in gt_sample["source1_entity_id"]:

    gt_row = gt_sample[
        gt_sample["source1_entity_id"] == s1_id
    ].iloc[0]

    matched_ids = str(gt_row["matched_entity_ids"])

    if matched_ids == "nan":
        continue

    s1_row = train_s1[
        train_s1["entity_id"] == s1_id
    ].iloc[0]

    s1_text = (
        str(s1_row["business_name"]) + " " +
        str(s1_row["business_address"])
    )

    s1_nums = extract_numbers(s1_text)

    for true_id in matched_ids.split(","):

        true_id = true_id.strip()

        if true_id not in all_number_candidates:

            if true_id not in s23_lookup.index:
                continue

            true_row = s23_lookup.loc[true_id]

            true_text = (
                str(true_row["business_name"]) + " " +
                str(true_row["business_address"])
            )

            true_nums = extract_numbers(true_text)

            common_nums = s1_nums.intersection(true_nums)

            indexed_counts = {
                n: len(number_index.get(n, []))
                for n in common_nums
            }

            diagnostic_rows.append({
                "s1_id": s1_id,
                "true_id": true_id,
                "s1_numbers": s1_nums,
                "true_numbers": true_nums,
                "common_numbers": common_nums,
                "index_frequency": indexed_counts
            })

            if len(diagnostic_rows) >= 20:
                break

    if len(diagnostic_rows) >= 20:
        break


diagnostic_df = pd.DataFrame(diagnostic_rows)

print("Missed-match examples:", len(diagnostic_df))

for _, r in diagnostic_df.iterrows():
    print("\n--------------------------------")
    print(r["s1_id"], "->", r["true_id"])
    print("S1 numbers:", r["s1_numbers"])
    print("TRUE numbers:", r["true_numbers"])
    print("COMMON:", r["common_numbers"])
    print("INDEX FREQUENCY:", r["index_frequency"])

S2 rows: 5034616
S3 rows: 5285603
Missed-match examples: 20

--------------------------------
S1-965667 -> S2-681193310
S1 numbers: {'85'}
TRUE numbers: set()
COMMON: set()
INDEX FREQUENCY: {}

--------------------------------
S1-965667 -> S2-743505751
S1 numbers: {'85'}
TRUE numbers: set()
COMMON: set()
INDEX FREQUENCY: {}

--------------------------------
S1-965667 -> S3-775321672
S1 numbers: {'85'}
TRUE numbers: {'85'}
COMMON: {'85'}
INDEX FREQUENCY: {'85': 12041}

--------------------------------
S1-965667 -> S3-11291185
S1 numbers: {'85'}
TRUE numbers: set()
COMMON: set()
INDEX FREQUENCY: {}

--------------------------------
S1-965667 -> S3-860443364
S1 numbers: {'85'}
TRUE numbers: set()
COMMON: set()
INDEX FREQUENCY: {}

--------------------------------
S1-55344266 -> S2-249013014
S1 numbers: {'2', '6', '29'}
TRUE numbers: {'2', '6', '29'}
COMMON: {'2', '6', '29'}
INDEX FREQUENCY: {'2': 198432, '6': 88612, '29': 30041}

--------------------------------
S1-55344266 -> S2-197070651
S1 numbers: {'2', '6', '29'}
TRUE numbers: {'2', '6', '29'}
COMMON: {'2', '6', '29'}
INDEX FREQUENCY: {'2': 198432, '6': 88612, '29': 30041}

--------------------------------
S1-55344266 -> S3-478195123
S1 numbers: {'2', '6', '29'}
TRUE numbers: {'2', '6', '29'}
COMMON: {'2', '6', '29'}
INDEX FREQUENCY: {'2': 198432, '6': 88612, '29': 30041}

--------------------------------
S1-55344266 -> S3-384364074
S1 numbers: {'2', '6', '29'}
TRUE numbers: {'2', '6', '29'}
COMMON: {'2', '6', '29'}
INDEX FREQUENCY: {'2': 198432, '6': 88612, '29': 30041}

--------------------------------
S1-343815751 -> S2-790675320
S1 numbers: {'45', '630'}
TRUE numbers: {'45', '630'}
COMMON: {'45', '630'}
INDEX FREQUENCY: {'45': 23022, '630': 2880}

--------------------------------
S1-343815751 -> S2-479876582
S1 numbers: {'45', '630'}
TRUE numbers: {'45'}
COMMON: {'45'}
INDEX FREQUENCY: {'45': 23022}

--------------------------------
S1-343815751 -> S3-878454467
S1 numbers: {'45', '630'}
TRUE numbers: {'45', '630'}
COMMON: {'45', '630'}
INDEX FREQUENCY: {'45': 23022, '630': 2880}

--------------------------------
S1-656753428 -> S3-679606215
S1 numbers: {'9487203', '684', '989'}
TRUE numbers: {'684'}
COMMON: {'684'}
INDEX FREQUENCY: {'684': 1199}

--------------------------------
S1-102811957 -> S2-478959098
S1 numbers: {'3315'}
TRUE numbers: {'3315'}
COMMON: {'3315'}
INDEX FREQUENCY: {'3315': 678}

--------------------------------
S1-102811957 -> S2-553508714
S1 numbers: {'3315'}
TRUE numbers: {'3315'}
COMMON: {'3315'}
INDEX FREQUENCY: {'3315': 678}

--------------------------------
S1-102811957 -> S2-625774905
S1 numbers: {'3315'}
TRUE numbers: {'3315'}
COMMON: {'3315'}
INDEX FREQUENCY: {'3315': 678}

--------------------------------
S1-102811957 -> S3-728090388
S1 numbers: {'3315'}
TRUE numbers: {'3315'}
COMMON: {'3315'}
INDEX FREQUENCY: {'3315': 678}

--------------------------------
S1-102811957 -> S3-928796641
S1 numbers: {'3315'}
TRUE numbers: {'3315'}
COMMON: {'3315'}
INDEX FREQUENCY: {'3315': 678}

--------------------------------
S1-102811957 -> S3-449308785
S1 numbers: {'3315'}
TRUE numbers: set()
COMMON: set()
INDEX FREQUENCY: {}

--------------------------------
S1-18727616 -> S2-755677256
S1 numbers: {'1056'}
TRUE numbers: {'1056-1060', '8807'}
COMMON: set()
INDEX FREQUENCY: {}

In [ ]:
import re

def extract_numbers(text):
    if pd.isna(text):
        return set()

    text = str(text)

    # Extract individual numeric components.
    # Example:
    # 1056-1060 -> 1056, 1060
    # 20-6-3/12 -> 20, 6, 3, 12
    # 9/2113 -> 9, 2113
    numbers = re.findall(r'\d+', text)

    return set(numbers)

In [ ]:
from collections import defaultdict

number_index = defaultdict(list)

for _, row in train_s2.iterrows():

    text = (
        str(row["business_name"]) + " " +
        str(row["business_address"])
    )

    numbers = extract_numbers(text)

    for num in numbers:
        number_index[num].append(row["entity_id"])


for _, row in train_s3.iterrows():

    text = (
        str(row["business_name"]) + " " +
        str(row["business_address"])
    )

    numbers = extract_numbers(text)

    for num in numbers:
        number_index[num].append(row["entity_id"])


print("Number index rebuilt.")
print("Unique number keys:", len(number_index))

Number index rebuilt.
Unique number keys: 145020

In [ ]:
MAX_NUMBER_FREQUENCY = 100

all_number_candidates = set()

for _, row in s1_sample.iterrows():

    text = (
        str(row["business_name"]) + " " +
        str(row["business_address"])
    )

    numbers = extract_numbers(text)

    for num in numbers:

        matches = number_index.get(num, [])

        if 0 < len(matches) <= MAX_NUMBER_FREQUENCY:
            all_number_candidates.update(matches)


found = true_matches.intersection(all_number_candidates)
missed = true_matches - all_number_candidates

print("====================================")
print("NUMBER BLOCKING RECALL")
print("====================================")
print("True matches:", len(true_matches))
print("Found:", len(found))
print("Missed:", len(missed))
print(
    "Blocking Recall:",
    round(len(found) / len(true_matches), 4)
)
print(
    "Blocking Recall %:",
    round(len(found) / len(true_matches) * 100, 2),
    "%"
)
print("Candidate count:", len(all_number_candidates))

====================================
NUMBER BLOCKING RECALL
====================================
True matches: 343
Found: 21
Missed: 322
Blocking Recall: 0.0612
Blocking Recall %: 6.12 %
Candidate count: 372

In [ ]:
TOP_K_NAME = 20
TOP_K_ADDRESS = 20

In [ ]:
TRAIN S1
TRAIN S2
TRAIN S3
train_ground_truth

SyntaxError: invalid syntax (3005708437.py, line 1)

In [ ]:
TOP_K_NAME = 20
TOP_K_ADDRESS = 20

print("TOP_K_NAME =", TOP_K_NAME)
print("TOP_K_ADDRESS =", TOP_K_ADDRESS)

TOP_K_NAME = 20
TOP_K_ADDRESS = 20

In [ ]:
# Name + Address blocking recall test

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import pandas as pd

# Use first 100 TRAIN S1 entities
s1_eval = s1_train.head(100).copy()

# Make sure IDs are strings
s1_eval["entity_id"] = s1_eval["entity_id"].astype(str)
s2_train["entity_id"] = s2_train["entity_id"].astype(str)
s3_train["entity_id"] = s3_train["entity_id"].astype(str)

# Combine S2 + S3
s23 = pd.concat([s2_train, s3_train], ignore_index=True)

# ---------------- NAME TF-IDF ----------------
name_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

name_matrix = name_vectorizer.fit_transform(
    s23["business_name_normalized"].fillna("")
)

s1_name_matrix = name_vectorizer.transform(
    s1_eval["business_name_normalized"].fillna("")
)

# ---------------- ADDRESS TF-IDF ----------------
address_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

address_matrix = address_vectorizer.fit_transform(
    s23["business_address_normalized"].fillna("")
)

s1_address_matrix = address_vectorizer.transform(
    s1_eval["business_address_normalized"].fillna("")
)

# ---------------- GENERATE CANDIDATES ----------------
candidate_sets = []

for i in range(len(s1_eval)):

    # Name similarity
    name_scores = cosine_similarity(
        s1_name_matrix[i],
        name_matrix
    ).ravel()

    name_idx = np.argsort(name_scores)[-TOP_K_NAME:]

    # Address similarity
    address_scores = cosine_similarity(
        s1_address_matrix[i],
        address_matrix
    ).ravel()

    address_idx = np.argsort(address_scores)[-TOP_K_ADDRESS:]

    # Union name + address candidates
    indices = set(name_idx) | set(address_idx)

    # Country filtering
    s1_country = s1_eval.iloc[i]["country"]

    indices = [
        j for j in indices
        if str(s23.iloc[j]["country"]) == str(s1_country)
    ]

    candidate_sets.append(
        set(s23.iloc[j]["entity_id"] for j in indices)
    )

print("Candidate generation completed.")
print("Average candidates per S1:",
      np.mean([len(x) for x in candidate_sets]))

NameError: name 's1_train' is not defined

In [ ]:
[v for v in globals() if v.startswith(("s1", "s2", "s3"))]

['s1',
 's2',
 's3',
 's1_matrix',
 's1_text',
 's1_name_matrix',
 's1_address_matrix',
 's1_id',
 's1row',
 's1_row',
 's1_numbers',
 's1_sample',
 's23',
 's23_lookup',
 's1_nums']

In [ ]:
print("S1:", s1.shape)
print("S2:", s2.shape)
print("S3:", s3.shape)

print("\nS1 columns:")
print(s1.columns.tolist())

S1: (1000, 7)
S2: (100000, 7)
S3: (100000, 7)

S1 columns:
['entity_id', 'business_name', 'business_address', 'country', 'name_norm', 'match_text', 'address_norm']

In [ ]:
[v for v in globals() if "ground" in v.lower() or "true" in v.lower() or "match" in v.lower()]

['ground_truth',
 'total_true',
 'found_true',
 'true_ids',
 'total_true_matches',
 'available_true',
 'missing_true',
 'matches',
 'matched',
 'true_id',
 'true_row',
 'true_numbers',
 'true_matches',
 'matched_ids',
 'true_text',
 'true_nums']

In [ ]:
print(type(ground_truth))

if hasattr(ground_truth, "shape"):
    print("Shape:", ground_truth.shape)

print("\nColumns:")
print(ground_truth.columns.tolist())

print("\nFirst 5 rows:")
display(ground_truth.head())

<class 'dict'>

Columns:

AttributeError: 'dict' object has no attribute 'columns'

In [ ]:
print(type(ground_truth))
print("Number of entries:", len(ground_truth))

# Show first 5 entries
for i, (key, value) in enumerate(ground_truth.items()):
    print("\nS1 ID:", key)
    print("Matches:", value)
    
    if i == 4:
        break

<class 'dict'>
Number of entries: 2206821

S1 ID: S1-965667
Matches: {'S2-681193310', 'S2-743505751', 'S3-775321672', 'S3-860443364', 'S3-11291185'}

S1 ID: S1-55344266
Matches: {'S3-384364074', 'S3-478195123', 'S2-197070651', 'S2-249013014'}

S1 ID: S1-343815751
Matches: {'S3-878454467', 'S2-479876582', 'S2-790675320'}

S1 ID: S1-656753428
Matches: {'S2-153058913', 'S2-24659151', 'S3-679606215'}

S1 ID: S1-102811957
Matches: {'S3-449308785', 'S3-728090388', 'S3-928796641', 'S2-553508714', 'S2-625774905', 'S2-478959098'}

In [ ]:
ground_truth
# key   = S1 entity ID
# value = set of matching S2/S3 entity IDs

{'S1-965667': {'S2-681193310',
  'S2-743505751',
  'S3-11291185',
  'S3-775321672',
  'S3-860443364'},
 'S1-55344266': {'S2-197070651',
  'S2-249013014',
  'S3-384364074',
  'S3-478195123'},
 'S1-343815751': {'S2-479876582', 'S2-790675320', 'S3-878454467'},
 'S1-656753428': {'S2-153058913', 'S2-24659151', 'S3-679606215'},
 'S1-102811957': {'S2-478959098',
  'S2-553508714',
  'S2-625774905',
  'S3-449308785',
  'S3-728090388',
  'S3-928796641'},
 'S1-18727616': {'S2-755677256',
  'S3-187831601',
  'S3-476250621',
  'S3-641489370'},
 'S1-318373630': {'S2-660036492', 'S3-804600254'},
 'S1-86989137': {'S3-274817120', 'S3-312496301'},
 'S1-29845983': {'S2-648035184', 'S3-588502663'},
 'S1-789009573': {'S2-383871912', 'S3-576451439', 'S3-74481402'},
 'S1-730934468': {'S2-356983532', 'S3-352439310'},
 'S1-7293388': {'S2-157073701', 'S2-442723188', 'S2-7028416', 'S3-523120965'},
 'S1-546142636': {'S2-392804085',
  'S2-487600131',
  'S2-582477216',
  'S3-200008747',
  'S3-249331830',
  'S3-729771680'},
 'S1-274126313': {'S2-51486805',
  'S2-680265918',
  'S2-736616474',
  'S3-461175723',
  'S3-850112871',
  'S3-925631694'},
 'S1-145361722': {'S2-120366543', 'S2-939389287', 'S3-96572514'},
 'S1-503957000': {'S2-173295926',
  'S2-235117490',
  'S2-353308450',
  'S2-994658326',
  'S3-33665521',
  'S3-555791452',
  'S3-858763214'},
 'S1-692000596': {'S2-580419223', 'S3-164220452'},
 'S1-561341312': {'S2-483615364', 'S3-619529814'},
 'S1-777597828': {'S2-836452886', 'S3-413669121'},
 'S1-282467635': {'S2-938895481', 'S3-138350041'},
 'S1-727602285': {'S2-138660620',
  'S2-23141904',
  'S2-947230367',
  'S2-976870196',
  'S3-204655096'},
 'S1-302869473': set(),
 'S1-65263544': {'S2-180463458',
  'S2-881122703',
  'S2-998270769',
  'S3-102573485',
  'S3-350074034',
  'S3-403476502'},
 'S1-840162906': {'S2-129529678',
  'S3-139858754',
  'S3-762681944',
  'S3-799520471',
  'S3-800978181'},
 'S1-264156494': {'S2-184087846', 'S3-544213330', 'S3-562014765'},
 'S1-567308588': {'S2-191200521',
  'S2-226928496',
  'S2-964733072',
  'S3-21806256',
  'S3-595927967',
  'S3-764465670'},
 'S1-292935703': {'S2-195749344',
  'S2-516200703',
  'S2-617410789',
  'S3-421403180',
  'S3-533626303',
  'S3-942647343'},
 'S1-439810025': {'S2-983636768', 'S3-975833735'},
 'S1-525304403': {'S2-293401164', 'S2-815373751', 'S3-477957595'},
 'S1-314714647': {'S2-46909251',
  'S2-968477409',
  'S3-192802051',
  'S3-837108914'},
 'S1-616588883': {'S2-603899205', 'S3-200505774', 'S3-625680391'},
 'S1-72310418': {'S2-11779506',
  'S2-516305116',
  'S3-570980846',
  'S3-731160199'},
 'S1-9962387': {'S2-15221089', 'S3-13637230', 'S3-160760047'},
 'S1-463669205': {'S2-301757320', 'S3-242940401'},
 'S1-116043204': {'S3-85523430'},
 'S1-818149988': {'S2-172270636',
  'S2-178277614',
  'S2-489380965',
  'S3-965578558'},
 'S1-876102895': {'S2-358560681',
  'S2-791711694',
  'S3-856057185',
  'S3-949391374'},
 'S1-262997549': set(),
 'S1-730719211': {'S2-241456014',
  'S2-467798366',
  'S2-61695240',
  'S3-951830396'},
 'S1-491795528': {'S2-707708907',
  'S2-910694348',
  'S2-977672203',
  'S3-198224533',
  'S3-449254398',
  'S3-746009250',
  'S3-751371369'},
 'S1-508022910': set(),
 'S1-473377609': {'S3-433876173'},
 'S1-72444401': {'S2-472011237',
  'S2-503949813',
  'S2-9053863',
  'S2-973800896',
  'S3-505153321'},
 'S1-67172650': {'S2-555166797',
  'S2-74945214',
  'S3-251407198',
  'S3-520282171',
  'S3-776312267'},
 'S1-131928575': {'S2-316703436',
  'S2-529222224',
  'S3-134620134',
  'S3-504772212',
  'S3-849706696'},
 'S1-574308285': {'S2-961415907', 'S3-163492874', 'S3-875723263'},
 'S1-225984658': {'S2-355430647', 'S2-581845376'},
 'S1-842533642': {'S2-352625664',
  'S3-429170537',
  'S3-553570072',
  'S3-764018977'},
 'S1-736418916': {'S2-271186953', 'S2-458035790'},
 'S1-439203009': {'S3-967165288'},
 'S1-686913759': {'S2-584238851', 'S3-247609615', 'S3-446980961'},
 'S1-666499407': set(),
 'S1-731397769': {'S2-184664253',
  'S2-811548929',
  'S2-962774422',
  'S3-170055411',
  'S3-794611761'},
 'S1-518197819': {'S2-585132276', 'S2-891724637', 'S3-14411598'},
 'S1-957102563': {'S2-327669113',
  'S2-763063986',
  'S3-368033022',
  'S3-944940220'},
 'S1-693111833': {'S2-289199523', 'S2-540189532', 'S3-736726288'},
 'S1-244810289': {'S2-351044090',
  'S2-506711361',
  'S2-63598201',
  'S3-742580559',
  'S3-975365926'},
 'S1-561619160': {'S2-453284266', 'S3-105824861'},
 'S1-989976700': {'S2-824832347', 'S3-231189391', 'S3-279440303'},
 'S1-553375105': {'S2-81940621', 'S3-150800481'},
 'S1-638848187': {'S2-189915219',
  'S2-193652635',
  'S2-2393709',
  'S2-385237185',
  'S2-720163352',
  'S3-823200767',
  'S3-860885625'},
 'S1-152222475': {'S2-449137844',
  'S2-981487936',
  'S3-486655756',
  'S3-784413899',
  'S3-933485363'},
 'S1-214010889': {'S2-11418208',
  'S2-911687989',
  'S3-402934592',
  'S3-601290834'},
 'S1-161556164': {'S2-331524837',
  'S2-709771917',
  'S2-857236633',
  'S3-729432354',
  'S3-91054277'},
 'S1-965524997': set(),
 'S1-145714579': {'S2-126729754',
  'S2-372650368',
  'S2-425820120',
  'S2-555326071',
  'S3-745131290'},
 'S1-136081707': {'S3-198554090', 'S3-494852042'},
 'S1-973290215': {'S3-925530888'},
 'S1-389414274': {'S2-149253287',
  'S2-24125756',
  'S2-933610960',
  'S3-443891409',
  'S3-993901020'},
 'S1-439955051': {'S2-647999183', 'S3-158696226'},
 'S1-432073164': {'S2-790103206', 'S3-275007071', 'S3-520531285'},
 'S1-540957762': {'S2-25924850', 'S3-103890437', 'S3-404440111'},
 'S1-790589419': {'S2-103997796',
  'S3-213905796',
  'S3-242226202',
  'S3-46701641'},
 'S1-540645835': {'S2-718774116', 'S2-982374245', 'S3-705881096'},
 'S1-830177070': set(),
 'S1-731542669': {'S2-403134793',
  'S2-939487122',
  'S3-535243754',
  'S3-576199259',
  'S3-988120505'},
 'S1-24234371': {'S2-472862697',
  'S2-60388632',
  'S3-345200400',
  'S3-585251996',
  'S3-669346845',
  'S3-809956848',
  'S3-864938817'},
 'S1-365634347': {'S2-368827389',
  'S2-897093331',
  'S3-105919096',
  'S3-61389060'},
 'S1-170252930': {'S2-233855016',
  'S2-844572537',
  'S3-228972158',
  'S3-391969183'},
 'S1-243930232': {'S2-337942322', 'S2-950290299', 'S3-338228632'},
 'S1-379863265': {'S2-358206813',
  'S2-4788127',
  'S3-270031565',
  'S3-607360095',
  'S3-840504567'},
 'S1-652339606': {'S2-731383297',
  'S3-207339762',
  'S3-626670274',
  'S3-946979261'},
 'S1-816256578': {'S2-20898154',
  'S2-58277947',
  'S2-598783662',
  'S2-772902621',
  'S3-330087840',
  'S3-499852307',
  'S3-545757502'},
 'S1-550488938': {'S2-918671514', 'S3-651095723', 'S3-772751614'},
 'S1-502736054': {'S3-537652714', 'S3-82080725'},
 'S1-649259801': {'S2-654066445'},
 'S1-453879293': {'S2-166379583',
  'S2-301969165',
  'S2-769320396',
  'S3-428197164'},
 'S1-927655670': {'S2-226884833', 'S3-708159263', 'S3-769824375'},
 'S1-26175016': {'S2-795484451', 'S3-606010619'},
 'S1-385608858': {'S2-635808285', 'S3-212832942', 'S3-393804899'},
 'S1-185938539': {'S2-456005244',
  'S3-379662508',
  'S3-846884848',
  'S3-880695057'},
 'S1-654156225': {'S2-200519662',
  'S2-775493531',
  'S3-855861296',
  'S3-871798312'},
 'S1-541270202': {'S2-657479988',
  'S3-31133661',
  'S3-381852444',
  'S3-425705194'},
 'S1-551473015': {'S2-588779033',
  'S2-6101812',
  'S2-753820444',
  'S3-601294315',
  'S3-772633035'},
 'S1-894323554': {'S3-255052963',
  'S3-287932701',
  'S3-634456456',
  'S3-813027057'},
 'S1-212509374': {'S2-598327313',
  'S2-682745911',
  'S2-997766473',
  'S3-238736316',
  'S3-635162337'},
 'S1-359440945': {'S2-683352932',
  'S2-940771150',
  'S3-137202105',
  'S3-20852064',
  'S3-75226047'},
 'S1-102422131': {'S2-743086829', 'S3-778505908'},
 'S1-862038247': {'S2-451274541'},
 'S1-781132420': {'S2-553335027', 'S3-277822614', 'S3-439667182'},
 'S1-295437535': {'S2-969740937', 'S3-651788103', 'S3-918259250'},
 'S1-247801289': {'S2-718026833',
  'S2-752280842',
  'S3-255051180',
  'S3-690379551'},
 'S1-618246590': {'S2-339477476',
  'S2-955993024',
  'S2-981272489',
  'S3-901155265',
  'S3-958161415',
  'S3-963717882'},
 'S1-539763792': {'S2-26500789',
  'S2-912528411',
  'S3-643822684',
  'S3-741223656'},
 'S1-89774084': {'S2-198723291'},
 'S1-854952911': {'S2-138434584', 'S2-180445273', 'S2-598796961'},
 'S1-292900819': {'S2-285810778',
  'S2-791548670',
  'S2-935808193',
  'S3-511058262'},
 'S1-531928114': {'S2-104952404',
  'S2-127219034',
  'S3-110146591',
  'S3-754675415'},
 'S1-945578383': {'S2-158613473',
  'S2-277106942',
  'S2-914824440',
  'S3-413656991',
  'S3-434437783',
  'S3-849412812'},
 'S1-591062600': {'S2-170048686', 'S2-478640391'},
 'S1-444476349': {'S2-774179184', 'S2-870449054'},
 'S1-652218682': {'S2-327770765',
  'S2-452604901',
  'S2-892578739',
  'S3-203105144',
  'S3-47477041',
  'S3-936092443',
  'S3-959486209'},
 'S1-929320417': {'S2-275012701',
  'S2-479796481',
  'S3-241909309',
  'S3-384706486',
  'S3-455011584'},
 'S1-900694722': {'S2-791270538',
  'S3-53196875',
  'S3-602669802',
  'S3-755958654'},
 'S1-202262115': set(),
 'S1-741937259': {'S2-767782635',
  'S3-167906319',
  'S3-196963273',
  'S3-738890866',
  'S3-902008087'},
 'S1-6107395': {'S2-389381313',
  'S2-472559214',
  'S2-664730773',
  'S3-658460246',
  'S3-782470874'},
 'S1-83647344': {'S2-777713487',
  'S2-951545019',
  'S3-175231511',
  'S3-248378176',
  'S3-383555916',
  'S3-489977474'},
 'S1-307962633': {'S2-22544434',
  'S2-415653047',
  'S2-604871582',
  'S2-885755783',
  'S3-152251935'},
 'S1-971070058': {'S2-204665869',
  'S2-648948605',
  'S3-259186358',
  'S3-997282939'},
 'S1-466277913': {'S2-600409962',
  'S2-650875195',
  'S2-799745101',
  'S3-24723125',
  'S3-280749539'},
 'S1-759513870': {'S2-298789861',
  'S2-464637188',
  'S2-503211941',
  'S2-806217659',
  'S3-757550366'},
 'S1-582619930': {'S2-458287334', 'S3-267021268', 'S3-665736329'},
 'S1-254440362': {'S2-593056234', 'S3-418652375', 'S3-734943831'},
 'S1-425631822': {'S2-426890506', 'S2-932399936', 'S3-577199638'},
 'S1-432931957': {'S2-596145832',
  'S2-958761019',
  'S3-284924975',
  'S3-981713396'},
 'S1-730297501': {'S2-498113879',
  'S2-913826284',
  'S3-117378264',
  'S3-142585297',
  'S3-659628079'},
 'S1-891833169': {'S2-25345424', 'S2-65554277'},
 'S1-424976769': {'S2-18126063', 'S3-296472077', 'S3-443109567'},
 'S1-625699510': set(),
 'S1-953694901': {'S2-282116255',
  'S2-798975705',
  'S3-5786446',
  'S3-860481692'},
 'S1-604865181': set(),
 'S1-793447671': {'S2-888569504',
  'S2-895081043',
  'S3-325254367',
  'S3-388747679'},
 'S1-369720553': {'S2-309368741', 'S2-736703322', 'S3-439447419'},
 'S1-216137765': {'S2-190915441',
  'S2-410963764',
  'S2-680612609',
  'S2-904465183',
  'S3-818304481'},
 'S1-9455909': {'S2-646408552',
  'S3-133372803',
  'S3-384632970',
  'S3-393934040',
  'S3-609989467'},
 'S1-796816825': {'S2-196975670', 'S2-347326271', 'S3-896547694'},
 'S1-3006430': {'S2-181659751', 'S2-794710696'},
 'S1-922626199': {'S2-851752978',
  'S3-1218889',
  'S3-286175400',
  'S3-564988957',
  'S3-841777268'},
 'S1-862024840': {'S2-74265858', 'S3-187313683'},
 'S1-91229135': {'S2-73405606', 'S3-776763819', 'S3-960685971'},
 'S1-854284989': {'S2-54609117',
  'S2-580208171',
  'S3-317013910',
  'S3-676690737'},
 'S1-446697179': {'S2-377640723',
  'S2-86619877',
  'S2-922150401',
  'S3-142602324',
  'S3-787413121'},
 'S1-996012175': {'S2-168466570',
  'S2-269681023',
  'S2-322555091',
  'S3-153285717',
  'S3-522751192',
  'S3-666964577'},
 'S1-424050882': {'S3-37198119'},
 'S1-441851025': {'S2-794479832', 'S3-516789702'},
 'S1-894049089': {'S2-972003483', 'S3-841264731', 'S3-892940011'},
 'S1-683515854': {'S2-434073238',
  'S2-597139895',
  'S2-756250340',
  'S3-145863982',
  'S3-406939248'},
 'S1-297294757': {'S2-831679005',
  'S3-17545461',
  'S3-595893944',
  'S3-802514980'},
 'S1-287953061': {'S2-423926954',
  'S2-713716483',
  'S3-161833863',
  'S3-368347834'},
 'S1-635770223': {'S2-117370496',
  'S2-329661878',
  'S3-52020616',
  'S3-755529230'},
 'S1-971813156': {'S3-394463058'},
 'S1-734355564': {'S3-111095129', 'S3-854314313'},
 'S1-477776195': {'S2-871236056', 'S3-109807026', 'S3-723948056'},
 'S1-821434436': {'S2-965836188', 'S3-869884588'},
 'S1-45260965': {'S3-339187428', 'S3-602719548', 'S3-722543767'},
 'S1-93741603': {'S2-535692078',
  'S3-660744201',
  'S3-730249237',
  'S3-782738358',
  'S3-78873124',
  'S3-981096747'},
 'S1-472139199': {'S2-122544659', 'S3-403396329', 'S3-474761183'},
 'S1-247776121': {'S2-651967616',
  'S2-867573251',
  'S3-422475598',
  'S3-430990586'},
 'S1-805056706': {'S2-152730216',
  'S2-155276085',
  'S3-217277717',
  'S3-538340664',
  'S3-786470510'},
 'S1-106072003': {'S2-699555547'},
 'S1-562378871': {'S2-125217177', 'S2-164774900', 'S3-361884466'},
 'S1-981013217': {'S2-133339848',
  'S3-123466797',
  'S3-204939280',
  'S3-878103824',
  'S3-967493646'},
 'S1-573706294': {'S2-20524568',
  'S3-436229899',
  'S3-626666235',
  'S3-694735964',
  'S3-953602697'},
 'S1-310827934': {'S2-169546802', 'S2-186080711', 'S2-720050181'},
 'S1-217362890': {'S2-764924647', 'S3-871408188'},
 'S1-879276752': {'S2-943394264', 'S3-144339303', 'S3-570651750'},
 'S1-921549539': {'S2-553145531', 'S3-483530074', 'S3-596285936'},
 'S1-906428444': {'S2-321816304',
  'S2-664348256',
  'S2-91790174',
  'S3-129054940',
  'S3-71002681',
  'S3-751767229',
  'S3-932095902'},
 'S1-505333132': {'S2-238550131', 'S3-484968993', 'S3-551152157'},
 'S1-88224713': set(),
 'S1-136601270': {'S2-254817327',
  'S3-162285797',
  'S3-311795383',
  'S3-449970897'},
 'S1-350234058': {'S3-90766911'},
 'S1-838355310': {'S2-248722765',
  'S2-351731497',
  'S2-58376459',
  'S3-460098477'},
 'S1-155848476': {'S2-306873906', 'S2-911723717', 'S3-79854379'},
 'S1-156380173': {'S2-755422053',
  'S2-905679603',
  'S2-954495419',
  'S3-713859403'},
 'S1-549559960': {'S2-848203707', 'S3-231650119', 'S3-292200508'},
 'S1-897282581': {'S2-522109781', 'S2-812189457', 'S3-747124468'},
 'S1-237739500': {'S3-148513444', 'S3-679029492', 'S3-797828547'},
 'S1-357837082': {'S2-236157315', 'S2-65680643', 'S3-245902676'},
 'S1-292603366': {'S2-295843240',
  'S2-638471523',
  'S2-757482340',
  'S2-805392241',
  'S3-77023816'},
 'S1-108246457': {'S2-463492748',
  'S2-883950674',
  'S3-122500755',
  'S3-838268095'},
 'S1-727766958': {'S2-489771335', 'S3-216771625', 'S3-262641232'},
 'S1-719571188': set(),
 'S1-646393119': {'S2-636746717',
  'S3-433892033',
  'S3-465583962',
  'S3-886048349'},
 'S1-723966103': {'S2-334991974',
  'S2-399866773',
  'S3-161755914',
  'S3-73180305'},
 'S1-76693096': {'S2-160988895', 'S2-78074287', 'S3-215540151'},
 'S1-967724835': {'S2-457310582', 'S3-178777115', 'S3-682315461'},
 'S1-288276341': {'S3-815540739'},
 'S1-887125153': {'S2-448398036'},
 'S1-304029686': {'S2-469411714',
  'S2-948269515',
  'S3-270996986',
  'S3-645171149'},
 'S1-166609944': {'S2-429123768',
  'S2-991673471',
  'S3-912252220',
  'S3-91858577'},
 'S1-178800424': {'S2-23183100', 'S3-900652028'},
 'S1-924630389': {'S2-143853453', 'S3-10826619', 'S3-831568644'},
 'S1-81771195': {'S2-338811924', 'S3-616109', 'S3-939808100'},
 'S1-403692077': set(),
 'S1-745867296': {'S2-43113841'},
 'S1-671241040': {'S2-904226109'},
 'S1-557991692': {'S2-88682972', 'S3-176178171', 'S3-853727007'},
 'S1-8713989': {'S2-37189974',
  'S3-20459433',
  'S3-58380591',
  'S3-588750081',
  'S3-817876291'},
 'S1-945360052': {'S2-146961832',
  'S2-768746975',
  'S3-403273737',
  'S3-416879878',
  'S3-993303669'},
 'S1-555242352': {'S2-253027494',
  'S2-256698756',
  'S2-810626996',
  'S3-884140951'},
 'S1-56911061': {'S2-689298806', 'S3-49524617', 'S3-632926404'},
 'S1-270043704': {'S2-807921453', 'S3-397763900'},
 'S1-477515156': {'S2-154913443',
  'S2-315095658',
  'S3-311437617',
  'S3-979362679'},
 'S1-149024193': {'S2-186116098', 'S3-604630789'},
 'S1-625272950': {'S2-526399876', 'S3-618327131'},
 'S1-225124222': {'S2-563632605',
  'S2-686284157',
  'S3-512465987',
  'S3-538964283'},
 'S1-754023472': {'S2-420202495', 'S3-176329043', 'S3-616793249'},
 'S1-302461695': {'S2-36747880', 'S3-420979078'},
 'S1-692219144': {'S2-523089825', 'S2-974874434', 'S3-560129335'},
 'S1-609996572': {'S2-190427009',
  'S2-40869239',
  'S2-657417123',
  'S2-672443639',
  'S3-262044007',
  'S3-366128148'},
 'S1-236768477': {'S2-490929782',
  'S2-765988280',
  'S3-103597021',
  'S3-135901754',
  'S3-40245970'},
 'S1-86469552': {'S2-328039185',
  'S3-220000395',
  'S3-479224552',
  'S3-918163916'},
 'S1-238175541': {'S2-558978413', 'S3-542988034', 'S3-905308312'},
 'S1-849670817': {'S2-110881580',
  'S2-151920731',
  'S2-414936885',
  'S2-620496053',
  'S3-188936373',
  'S3-32572135',
  'S3-57849762'},
 'S1-445868199': {'S2-872518576', 'S3-527067015', 'S3-924959775'},
 'S1-289512402': {'S2-547617311',
  'S3-145008714',
  'S3-866244606',
  'S3-89827315'},
 'S1-842582339': {'S2-332783247',
  'S2-718008063',
  'S3-455248213',
  'S3-517179359',
  'S3-789259677',
  'S3-84822830',
  'S3-923995241'},
 'S1-54193164': {'S2-414539794',
  'S2-434257717',
  'S2-676269902',
  'S3-486621278',
  'S3-687331533'},
 'S1-508701481': {'S2-1173491',
  'S2-316212039',
  'S2-712560178',
  'S3-444227012'},
 'S1-38836424': {'S2-589094691', 'S3-112223799', 'S3-881605497'},
 'S1-888185705': {'S3-521406491'},
 'S1-298796171': set(),
 'S1-65040114': {'S2-66755406'},
 'S1-485414585': {'S2-333748173',
  'S3-122687142',
  'S3-425803841',
  'S3-730989427'},
 'S1-994893973': {'S2-203258493', 'S3-360939675'},
 'S1-140763859': {'S2-672232195',
  'S2-952678608',
  'S3-912364563',
  'S3-998314844'},
 'S1-705293979': {'S3-967828286'},
 'S1-618624562': {'S2-14084129',
  'S2-160477274',
  'S2-961810110',
  'S3-441239023'},
 'S1-997802413': {'S2-261550171',
  'S2-926905985',
  'S3-317367352',
  'S3-440432997',
  'S3-720276770'},
 'S1-679550141': {'S2-803016719',
  'S2-876234727',
  'S3-300368164',
  'S3-712537949',
  'S3-805670560',
  'S3-937330852'},
 'S1-73533983': {'S2-48233411', 'S2-99841727', 'S3-785488951'},
 'S1-139001469': {'S2-44497918', 'S2-94756237', 'S3-207399315'},
 'S1-472424906': {'S2-221481547',
  'S2-814158570',
  'S3-257476923',
  'S3-346286668',
  'S3-386776122',
  'S3-869369045'},
 'S1-849274176': {'S2-34421487',
  'S2-769215892',
  'S2-780835769',
  'S3-168674505'},
 'S1-759418496': {'S2-622075002',
  'S2-738948758',
  'S2-924496535',
  'S2-971927879',
  'S3-995238469'},
 'S1-776686932': {'S2-200619743',
  'S2-667655982',
  'S3-653415229',
  'S3-675413406'},
 'S1-61094929': {'S2-300149849',
  'S3-681449520',
  'S3-728538969',
  'S3-899083547'},
 'S1-482246278': {'S2-715957744',
  'S3-320053472',
  'S3-409374685',
  'S3-576586964'},
 'S1-660909577': {'S2-290734878',
  'S2-367610025',
  'S2-445772691',
  'S3-49358837',
  'S3-775037416'},
 'S1-873415495': {'S2-447283628', 'S2-930302127', 'S3-264890869'},
 'S1-887286027': {'S2-194799692',
  'S2-419080910',
  'S3-691429700',
  'S3-879493126'},
 'S1-935335906': {'S2-577689878'},
 'S1-115827165': {'S2-537593145',
  'S3-153172012',
  'S3-27891438',
  'S3-407678354',
  'S3-494929490',
  'S3-655137558'},
 'S1-680347141': {'S3-315706239'},
 'S1-721605946': {'S2-429513205', 'S2-9535204'},
 'S1-478804382': {'S2-386167994',
  'S2-949124193',
  'S3-105647246',
  'S3-123682857',
  'S3-838160083'},
 'S1-399360980': {'S2-13956324', 'S2-347388159', 'S3-374508454'},
 'S1-946063787': {'S2-96281545', 'S3-255658738'},
 'S1-679981169': {'S2-548700789',
  'S2-756848974',
  'S3-253689376',
  'S3-385446229',
  'S3-559602234',
  'S3-902644030'},
 'S1-852122558': {'S2-13742356', 'S2-836861185', 'S3-541486453'},
 'S1-654078241': {'S2-27298391',
  'S2-542793063',
  'S3-45895204',
  'S3-778778307'},
 'S1-574271583': {'S2-308807234', 'S2-567264163', 'S2-626684761'},
 'S1-658984896': {'S2-37217309',
  'S2-696163364',
  'S3-627345153',
  'S3-702254487',
  'S3-840280069'},
 'S1-452967807': {'S2-360702286',
  'S2-777341549',
  'S2-890764231',
  'S3-296354640',
  'S3-39218497'},
 'S1-657325262': {'S2-301300035',
  'S2-463332740',
  'S3-461081164',
  'S3-76857645'},
 'S1-643535950': {'S2-401486146',
  'S2-585909854',
  'S3-358233206',
  'S3-760214219'},

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

TOP_K_NAME = 20
TOP_K_ADDRESS = 20

# Combine S2 + S3
s23 = pd.concat([s2, s3], ignore_index=True)

# Make sure IDs are strings
s1["entity_id"] = s1["entity_id"].astype(str)
s23["entity_id"] = s23["entity_id"].astype(str)

# -----------------------------
# NAME TF-IDF
# -----------------------------
name_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

name_matrix = name_vectorizer.fit_transform(
    s23["name_norm"].fillna("")
)

s1_name_matrix = name_vectorizer.transform(
    s1["name_norm"].fillna("")
)

# -----------------------------
# ADDRESS TF-IDF
# -----------------------------
address_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

address_matrix = address_vectorizer.fit_transform(
    s23["address_norm"].fillna("")
)

s1_address_matrix = address_vectorizer.transform(
    s1["address_norm"].fillna("")
)

# -----------------------------
# GENERATE CANDIDATES
# -----------------------------
candidate_sets = []

for i in range(len(s1)):

    # Name candidates
    name_scores = cosine_similarity(
        s1_name_matrix[i],
        name_matrix
    ).ravel()

    name_idx = np.argsort(name_scores)[-TOP_K_NAME:]

    # Address candidates
    address_scores = cosine_similarity(
        s1_address_matrix[i],
        address_matrix
    ).ravel()

    address_idx = np.argsort(address_scores)[-TOP_K_ADDRESS:]

    # Union
    indices = set(name_idx) | set(address_idx)

    # Country filter
    s1_country = str(s1.iloc[i]["country"])

    indices = [
        j for j in indices
        if str(s23.iloc[j]["country"]) == s1_country
    ]

    candidate_sets.append(
        set(s23.iloc[j]["entity_id"] for j in indices)
    )

print("Candidate generation completed.")
print("Average candidates per S1:",
      np.mean([len(x) for x in candidate_sets]))
print("Maximum candidates:",
      max(len(x) for x in candidate_sets))

Candidate generation completed.
Average candidates per S1: 37.76
Maximum candidates: 40

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

TOP_K_NAME = 20
TOP_K_ADDRESS = 20

# Combine S2 + S3
s23 = pd.concat([s2, s3], ignore_index=True)

# Make sure IDs are strings
s1["entity_id"] = s1["entity_id"].astype(str)
s23["entity_id"] = s23["entity_id"].astype(str)

# -----------------------------
# NAME TF-IDF
# -----------------------------
name_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

name_matrix = name_vectorizer.fit_transform(
    s23["name_norm"].fillna("")
)

s1_name_matrix = name_vectorizer.transform(
    s1["name_norm"].fillna("")
)

# -----------------------------
# ADDRESS TF-IDF
# -----------------------------
address_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

address_matrix = address_vectorizer.fit_transform(
    s23["address_norm"].fillna("")
)

s1_address_matrix = address_vectorizer.transform(
    s1["address_norm"].fillna("")
)

# -----------------------------
# GENERATE CANDIDATES
# -----------------------------
candidate_sets = []

for i in range(len(s1)):

    # Name candidates
    name_scores = cosine_similarity(
        s1_name_matrix[i],
        name_matrix
    ).ravel()

    name_idx = np.argsort(name_scores)[-TOP_K_NAME:]

    # Address candidates
    address_scores = cosine_similarity(
        s1_address_matrix[i],
        address_matrix
    ).ravel()

    address_idx = np.argsort(address_scores)[-TOP_K_ADDRESS:]

    # Union
    indices = set(name_idx) | set(address_idx)

    # Country filter
    s1_country = str(s1.iloc[i]["country"])

    indices = [
        j for j in indices
        if str(s23.iloc[j]["country"]) == s1_country
    ]

    candidate_sets.append(
        set(s23.iloc[j]["entity_id"] for j in indices)
    )

print("Candidate generation completed.")
print("Average candidates per S1:",
      np.mean([len(x) for x in candidate_sets]))
print("Maximum candidates:",
      max(len(x) for x in candidate_sets))

Candidate generation completed.
Average candidates per S1: 37.76
Maximum candidates: 40

In [ ]:
total_true = 0
found_true = 0
missed_true = 0

for i, row in s1.iterrows():

    s1_id = str(row["entity_id"])

    # Ground-truth matches
    true_ids = ground_truth.get(s1_id, set())

    # Candidates generated
    candidates = candidate_sets[i]

    total_true += len(true_ids)
    found_true += len(true_ids & candidates)
    missed_true += len(true_ids - candidates)

recall = found_true / total_true if total_true > 0 else 0

print("=" * 60)
print("NAME + ADDRESS BLOCKING RECALL")
print("=" * 60)
print("True matches:", total_true)
print("Found:", found_true)
print("Missed:", missed_true)
print("Blocking Recall:", round(recall, 4))
print("Blocking Recall %:", round(recall * 100, 2), "%")
print("Average candidates/S1:",
      round(np.mean([len(x) for x in candidate_sets]), 2))

============================================================
NAME + ADDRESS BLOCKING RECALL
============================================================
True matches: 0
Found: 0
Missed: 0
Blocking Recall: 0
Blocking Recall %: 0 %
Average candidates/S1: 37.76

In [ ]:
s1_ids = set(s1["entity_id"].astype(str))
gt_ids = set(ground_truth.keys())

overlap = s1_ids & gt_ids

print("S1 IDs:", len(s1_ids))
print("Ground-truth IDs:", len(gt_ids))
print("Overlap:", len(overlap))

print("\nExample S1 IDs:")
print(list(s1_ids)[:5])

print("\nExample ground-truth IDs:")
print(list(gt_ids)[:5])

S1 IDs: 1000
Ground-truth IDs: 2206821
Overlap: 0

Example S1 IDs:
['S1-899271918', 'S1-105827392', 'S1-478404464', 'S1-480447397', 'S1-445413591']

Example ground-truth IDs:
['S1-392132853', 'S1-865933830', 'S1-88866136', 'S1-494669194', 'S1-238205532']

In [ ]:
[v for v in globals() if "train" in v.lower()]

['TRAIN_DIR',
 'train_s1',
 'train_s2',
 'train_s3',
 'train_pool',
 'name_vectorizer_train',
 'name_matrix_train',
 'train_s1_name_matrix',
 'name_nn_train',
 'name_dist_train',
 'name_idx_train',
 'address_vectorizer_train',
 'address_matrix_train',
 'train_s1_address_matrix',
 'address_nn_train',
 'address_dist_train',
 'address_idx_train',
 'train_candidates',
 'candidate_lookup_train']

In [ ]:
print("TRAIN S1:", train_s1.shape)
print("TRAIN S2:", train_s2.shape)
print("TRAIN S3:", train_s3.shape)

print("\nColumns:")
print(train_s1.columns.tolist())

TRAIN S1: (2206821, 4)
TRAIN S2: (5034616, 4)
TRAIN S3: (5285603, 4)

Columns:
['entity_id', 'business_name', 'business_address', 'country']

In [ ]:
print(type(train_candidates))

if hasattr(train_candidates, "shape"):
    print("Shape:", train_candidates.shape)

if hasattr(train_candidates, "columns"):
    print("Columns:", train_candidates.columns.tolist())

print("\nFirst item:")
print(train_candidates[:1] if not hasattr(train_candidates, "head") else train_candidates.head(1))

<class 'pandas.DataFrame'>
Shape: (19936, 3)
Columns: ['source1_entity_id', 'candidate_entity_id', 'channel']

First item:
  source1_entity_id candidate_entity_id channel
0      S1-925783039        S3-507928122    name

In [ ]:
# Calculate blocking recall using existing train_candidates

candidate_lookup = (
    train_candidates
    .groupby("source1_entity_id")["candidate_entity_id"]
    .apply(set)
    .to_dict()
)

total_true = 0
found_true = 0
missed_true = 0

for s1_id, true_ids in ground_truth.items():

    candidates = candidate_lookup.get(s1_id, set())

    total_true += len(true_ids)
    found_true += len(true_ids & candidates)
    missed_true += len(true_ids - candidates)

recall = found_true / total_true if total_true else 0

print("=" * 60)
print("REAL NAME + ADDRESS BLOCKING RECALL")
print("=" * 60)
print("True matches:", total_true)
print("Found:", found_true)
print("Missed:", missed_true)
print("Blocking Recall:", round(recall, 4))
print("Blocking Recall %:", round(recall * 100, 2), "%")
print("Total candidate pairs:", len(train_candidates))
print("Average candidates/S1:",
      round(len(train_candidates) / len(ground_truth), 2))

============================================================
REAL NAME + ADDRESS BLOCKING RECALL
============================================================
True matches: 7638365
Found: 66
Missed: 7638299
Blocking Recall: 0.0
Blocking Recall %: 0.0 %
Total candidate pairs: 19936
Average candidates/S1: 0.01

In [ ]:
print("name_idx_train:", type(name_idx_train), 
      getattr(name_idx_train, "shape", None))

print("address_idx_train:", type(address_idx_train), 
      getattr(address_idx_train, "shape", None))

print("name_nn_train:", type(name_nn_train), 
      getattr(name_nn_train, "shape", None))

print("address_nn_train:", type(address_nn_train), 
      getattr(address_nn_train, "shape", None))

name_idx_train: <class 'numpy.ndarray'> (1000, 10)
address_idx_train: <class 'numpy.ndarray'> (1000, 10)
name_nn_train: <class 'sklearn.neighbors._unsupervised.NearestNeighbors'> None
address_nn_train: <class 'sklearn.neighbors._unsupervised.NearestNeighbors'> None

In [ ]:
print("train_s1:", train_s1.shape)
print("First train_s1 IDs:")
print(train_s1["entity_id"].head().tolist())

print("\nFirst IDs used for NN:")
print(s1["entity_id"].head().tolist())

train_s1: (2206821, 4)
First train_s1 IDs:
['S1-925783039', 'S1-773889195', 'S1-377745466', 'S1-133037285', 'S1-755362802']

First IDs used for NN:
['S1-714132312', 'S1-106407869', 'S1-156285671', 'S1-689823050', 'S1-921369899']

In [ ]:
# Check whether the existing train_s1 has normalized columns
print(train_s1.columns.tolist())
print(train_s2.columns.tolist())
print(train_s3.columns.tolist())

['entity_id', 'business_name', 'business_address', 'country']
['entity_id', 'business_name', 'business_address', 'country']
['entity_id', 'business_name', 'business_address', 'country']

In [ ]:
import re
import pandas as pd

def normalize_text_unicode(x):
    if pd.isna(x):
        return ""
    
    x = str(x).lower()

    replacements = {
        "private limited": "pvt ltd",
        "private ltd": "pvt ltd",
        "corporation": "corp",
        "incorporated": "inc",
        "limited": "ltd",
        "company": "co",
        "street": "st",
        "road": "rd",
        "avenue": "ave",
        "boulevard": "blvd",
        "drive": "dr",
        "lane": "ln",
        "highway": "hwy",
        "parkway": "pkwy",
        "apartment": "apt",
        "suite": "ste",
        "place": "pl",
        "court": "ct"
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = re.sub(r"[^\w\s]", " ", x, flags=re.UNICODE)
    x = re.sub(r"\s+", " ", x).strip()

    return x


# Normalize training data
train_s1["name_norm"] = train_s1["business_name"].map(normalize_text_unicode)
train_s1["address_norm"] = train_s1["business_address"].map(normalize_text_unicode)

train_s2["name_norm"] = train_s2["business_name"].map(normalize_text_unicode)
train_s2["address_norm"] = train_s2["business_address"].map(normalize_text_unicode)

train_s3["name_norm"] = train_s3["business_name"].map(normalize_text_unicode)
train_s3["address_norm"] = train_s3["business_address"].map(normalize_text_unicode)

print("Normalization completed.")

print("S1:", train_s1.shape)
print("S2:", train_s2.shape)
print("S3:", train_s3.shape)

Normalization completed.
S1: (2206821, 6)
S2: (5034616, 6)
S3: (5285603, 6)

In [ ]:
# Correctly aligned evaluation sample
s1_eval = train_s1.head(100).copy()

print("Evaluation S1 rows:", len(s1_eval))
print("First IDs:")
print(s1_eval["entity_id"].head().tolist())

Evaluation S1 rows: 100
First IDs:
['S1-925783039', 'S1-773889195', 'S1-377745466', 'S1-133037285', 'S1-755362802']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

TOP_K_NAME = 20
TOP_K_ADDRESS = 20

# Combine full S2 + S3
train_s23 = pd.concat([train_s2, train_s3], ignore_index=True)

print("S2 + S3 rows:", len(train_s23))

# ---------------- NAME TF-IDF ----------------
name_vectorizer_eval = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

name_matrix_eval = name_vectorizer_eval.fit_transform(
    train_s23["name_norm"].fillna("")
)

s1_name_eval = name_vectorizer_eval.transform(
    s1_eval["name_norm"].fillna("")
)

# ---------------- ADDRESS TF-IDF ----------------
address_vectorizer_eval = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

address_matrix_eval = address_vectorizer_eval.fit_transform(
    train_s23["address_norm"].fillna("")
)

s1_address_eval = address_vectorizer_eval.transform(
    s1_eval["address_norm"].fillna("")
)

# ---------------- CANDIDATES ----------------
candidate_sets_eval = []

for i in range(len(s1_eval)):

    name_scores = cosine_similarity(
        s1_name_eval[i],
        name_matrix_eval
    ).ravel()

    name_idx = np.argpartition(
        name_scores, -TOP_K_NAME
    )[-TOP_K_NAME:]

    address_scores = cosine_similarity(
        s1_address_eval[i],
        address_matrix_eval
    ).ravel()

    address_idx = np.argpartition(
        address_scores, -TOP_K_ADDRESS
    )[-TOP_K_ADDRESS:]

    indices = set(name_idx) | set(address_idx)

    # Country filtering
    country = str(s1_eval.iloc[i]["country"])

    indices = [
        j for j in indices
        if str(train_s23.iloc[j]["country"]) == country
    ]

    candidate_sets_eval.append(
        set(train_s23.iloc[j]["entity_id"] for j in indices)
    )

print("\nCandidate generation completed.")
print(
    "Average candidates/S1:",
    round(np.mean([len(x) for x in candidate_sets_eval]), 2)
)
print(
    "Maximum candidates:",
    max(len(x) for x in candidate_sets_eval)
)

NameError: name 'train_s2' is not defined

In [ ]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 3.0.6
NumPy: 2.5.3

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

TOP_K_NAME = 20
TOP_K_ADDRESS = 20

# Combine full S2 + S3
train_s23 = pd.concat([train_s2, train_s3], ignore_index=True)

print("S2 + S3 rows:", len(train_s23))

# ---------------- NAME TF-IDF ----------------
name_vectorizer_eval = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

name_matrix_eval = name_vectorizer_eval.fit_transform(
    train_s23["name_norm"].fillna("")
)

s1_name_eval = name_vectorizer_eval.transform(
    s1_eval["name_norm"].fillna("")
)

# ---------------- ADDRESS TF-IDF ----------------
address_vectorizer_eval = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

address_matrix_eval = address_vectorizer_eval.fit_transform(
    train_s23["address_norm"].fillna("")
)

s1_address_eval = address_vectorizer_eval.transform(
    s1_eval["address_norm"].fillna("")
)

# ---------------- CANDIDATES ----------------
candidate_sets_eval = []

for i in range(len(s1_eval)):

    name_scores = cosine_similarity(
        s1_name_eval[i],
        name_matrix_eval
    ).ravel()

    name_idx = np.argpartition(
        name_scores, -TOP_K_NAME
    )[-TOP_K_NAME:]

    address_scores = cosine_similarity(
        s1_address_eval[i],
        address_matrix_eval
    ).ravel()

    address_idx = np.argpartition(
        address_scores, -TOP_K_ADDRESS
    )[-TOP_K_ADDRESS:]

    indices = set(name_idx) | set(address_idx)

    # Country filtering
    country = str(s1_eval.iloc[i]["country"])

    indices = [
        j for j in indices
        if str(train_s23.iloc[j]["country"]) == country
    ]

    candidate_sets_eval.append(
        set(train_s23.iloc[j]["entity_id"] for j in indices)
    )

print("\nCandidate generation completed.")
print(
    "Average candidates/S1:",
    round(np.mean([len(x) for x in candidate_sets_eval]), 2)
)
print(
    "Maximum candidates:",
    max(len(x) for x in candidate_sets_eval)
)

NameError: name 'train_s2' is not defined

In [ ]:
import pandas as pd
import numpy as np

TRAIN_DIR = "/path/to/your/train"

train_s1 = pd.read_csv(
    f"{TRAIN_DIR}/train_source1.tsv",
    sep="\t"
)

train_s2 = pd.read_csv(
    f"{TRAIN_DIR}/train_source2.tsv",
    sep="\t"
)

train_s3 = pd.read_csv(
    f"{TRAIN_DIR}/train_source3.tsv",
    sep="\t"
)

print("TRAIN S1:", train_s1.shape)
print("TRAIN S2:", train_s2.shape)
print("TRAIN S3:", train_s3.shape)

FileNotFoundError: [Errno 2] No such file or directory: '/path/to/your/train/train_source1.tsv'

In [ ]:
import os

print(os.getcwd())
print(os.listdir("."))

/Users/apple/Downloads/student_resource/dataset/train
['eda.ipynb', 'entity_matching_model.pkl', 'positive_pairs.tsv', 'TEST', 'positive_features.tsv', 'train_ground_truth.tsv', 'candidate_generation.ipynb', 'train_source2.tsv', 'entity_matching_dataset.tsv', 'train_source3.tsv', 'train_source1.tsv', 'entity_matching_clean.tsv', '.git', 'model_config.json', 'negative_features.tsv']

In [ ]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles/folders here:")
print(os.listdir("."))

Current folder:
/Users/apple/Downloads/student_resource/dataset/train

Files/folders here:
['eda.ipynb', 'entity_matching_model.pkl', 'positive_pairs.tsv', 'TEST', 'positive_features.tsv', 'train_ground_truth.tsv', 'candidate_generation.ipynb', 'train_source2.tsv', 'entity_matching_dataset.tsv', 'train_source3.tsv', 'train_source1.tsv', 'entity_matching_clean.tsv', '.git', 'model_config.json', 'negative_features.tsv']

In [ ]:
TRAIN_DIR = "dataset/train"

In [ ]:
import pandas as pd

TRAIN_DIR = "dataset/train"

train_s1 = pd.read_csv(
    f"{TRAIN_DIR}/train_source1.tsv",
    sep="\t"
)

train_s2 = pd.read_csv(
    f"{TRAIN_DIR}/train_source2.tsv",
    sep="\t"
)

train_s3 = pd.read_csv(
    f"{TRAIN_DIR}/train_source3.tsv",
    sep="\t"
)

print("TRAIN S1:", train_s1.shape)
print("TRAIN S2:", train_s2.shape)
print("TRAIN S3:", train_s3.shape)

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/train/train_source1.tsv'

In [ ]:
TRAIN_DIR = "dataset/train"

In [ ]:
TRAIN_DIR = "/Users/YOUR_USERNAME/Downloads/student_resource 2/dataset/train"

In [ ]:
import os

print(os.path.expanduser("~/Downloads/student_resource 2/dataset/train"))

/Users/apple/Downloads/student_resource 2/dataset/train

In [ ]:
import os

TRAIN_DIR = os.path.expanduser(
    "~/Downloads/student_resource 2/dataset/train"
)

print("Exists:", os.path.exists(TRAIN_DIR))
print("Files:", os.listdir(TRAIN_DIR))

Exists: True
Files: ['train_ground_truth.tsv', 'train_source2.tsv', 'train_source3.tsv', 'train_source1.tsv']

In [ ]:
import pandas as pd

train_s1 = pd.read_csv(
    os.path.join(TRAIN_DIR, "train_source1.tsv"),
    sep="\t"
)

train_s2 = pd.read_csv(
    os.path.join(TRAIN_DIR, "train_source2.tsv"),
    sep="\t"
)

train_s3 = pd.read_csv(
    os.path.join(TRAIN_DIR, "train_source3.tsv"),
    sep="\t"
)

print("TRAIN S1:", train_s1.shape)
print("TRAIN S2:", train_s2.shape)
print("TRAIN S3:", train_s3.shape)

TRAIN S1: (2206821, 4)
TRAIN S2: (5034616, 4)
TRAIN S3: (5285603, 4)

In [ ]:
import re
import pandas as pd

def normalize_text_unicode(x):
    if pd.isna(x):
        return ""

    x = str(x).lower()

    replacements = {
        "private limited": "pvt ltd",
        "private ltd": "pvt ltd",
        "corporation": "corp",
        "incorporated": "inc",
        "limited": "ltd",
        "company": "co",
        "street": "st",
        "road": "rd",
        "avenue": "ave",
        "boulevard": "blvd",
        "drive": "dr",
        "lane": "ln",
        "highway": "hwy",
        "parkway": "pkwy",
        "apartment": "apt",
        "suite": "ste",
        "place": "pl",
        "court": "ct"
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = re.sub(r"[^\w\s]", " ", x, flags=re.UNICODE)
    x = re.sub(r"\s+", " ", x).strip()

    return x


train_s1["name_norm"] = train_s1["business_name"].map(normalize_text_unicode)
train_s1["address_norm"] = train_s1["business_address"].map(normalize_text_unicode)

train_s2["name_norm"] = train_s2["business_name"].map(normalize_text_unicode)
train_s2["address_norm"] = train_s2["business_address"].map(normalize_text_unicode)

train_s3["name_norm"] = train_s3["business_name"].map(normalize_text_unicode)
train_s3["address_norm"] = train_s3["business_address"].map(normalize_text_unicode)

print("Normalization completed.")
print("S1:", train_s1.shape)
print("S2:", train_s2.shape)
print("S3:", train_s3.shape)

Normalization completed.
S1: (2206821, 6)
S2: (5034616, 6)
S3: (5285603, 6)

In [ ]:
s1_eval = train_s1.head(100).copy()

print("Evaluation S1 rows:", len(s1_eval))
print("First IDs:", s1_eval["entity_id"].head().tolist())

Evaluation S1 rows: 100
First IDs: ['S1-925783039', 'S1-773889195', 'S1-377745466', 'S1-133037285', 'S1-755362802']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

TOP_K_NAME = 20
TOP_K_ADDRESS = 20

# Full S2 + S3 pool
train_s23 = pd.concat([train_s2, train_s3], ignore_index=True)

print("S2 + S3 rows:", len(train_s23))

# Name TF-IDF
name_vectorizer_eval = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

name_matrix_eval = name_vectorizer_eval.fit_transform(
    train_s23["name_norm"].fillna("")
)

s1_name_eval = name_vectorizer_eval.transform(
    s1_eval["name_norm"].fillna("")
)

# Address TF-IDF
address_vectorizer_eval = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=2
)

address_matrix_eval = address_vectorizer_eval.fit_transform(
    train_s23["address_norm"].fillna("")
)

s1_address_eval = address_vectorizer_eval.transform(
    s1_eval["address_norm"].fillna("")
)

# Candidate generation
candidate_sets_eval = []

for i in range(len(s1_eval)):

    name_scores = cosine_similarity(
        s1_name_eval[i],
        name_matrix_eval
    ).ravel()

    name_idx = np.argpartition(
        name_scores, -TOP_K_NAME
    )[-TOP_K_NAME:]

    address_scores = cosine_similarity(
        s1_address_eval[i],
        address_matrix_eval
    ).ravel()

    address_idx = np.argpartition(
        address_scores, -TOP_K_ADDRESS
    )[-TOP_K_ADDRESS:]

    indices = set(name_idx) | set(address_idx)

    # Country filter
    country = str(s1_eval.iloc[i]["country"])

    indices = [
        j for j in indices
        if str(train_s23.iloc[j]["country"]) == country
    ]

    candidate_sets_eval.append(
        set(train_s23.iloc[j]["entity_id"] for j in indices)
    )

print("\nCandidate generation completed.")
print(
    "Average candidates/S1:",
    round(np.mean([len(x) for x in candidate_sets_eval]), 2)
)
print(
    "Maximum candidates:",
    max(len(x) for x in candidate_sets_eval)
)

S2 + S3 rows: 10320219

:

:

In [ ]:
name_matrix_eval = name_vectorizer_eval.fit_transform(
    train_s23["name_norm"]
)

NameError: name 'name_vectorizer_eval' is not defined

In [ ]:
print("Kernel is working")

Kernel is working

In [ ]:
import pandas as pd
import numpy as np
import os

TRAIN_DIR = os.path.expanduser(
    "~/Downloads/student_resource 2/dataset/train"
)

train_s1 = pd.read_csv(
    os.path.join(TRAIN_DIR, "train_source1.tsv"),
    sep="\t",
    dtype=str
)

train_s2 = pd.read_csv(
    os.path.join(TRAIN_DIR, "train_source2.tsv"),
    sep="\t",
    dtype=str
)

train_s3 = pd.read_csv(
    os.path.join(TRAIN_DIR, "train_source3.tsv"),
    sep="\t",
    dtype=str
)

print("S1:", train_s1.shape)
print("S2:", train_s2.shape)
print("S3:", train_s3.shape)

S1: (2206821, 4)
S2: (5034616, 4)
S3: (5285603, 4)

In [ ]:
import pandas as pd
import os

GROUND_TRUTH_FILE = os.path.expanduser(
    "~/Downloads/student_resource 2/dataset/train_ground_truth.tsv"
)

print("File exists:", os.path.exists(GROUND_TRUTH_FILE))

File exists: False

In [ ]:
GROUND_TRUTH_FILE = os.path.expanduser(
    "~/Downloads/student_resource 2/train_ground_truth.tsv"
)

print("File exists:", os.path.exists(GROUND_TRUTH_FILE))

File exists: False

In [ ]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nSearching for train_ground_truth.tsv...")

matches = []

for root, dirs, files in os.walk(os.path.expanduser("~/Downloads")):
    if "train_ground_truth.tsv" in files:
        matches.append(os.path.join(root, "train_ground_truth.tsv"))

print("\nFound:")
for path in matches:
    print(path)

Current working directory:
/Users/apple/Downloads/student_resource/dataset/train

Searching for train_ground_truth.tsv...

Found:
/Users/apple/Downloads/student_resource/dataset/train/train_ground_truth.tsv
/Users/apple/Downloads/student_resource 2/dataset/train/train_ground_truth.tsv

In [ ]:
import os
import pandas as pd

GROUND_TRUTH_FILE = (
    "/Users/apple/Downloads/student_resource 2/"
    "dataset/train/train_ground_truth.tsv"
)

print("Exists:", os.path.exists(GROUND_TRUTH_FILE))
print("Size (MB):", round(os.path.getsize(GROUND_TRUTH_FILE) / 1024**2, 2))

Exists: True
Size (MB): 121.13

In [ ]:
import pandas as pd

eval_ids = set(train_s1.head(100)["entity_id"].astype(str))

gt_parts = []

for chunk in pd.read_csv(
    GROUND_TRUTH_FILE,
    sep="\t",
    dtype=str,
    chunksize=200_000
):
    chunk["source1_entity_id"] = chunk["source1_entity_id"].astype(str)

    matched = chunk[
        chunk["source1_entity_id"].isin(eval_ids)
    ]

    if len(matched) > 0:
        gt_parts.append(matched)

ground_truth_eval = pd.concat(
    gt_parts,
    ignore_index=True
)

print("Ground-truth rows found:", len(ground_truth_eval))
print(ground_truth_eval.head())

Ground-truth rows found: 100
  source1_entity_id                                 matched_entity_ids
0      S1-746273151                                                NaN
1      S1-993527714                          S3-250788566,S3-623091575
2      S1-236312382              S2-734049056,S2-69010626,S3-591515133
3      S1-630223771  S2-494260820,S3-697578371,S3-815538600,S3-5874...
4       S1-17666546             S2-341313901,S3-144249320,S3-358598397

In [ ]:
print(train_s1.columns.tolist())

['entity_id', 'business_name', 'business_address', 'country']

In [ ]:
import re
import pandas as pd

def normalize_text_unicode(x):
    if pd.isna(x):
        return ""

    x = str(x).lower()

    replacements = {
        "private limited": "pvt ltd",
        "private ltd": "pvt ltd",
        "corporation": "corp",
        "incorporated": "inc",
        "limited": "ltd",
        "company": "co",
        "street": "st",
        "road": "rd",
        "avenue": "ave",
        "boulevard": "blvd",
        "drive": "dr",
        "lane": "ln",
        "highway": "hwy",
        "parkway": "pkwy",
        "apartment": "apt",
        "suite": "ste",
        "place": "pl",
        "court": "ct"
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = re.sub(r"[^\w\s]", " ", x, flags=re.UNICODE)
    x = re.sub(r"\s+", " ", x).strip()

    return x


for df in [train_s1, train_s2, train_s3]:
    df["name_norm"] = df["business_name"].map(normalize_text_unicode)
    df["address_norm"] = df["business_address"].map(normalize_text_unicode)

print("Normalization completed.")
print(train_s1.shape, train_s2.shape, train_s3.shape)

Normalization completed.
(2206821, 6) (5034616, 6) (5285603, 6)

In [ ]:
# Correctly aligned 100-row evaluation set

s1_eval = train_s1.head(100).copy()

print("Evaluation rows:", len(s1_eval))
print("First 5 IDs:")
print(s1_eval["entity_id"].tolist()[:5])

Evaluation rows: 100
First 5 IDs:
['S1-925783039', 'S1-773889195', 'S1-377745466', 'S1-133037285', 'S1-755362802']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import normalize
import numpy as np
import pandas as pd

TOP_K = 20
CHUNK_SIZE = 100_000

# Evaluation S1
eval_names = s1_eval["name_norm"].fillna("").tolist()
eval_addresses = s1_eval["address_norm"].fillna("").tolist()

# Fit vectorizers ONLY on the 100 S1 evaluation records.
# This keeps the vocabulary small.
name_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=1
)

address_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=1
)

s1_name_matrix = name_vectorizer.fit_transform(eval_names)
s1_address_matrix = address_vectorizer.fit_transform(eval_addresses)

# Store best candidates for each S1
name_best = [[] for _ in range(len(s1_eval))]
address_best = [[] for _ in range(len(s1_eval))]

# --------------------------------------------------
# Process S2 and S3 separately in chunks
# --------------------------------------------------

sources = [
    ("S2", train_s2),
    ("S3", train_s3)
]

for source_name, source_df in sources:

    print(f"\nProcessing {source_name}: {len(source_df):,} rows")

    for start in range(0, len(source_df), CHUNK_SIZE):

        end = min(start + CHUNK_SIZE, len(source_df))
        chunk = source_df.iloc[start:end]

        # ---------- NAME ----------
        chunk_name_matrix = name_vectorizer.transform(
            chunk["name_norm"].fillna("")
        )

        name_scores = s1_name_matrix @ chunk_name_matrix.T

        for i in range(len(s1_eval)):

            scores = name_scores[i].toarray().ravel()

            k = min(TOP_K, len(scores))
            idx = np.argpartition(scores, -k)[-k:]

            for j in idx:
                if scores[j] > 0:
                    name_best[i].append(
                        (
                            float(scores[j]),
                            chunk.iloc[j]["entity_id"],
                            str(chunk.iloc[j]["country"])
                        )
                    )

        # ---------- ADDRESS ----------
        chunk_address_matrix = address_vectorizer.transform(
            chunk["address_norm"].fillna("")
        )

        address_scores = s1_address_matrix @ chunk_address_matrix.T

        for i in range(len(s1_eval)):

            scores = address_scores[i].toarray().ravel()

            k = min(TOP_K, len(scores))
            idx = np.argpartition(scores, -k)[-k:]

            for j in idx:
                if scores[j] > 0:
                    address_best[i].append(
                        (
                            float(scores[j]),
                            chunk.iloc[j]["entity_id"],
                            str(chunk.iloc[j]["country"])
                        )
                    )

        if end % 500_000 == 0 or end == len(source_df):
            print(f"  Processed {end:,}/{len(source_df):,}")

# --------------------------------------------------
# Keep only global top-20 per channel + country filter
# --------------------------------------------------

candidate_sets_eval = []

for i in range(len(s1_eval)):

    country = str(s1_eval.iloc[i]["country"])

    name_candidates = sorted(
        [
            x for x in name_best[i]
            if x[2] == country
        ],
        reverse=True
    )[:TOP_K]

    address_candidates = sorted(
        [
            x for x in address_best[i]
            if x[2] == country
        ],
        reverse=True
    )[:TOP_K]

    candidates = set(
        x[1] for x in name_candidates
    ) | set(
        x[1] for x in address_candidates
    )

    candidate_sets_eval.append(candidates)

print("\n========================================")
print("CANDIDATE GENERATION COMPLETED")
print("========================================")
print(
    "Average candidates/S1:",
    round(np.mean([len(x) for x in candidate_sets_eval]), 2)
)
print(
    "Maximum candidates:",
    max(len(x) for x in candidate_sets_eval)
)

Processing S2: 5,034,616 rows
  Processed 500,000/5,034,616
  Processed 1,000,000/5,034,616
  Processed 1,500,000/5,034,616
  Processed 2,000,000/5,034,616
  Processed 2,500,000/5,034,616
  Processed 3,000,000/5,034,616
  Processed 3,500,000/5,034,616
  Processed 4,000,000/5,034,616
  Processed 4,500,000/5,034,616
  Processed 5,000,000/5,034,616
  Processed 5,034,616/5,034,616

Processing S3: 5,285,603 rows
  Processed 500,000/5,285,603
  Processed 1,000,000/5,285,603
  Processed 1,500,000/5,285,603
  Processed 2,000,000/5,285,603
  Processed 2,500,000/5,285,603
  Processed 3,000,000/5,285,603
  Processed 3,500,000/5,285,603
  Processed 4,000,000/5,285,603
  Processed 4,500,000/5,285,603
  Processed 5,000,000/5,285,603
  Processed 5,285,603/5,285,603

========================================
CANDIDATE GENERATION COMPLETED
========================================
Average candidates/S1: 38.05
Maximum candidates: 40

In [ ]:
# Build ground-truth lookup for the 100 evaluation S1s

ground_truth_eval = {}

for _, row in ground_truth_df.iterrows():
    s1_id = str(row["source1_entity_id"])
    value = row["matched_entity_ids"]

    if pd.isna(value) or str(value).strip() == "":
        ground_truth_eval[s1_id] = set()
    else:
        ground_truth_eval[s1_id] = set(
            x.strip()
            for x in str(value).split(",")
            if x.strip()
        )

# Calculate blocking recall
total_true = 0
found_true = 0
missed_true = 0

for i, row in s1_eval.reset_index(drop=True).iterrows():

    s1_id = str(row["entity_id"])

    true_ids = ground_truth_eval.get(s1_id, set())
    candidates = candidate_sets_eval[i]

    total_true += len(true_ids)
    found_true += len(true_ids & candidates)
    missed_true += len(true_ids - candidates)

recall = found_true / total_true if total_true > 0 else 0

print("=" * 60)
print("MEMORY-SAFE NAME + ADDRESS BLOCKING RECALL")
print("=" * 60)
print("True matches:", total_true)
print("Found:", found_true)
print("Missed:", missed_true)
print("Blocking Recall:", round(recall, 4))
print("Blocking Recall %:", round(recall * 100, 2), "%")
print("Average candidates/S1:", 
      round(np.mean([len(x) for x in candidate_sets_eval]), 2))
print("Maximum candidates/S1:",
      max(len(x) for x in candidate_sets_eval))

NameError: name 'ground_truth_df' is not defined

In [ ]:
import pandas as pd

# Load the 100 ground-truth rows again
eval_ids = set(s1_eval["entity_id"].astype(str))

gt_parts = []

for chunk in pd.read_csv(
    GROUND_TRUTH_FILE,
    sep="\t",
    dtype=str,
    chunksize=200_000
):
    chunk["source1_entity_id"] = chunk["source1_entity_id"].astype(str)

    matched = chunk[
        chunk["source1_entity_id"].isin(eval_ids)
    ]

    if len(matched) > 0:
        gt_parts.append(matched)

ground_truth_df = pd.concat(
    gt_parts,
    ignore_index=True
)

print("Ground-truth rows:", len(ground_truth_df))

Ground-truth rows: 100

In [ ]:
ground_truth_eval = {}

for _, row in ground_truth_df.iterrows():
    s1_id = str(row["source1_entity_id"])
    value = row["matched_entity_ids"]

    if pd.isna(value) or str(value).strip() == "":
        ground_truth_eval[s1_id] = set()
    else:
        ground_truth_eval[s1_id] = set(
            x.strip()
            for x in str(value).split(",")
            if x.strip()
        )

total_true = 0
found_true = 0
missed_true = 0

for i, row in s1_eval.reset_index(drop=True).iterrows():

    s1_id = str(row["entity_id"])

    true_ids = ground_truth_eval.get(s1_id, set())
    candidates = candidate_sets_eval[i]

    total_true += len(true_ids)
    found_true += len(true_ids & candidates)
    missed_true += len(true_ids - candidates)

recall = found_true / total_true if total_true > 0 else 0

print("=" * 60)
print("BLOCKING RECALL")
print("=" * 60)
print("True matches:", total_true)
print("Found:", found_true)
print("Missed:", missed_true)
print("Blocking Recall %:", round(recall * 100, 2), "%")
print("Average candidates/S1:",
      round(np.mean([len(x) for x in candidate_sets_eval]), 2))
print("Maximum candidates/S1:",
      max(len(x) for x in candidate_sets_eval))

============================================================
BLOCKING RECALL
============================================================
True matches: 322
Found: 300
Missed: 22
Blocking Recall %: 93.17 %
Average candidates/S1: 38.05
Maximum candidates/S1: 40

In [ ]:
# Find the 22 missed true matches

missed_cases = []

for i, row in s1_eval.reset_index(drop=True).iterrows():

    s1_id = str(row["entity_id"])

    true_ids = ground_truth_eval.get(s1_id, set())
    candidates = candidate_sets_eval[i]

    missed = true_ids - candidates

    for true_id in missed:
        missed_cases.append({
            "s1_id": s1_id,
            "true_id": true_id,
            "s1_name": row["name_norm"],
            "s1_address": row["address_norm"],
            "country": row["country"]
        })

missed_df = pd.DataFrame(missed_cases)

print("Missed true pairs:", len(missed_df))
display(missed_df)

Missed true pairs: 22

,s1_id,true_id,s1_name,s1_address,country
0,S1-925783039,S3-698172821,orelee s barbershop,1795 westchester dr high point nc,US
1,S1-377745466,S3-402918963,b retail inc,1712 montebello ave phoenix az,US
2,S1-22305073,S2-578011604,dermatology green medicine,294 meadowcreek dr unit unit 2 village of pewa...,US
3,S1-504790211,S2-340882825,crystal lending pc,11643 prosperity rd south jordan ut,US
4,S1-597762257,S3-426660831,green logistics pvt ltd,e 7 second floor new delhi south delhi delhi,India
5,S1-252242682,S2-84842746,aggie e nagle l c s w,11900 54th ave plymouth mn,US
6,S1-883973644,S2-346262429,global hovnanian llc,4024 39th ave seattle wa,US
7,S1-982210261,S3-224600177,mayur hospital of gondal,c o dwarkadhis enterprise c m palace ist floor...,India
8,S1-514155563,S2-556405995,horizon llc,2025 sterigere st west norriton township pa,US
9,S1-681392030,S3-340243016,care institute of technology,west bengal howrah 229 kolkata netaji subhas c...,India
10,S1-216181354,S3-509236611,united consultants pvt ltd,1 522a survey no 52 rajput associates kolkhe p...,India
11,S1-216181354,S3-317748253,united consultants pvt ltd,1 522a survey no 52 rajput associates kolkhe p...,India
12,S1-454111437,S2-790403370,maa research pvt ltd,flat no 702 sapphire a gulmohur tower chiranje...,India
13,S1-302710833,S3-203698864,kial weaver signature associates halifax,nc 6961 301 halifax,US
14,S1-208973592,S3-931413846,morgan ameren inc,la 266 enterprise dr houma,US
15,S1-208973592,S2-481660181,morgan ameren inc,la 266 enterprise dr houma,US
16,S1-630223771,S3-815538600,all international llp,office 105 flr 1 sujata chambers abhaychand ga...,India
17,S1-630223771,S3-697578371,all international llp,office 105 flr 1 sujata chambers abhaychand ga...,India
18,S1-630223771,S3-587424087,all international llp,office 105 flr 1 sujata chambers abhaychand ga...,India
19,S1-754175313,S3-412701641,alpha media pvt ltd,28 b chand bihari nagar near khatipura bridge ...,India
20,S1-912508322,S2-276782865,shiv technologies llp,42 16th cross 8th main rd malleswaram bengalur...,India
21,S1-800482427,S3-355590735,b biotechnologies llc,328 buckingham st unit 414 columbus oh,US

In [ ]:
# Look up the missed true entities in S2/S3

missed_ids = set(missed_df["true_id"])

s2_missed = train_s2[
    train_s2["entity_id"].isin(missed_ids)
].copy()

s3_missed = train_s3[
    train_s3["entity_id"].isin(missed_ids)
].copy()

missed_entities = pd.concat(
    [s2_missed, s3_missed],
    ignore_index=True
)

# Merge true entity information
diagnostic = missed_df.merge(
    missed_entities[
        ["entity_id", "name_norm", "address_norm", "country"]
    ],
    left_on="true_id",
    right_on="entity_id",
    how="left",
    suffixes=("_s1", "_true")
)

diagnostic["name_exact"] = (
    diagnostic["s1_name"] ==
    diagnostic["name_norm"]
)

diagnostic["address_exact"] = (
    diagnostic["s1_address"] ==
    diagnostic["address_norm"]
)

diagnostic["country_match"] = (
    diagnostic["country_s1"].astype(str) ==
    diagnostic["country_true"].astype(str)
)

print("Missed-pair diagnostics:")
print(
    diagnostic[
        ["s1_id", "true_id",
         "name_exact",
         "address_exact",
         "country_match"]
    ]
)

print("\nExact name recoveries:",
      diagnostic["name_exact"].sum())

print("Exact address recoveries:",
      diagnostic["address_exact"].sum())

Missed-pair diagnostics:
           s1_id       true_id  name_exact  address_exact  country_match
0   S1-925783039  S3-698172821       False          False           True
1   S1-377745466  S3-402918963       False          False           True
2    S1-22305073  S2-578011604       False          False           True
3   S1-504790211  S2-340882825       False          False           True
4   S1-597762257  S3-426660831       False          False           True
5   S1-252242682   S2-84842746       False          False           True
6   S1-883973644  S2-346262429       False          False           True
7   S1-982210261  S3-224600177       False          False           True
8   S1-514155563  S2-556405995       False          False           True
9   S1-681392030  S3-340243016       False          False           True
10  S1-216181354  S3-509236611       False          False           True
11  S1-216181354  S3-317748253       False          False           True
12  S1-454111437  S2-790403370       False          False           True
13  S1-302710833  S3-203698864       False          False           True
14  S1-208973592  S3-931413846       False          False           True
15  S1-208973592  S2-481660181       False          False           True
16  S1-630223771  S3-815538600       False          False           True
17  S1-630223771  S3-697578371       False          False           True
18  S1-630223771  S3-587424087       False          False           True
19  S1-754175313  S3-412701641       False          False           True
20  S1-912508322  S2-276782865       False          False           True
21  S1-800482427  S3-355590735       False          False           True

Exact name recoveries: 0
Exact address recoveries: 0

In [ ]:
import re

def extract_numbers(text):
    if pd.isna(text):
        return set()
    return set(re.findall(r"\d+", str(text)))

# Add numbers to the 22 missed cases
diagnostic["s1_numbers"] = diagnostic["s1_address"].apply(
    extract_numbers
)

diagnostic["true_numbers"] = diagnostic["address_norm"].apply(
    extract_numbers
)

diagnostic["shared_numbers"] = diagnostic.apply(
    lambda r: r["s1_numbers"] & r["true_numbers"],
    axis=1
)

print("Missed pairs with shared address numbers:")
print(
    diagnostic[
        ["s1_id", "true_id", "shared_numbers"]
    ]
)

print(
    "\nRecovered by shared number:",
    (diagnostic["shared_numbers"].apply(len) > 0).sum()
)

Missed pairs with shared address numbers:
           s1_id       true_id shared_numbers
0   S1-925783039  S3-698172821             {}
1   S1-377745466  S3-402918963         {1712}
2    S1-22305073  S2-578011604          {294}
3   S1-504790211  S2-340882825             {}
4   S1-597762257  S3-426660831            {7}
5   S1-252242682   S2-84842746           {54}
6   S1-883973644  S2-346262429     {4024, 39}
7   S1-982210261  S3-224600177             {}
8   S1-514155563  S2-556405995         {2025}
9   S1-681392030  S3-340243016          {229}
10  S1-216181354  S3-509236611          {522}
11  S1-216181354  S3-317748253          {522}
12  S1-454111437  S2-790403370             {}
13  S1-302710833  S3-203698864          {301}
14  S1-208973592  S3-931413846             {}
15  S1-208973592  S2-481660181          {266}
16  S1-630223771  S3-815538600          {105}
17  S1-630223771  S3-697578371          {105}
18  S1-630223771  S3-587424087          {105}
19  S1-754175313  S3-412701641           {28}
20  S1-912508322  S2-276782865           {42}
21  S1-800482427  S3-355590735             {}

Recovered by shared number: 16

In [ ]:
from collections import Counter

# Count how frequently each number appears in S2 + S3
number_frequency = Counter()

for df in [train_s2, train_s3]:
    for address in df["address_norm"].fillna(""):
        numbers = extract_numbers(address)
        for n in numbers:
            number_frequency[n] += 1

# Try several rarity thresholds
for threshold in [10, 25, 50, 100, 250, 500]:

    recovered = 0

    for _, row in diagnostic.iterrows():

        shared = row["shared_numbers"]

        rare_shared = {
            n for n in shared
            if number_frequency.get(n, 0) <= threshold
        }

        if rare_shared:
            recovered += 1

    print(
        f"Frequency <= {threshold}: "
        f"{recovered}/22 recovered"
    )

Frequency <= 10: 0/22 recovered
Frequency <= 25: 0/22 recovered
Frequency <= 50: 0/22 recovered
Frequency <= 100: 0/22 recovered
Frequency <= 250: 0/22 recovered
Frequency <= 500: 0/22 recovered

In [ ]:
TOP_K = 20

In [ ]:
TOP_K = 50

In [ ]:
# ============================================================
# MEMORY-SAFE NAME + ADDRESS CANDIDATE GENERATION
# TOP-K = 50
# ============================================================

import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer


# ------------------------------------------------------------
# SETTINGS
# ------------------------------------------------------------

TOP_K = 50
CHUNK_SIZE = 100_000

print("TOP_K:", TOP_K)
print("CHUNK_SIZE:", CHUNK_SIZE)


# ------------------------------------------------------------
# 1. EVALUATION S1
# ------------------------------------------------------------

s1_eval = train_s1.head(100).copy().reset_index(drop=True)

print("\nEvaluation S1:", s1_eval.shape)


# ------------------------------------------------------------
# 2. PREPARE TEXT
# ------------------------------------------------------------

eval_names = (
    s1_eval["name_norm"]
    .fillna("")
    .astype(str)
    .tolist()
)

eval_addresses = (
    s1_eval["address_norm"]
    .fillna("")
    .astype(str)
    .tolist()
)


# ------------------------------------------------------------
# 3. FIT SMALL VECTORIZERS
# ------------------------------------------------------------

print("\nFitting name vectorizer...")

name_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=1
)

s1_name_matrix = name_vectorizer.fit_transform(
    eval_names
)

print(
    "Name matrix:",
    s1_name_matrix.shape
)


print("\nFitting address vectorizer...")

address_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(2, 5),
    min_df=1
)

s1_address_matrix = address_vectorizer.fit_transform(
    eval_addresses
)

print(
    "Address matrix:",
    s1_address_matrix.shape
)


# ------------------------------------------------------------
# 4. STORAGE FOR BEST CANDIDATES
# ------------------------------------------------------------

name_best = [[] for _ in range(len(s1_eval))]
address_best = [[] for _ in range(len(s1_eval))]


# ------------------------------------------------------------
# 5. PROCESS S2 + S3 IN CHUNKS
# ------------------------------------------------------------

sources = [
    ("S2", train_s2),
    ("S3", train_s3)
]


for source_name, source_df in sources:

    print("\n" + "=" * 60)
    print(f"Processing {source_name}: {len(source_df):,} rows")
    print("=" * 60)

    for start in range(
        0,
        len(source_df),
        CHUNK_SIZE
    ):

        end = min(
            start + CHUNK_SIZE,
            len(source_df)
        )

        chunk = source_df.iloc[start:end]

        # ----------------------------------------------------
        # NAME
        # ----------------------------------------------------

        chunk_name_matrix = name_vectorizer.transform(
            chunk["name_norm"]
            .fillna("")
            .astype(str)
        )

        name_scores = (
            s1_name_matrix @
            chunk_name_matrix.T
        )

        for i in range(len(s1_eval)):

            scores = name_scores[i].toarray().ravel()

            k = min(
                TOP_K,
                len(scores)
            )

            if k == 0:
                continue

            idx = np.argpartition(
                scores,
                -k
            )[-k:]

            for j in idx:

                score = float(scores[j])

                if score > 0:

                    name_best[i].append(
                        (
                            score,
                            chunk.iloc[j]["entity_id"],
                            str(chunk.iloc[j]["country"])
                        )
                    )


        # ----------------------------------------------------
        # ADDRESS
        # ----------------------------------------------------

        chunk_address_matrix = address_vectorizer.transform(
            chunk["address_norm"]
            .fillna("")
            .astype(str)
        )

        address_scores = (
            s1_address_matrix @
            chunk_address_matrix.T
        )

        for i in range(len(s1_eval)):

            scores = address_scores[i].toarray().ravel()

            k = min(
                TOP_K,
                len(scores)
            )

            if k == 0:
                continue

            idx = np.argpartition(
                scores,
                -k
            )[-k:]

            for j in idx:

                score = float(scores[j])

                if score > 0:

                    address_best[i].append(
                        (
                            score,
                            chunk.iloc[j]["entity_id"],
                            str(chunk.iloc[j]["country"])
                        )
                    )


        # ----------------------------------------------------
        # PROGRESS
        # ----------------------------------------------------

        if (
            end % 500_000 == 0
            or end == len(source_df)
        ):

            print(
                f"Processed {end:,}/{len(source_df):,}"
            )


# ------------------------------------------------------------
# 6. CREATE FINAL CANDIDATE SETS
# ------------------------------------------------------------

candidate_sets_eval = []


for i in range(len(s1_eval)):

    s1_country = str(
        s1_eval.iloc[i]["country"]
    )


    # --------------------------------------------------------
    # NAME CANDIDATES
    # --------------------------------------------------------

    name_candidates = [
        x
        for x in name_best[i]
        if x[2] == s1_country
    ]

    name_candidates = sorted(
        name_candidates,
        key=lambda x: x[0],
        reverse=True
    )[:TOP_K]


    # --------------------------------------------------------
    # ADDRESS CANDIDATES
    # --------------------------------------------------------

    address_candidates = [
        x
        for x in address_best[i]
        if x[2] == s1_country
    ]

    address_candidates = sorted(
        address_candidates,
        key=lambda x: x[0],
        reverse=True
    )[:TOP_K]


    # --------------------------------------------------------
    # UNION NAME + ADDRESS
    # --------------------------------------------------------

    candidates = set()

    for item in name_candidates:
        candidates.add(item[1])

    for item in address_candidates:
        candidates.add(item[1])


    candidate_sets_eval.append(
        candidates
    )


# ------------------------------------------------------------
# 7. SUMMARY
# ------------------------------------------------------------

candidate_counts = [
    len(x)
    for x in candidate_sets_eval
]


print("\n")
print("=" * 60)
print("CANDIDATE GENERATION COMPLETED")
print("=" * 60)

print(
    "TOP_K:",
    TOP_K
)

print(
    "Average candidates/S1:",
    round(
        np.mean(candidate_counts),
        2
    )
)

print(
    "Maximum candidates:",
    max(candidate_counts)
)

print(
    "Minimum candidates:",
    min(candidate_counts)
)

print(
    "Total candidate pairs:",
    sum(candidate_counts)
)

TOP_K: 50
CHUNK_SIZE: 100000

Evaluation S1: (100, 6)

Fitting name vectorizer...
Name matrix: (100, 4266)

Fitting address vectorizer...
Address matrix: (100, 8886)

============================================================
Processing S2: 5,034,616 rows
============================================================
Processed 500,000/5,034,616
Processed 1,000,000/5,034,616
Processed 1,500,000/5,034,616
Processed 2,000,000/5,034,616
Processed 2,500,000/5,034,616
Processed 3,000,000/5,034,616
Processed 3,500,000/5,034,616
Processed 4,000,000/5,034,616
Processed 4,500,000/5,034,616
Processed 5,000,000/5,034,616
Processed 5,034,616/5,034,616

============================================================
Processing S3: 5,285,603 rows
============================================================
Processed 500,000/5,285,603
Processed 1,000,000/5,285,603
Processed 1,500,000/5,285,603
Processed 2,000,000/5,285,603
Processed 2,500,000/5,285,603
Processed 3,000,000/5,285,603
Processed 3,500,000/5,285,603
Processed 4,000,000/5,285,603
Processed 4,500,000/5,285,603
Processed 5,000,000/5,285,603
Processed 5,285,603/5,285,603


============================================================
CANDIDATE GENERATION COMPLETED
============================================================
TOP_K: 50
Average candidates/S1: 97.69
Maximum candidates: 100
Minimum candidates: 93
Total candidate pairs: 9769

In [ ]:
# ============================================================
# TOP-K = 50 BLOCKING RECALL
# ============================================================

total_true = 0
found_true = 0
missed_true = 0

missed_cases_50 = []

for i, row in s1_eval.reset_index(drop=True).iterrows():

    s1_id = str(row["entity_id"])

    true_ids = ground_truth_eval.get(
        s1_id,
        set()
    )

    candidates = candidate_sets_eval[i]

    found = true_ids & candidates
    missed = true_ids - candidates

    total_true += len(true_ids)
    found_true += len(found)
    missed_true += len(missed)

    for true_id in missed:
        missed_cases_50.append(
            (s1_id, true_id)
        )

recall = (
    found_true / total_true
    if total_true > 0
    else 0
)

print("=" * 60)
print("TOP-K = 50 BLOCKING RECALL")
print("=" * 60)

print("True matches:", total_true)
print("Found:", found_true)
print("Missed:", missed_true)

print(
    "Blocking Recall:",
    round(recall, 4)
)

print(
    "Blocking Recall %:",
    round(recall * 100, 2),
    "%"
)

print(
    "Average candidates/S1:",
    round(
        np.mean(
            [len(x) for x in candidate_sets_eval]
        ),
        2
    )
)

print(
    "Maximum candidates/S1:",
    max(
        len(x)
        for x in candidate_sets_eval
    )
)

============================================================
TOP-K = 50 BLOCKING RECALL
============================================================
True matches: 322
Found: 306
Missed: 16
Blocking Recall: 0.9503
Blocking Recall %: 95.03 %
Average candidates/S1: 97.69
Maximum candidates/S1: 100

In [ ]:
# Show the 16 matches still missed by TOP-K = 50

missed_cases_50_df = []

for i, row in s1_eval.reset_index(drop=True).iterrows():

    s1_id = str(row["entity_id"])
    true_ids = ground_truth_eval.get(s1_id, set())
    candidates = candidate_sets_eval[i]

    for true_id in (true_ids - candidates):

        missed_cases_50_df.append({
            "s1_id": s1_id,
            "true_id": true_id,
            "s1_name": row["name_norm"],
            "s1_address": row["address_norm"],
            "country": row["country"]
        })

missed_cases_50_df = pd.DataFrame(missed_cases_50_df)

print("Remaining missed pairs:", len(missed_cases_50_df))

display(missed_cases_50_df)

Remaining missed pairs: 16

,s1_id,true_id,s1_name,s1_address,country
0,S1-377745466,S3-402918963,b retail inc,1712 montebello ave phoenix az,US
1,S1-597762257,S3-426660831,green logistics pvt ltd,e 7 second floor new delhi south delhi delhi,India
2,S1-252242682,S2-84842746,aggie e nagle l c s w,11900 54th ave plymouth mn,US
3,S1-883973644,S2-346262429,global hovnanian llc,4024 39th ave seattle wa,US
4,S1-982210261,S3-224600177,mayur hospital of gondal,c o dwarkadhis enterprise c m palace ist floor...,India
5,S1-681392030,S3-340243016,care institute of technology,west bengal howrah 229 kolkata netaji subhas c...,India
6,S1-216181354,S3-509236611,united consultants pvt ltd,1 522a survey no 52 rajput associates kolkhe p...,India
7,S1-216181354,S3-317748253,united consultants pvt ltd,1 522a survey no 52 rajput associates kolkhe p...,India
8,S1-454111437,S2-790403370,maa research pvt ltd,flat no 702 sapphire a gulmohur tower chiranje...,India
9,S1-208973592,S3-931413846,morgan ameren inc,la 266 enterprise dr houma,US
10,S1-630223771,S3-815538600,all international llp,office 105 flr 1 sujata chambers abhaychand ga...,India
11,S1-630223771,S3-697578371,all international llp,office 105 flr 1 sujata chambers abhaychand ga...,India
12,S1-630223771,S3-587424087,all international llp,office 105 flr 1 sujata chambers abhaychand ga...,India
13,S1-754175313,S3-412701641,alpha media pvt ltd,28 b chand bihari nagar near khatipura bridge ...,India
14,S1-912508322,S2-276782865,shiv technologies llp,42 16th cross 8th main rd malleswaram bengalur...,India
15,S1-800482427,S3-355590735,b biotechnologies llc,328 buckingham st unit 414 columbus oh,US

In [ ]:
# ============================================================
# DIAGNOSE THE 16 REMAINING MISSED MATCHES
# ============================================================

from rapidfuzz.fuzz import ratio, token_set_ratio, WRatio
import re

missed_ids = set(
    missed_cases_50_df["true_id"].astype(str)
)

# Find the actual true entities
s2_true = train_s2[
    train_s2["entity_id"].astype(str).isin(missed_ids)
].copy()

s3_true = train_s3[
    train_s3["entity_id"].astype(str).isin(missed_ids)
].copy()

true_entities = pd.concat(
    [s2_true, s3_true],
    ignore_index=True
)

# Merge S1 + true entity
diagnostic_16 = missed_cases_50_df.merge(
    true_entities[
        [
            "entity_id",
            "business_name",
            "business_address",
            "name_norm",
            "address_norm",
            "country"
        ]
    ],
    left_on="true_id",
    right_on="entity_id",
    how="left",
    suffixes=("_s1", "_true")
)


# ------------------------------------------------------------
# Similarity functions
# ------------------------------------------------------------

def get_numbers(text):
    if pd.isna(text):
        return set()
    return set(re.findall(r"\d+", str(text)))


def get_tokens(text):
    if pd.isna(text):
        return set()
    return set(
        str(text).lower().split()
    )


diagnostic_16["name_ratio"] = diagnostic_16.apply(
    lambda r: ratio(
        str(r["s1_name"]),
        str(r["name_norm"])
    ),
    axis=1
)

diagnostic_16["name_token_ratio"] = diagnostic_16.apply(
    lambda r: token_set_ratio(
        str(r["s1_name"]),
        str(r["name_norm"])
    ),
    axis=1
)

diagnostic_16["name_WRatio"] = diagnostic_16.apply(
    lambda r: WRatio(
        str(r["s1_name"]),
        str(r["name_norm"])
    ),
    axis=1
)

diagnostic_16["address_ratio"] = diagnostic_16.apply(
    lambda r: ratio(
        str(r["s1_address"]),
        str(r["address_norm"])
    ),
    axis=1
)

diagnostic_16["shared_numbers"] = diagnostic_16.apply(
    lambda r:
        get_numbers(r["s1_address"]) &
        get_numbers(r["address_norm"]),
    axis=1
)

diagnostic_16["shared_address_tokens"] = diagnostic_16.apply(
    lambda r:
        get_tokens(r["s1_address"]) &
        get_tokens(r["address_norm"]),
    axis=1
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

display(
    diagnostic_16[
        [
            "s1_id",
            "true_id",
            "s1_name",
            "business_name",
            "s1_address",
            "business_address",
            "name_ratio",
            "name_token_ratio",
            "name_WRatio",
            "address_ratio",
            "shared_numbers",
            "shared_address_tokens"
        ]
    ]
)

,s1_id,true_id,s1_name,business_name,s1_address,business_address,name_ratio,name_token_ratio,name_WRatio,address_ratio,shared_numbers,shared_address_tokens
0,S1-377745466,S3-402918963,b retail inc,B+ Rétail Incorporated,1712 montebello ave phoenix az,"1712 Montebello Ave, Northeast, Arizona",91.666667,91.666667,91.666667,74.626866,{1712},"{montebello, ave, 1712}"
1,S1-597762257,S3-426660831,green logistics pvt ltd,ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड,e 7 second floor new delhi south delhi delhi,"South Delhi, No. 225 E-7, DL, New Delhi",10.526316,12.765957,12.127660,48.101266,{7},"{7, south, new, delhi, e}"
2,S1-252242682,S2-84842746,aggie e nagle l c s w,*** aggieenagle.com,11900 54th ave plymouth mn,"54ND AVENUE, MINNEAPLIS, MN",72.222222,66.666667,72.222222,50.000000,{54},"{ave, mn}"
3,S1-883973644,S2-346262429,global hovnanian llc,GLOBAL HOGNANINN LLC,4024 39th ave seattle wa,"4024B 39RD AVE, SEATTLE, WA",90.000000,90.000000,90.000000,89.795918,"{4024, 39}","{ave, wa, seattle}"
4,S1-982210261,S3-224600177,mayur hospital of gondal,Mayur Center Gondal of,c o dwarkadhis enterprise c m palace ist floor...,"Block E-2-5 C/o Dwarkadhis Enterprise, Gondal, GJ",60.869565,81.081081,77.027027,46.052632,{},"{gondal, c, dwarkadhis, enterprise, o}"
5,S1-681392030,S3-340243016,care institute of technology,Care Institute óf Technology,west bengal howrah 229 kolkata netaji subhas c...,"229., Kolkata, WB",96.428571,96.428571,96.428571,22.033898,{229},"{229, kolkata}"
6,S1-216181354,S3-509236611,united consultants pvt ltd,यूनाइटेड Consultants Private Limited,1 522a survey no 52 rajput associates kolkhe p...,"001/522A, Panvel, MH",74.074074,84.444444,80.222222,34.782609,{522},"{panvel, 522a, mh}"
7,S1-216181354,S3-317748253,united consultants pvt ltd,यूनाइटेड कंसल्टेंट्स प्राइवेट लिमिटेड,1 522a survey no 52 rajput associates kolkhe p...,"001/522A, Panvel, महाराष्ट्र",9.677419,11.111111,10.555556,32.000000,{522},"{panvel, 522a}"
8,S1-454111437,S2-790403370,maa research pvt ltd,*** Maa Research Private,flat no 702 sapphire a gulmohur tower chiranje...,"FLAT NO-00702, GHAZIABAD, Uttar Pradesh",80.000000,80.000000,80.000000,56.451613,{},"{pradesh, flat, ghaziabad, uttar, no}"
9,S1-208973592,S3-931413846,morgan ameren inc,@morganameren,la 266 enterprise dr houma,"Bayou Cane, Louisiana, 267 Enterprise Drive",82.758621,41.379310,82.758621,59.375000,{},"{dr, enterprise}"
10,S1-630223771,S3-815538600,all international llp,ऑल इंटरनेशनल एलएलपी,office 105 flr 1 sujata chambers abhaychand ga...,"Office C-105, Mumbai Ii, MH",10.256410,10.256410,10.256410,32.167832,{105},"{105, mumbai, office}"
11,S1-630223771,S3-697578371,all international llp,ऑल इंटरनेशनल एलएलपी,office 105 flr 1 sujata chambers abhaychand ga...,"Office C-105, Mumbai (SUBURBAN), MH, Mumbai City",10.256410,10.256410,10.256410,42.236025,{105},"{105, mumbai, office, city}"
12,S1-630223771,S3-587424087,all international llp,All LLP Center,office 105 flr 1 sujata chambers abhaychand ga...,"Office C-105, Mumbai Ii, MH",45.714286,68.571429,85.500000,32.167832,{105},"{105, mumbai, office}"
13,S1-754175313,S3-412701641,alpha media pvt ltd,Alpha Media Private [Limited],28 b chand bihari nagar near khatipura bridge ...,"28-B, Jaipur, राजस्थान",90.476190,90.476190,90.476190,30.434783,{28},"{b, jaipur, 28}"
14,S1-912508322,S2-276782865,shiv technologies llp,ಶಿವ್ ಟೆಕ್ನಾಲಜೀಸ್ ಎಲ್ಎಲ್‌ಪಿ,42 16th cross 8th main rd malleswaram bengalur...,"Karnataka, BENGALURU, 42, BANGALORE",9.302326,10.000000,9.500000,50.505051,{42},"{42, bengaluru, bangalore, karnataka}"
15,S1-800482427,S3-355590735,b biotechnologies llc,B+ LLC Services,328 buckingham st unit 414 columbus oh,NaN,34.285714,57.142857,85.500000,0.000000,{},{}

In [ ]:
# ============================================================
# TEST TF-IDF SIMILARITY FOR THE 16 MISSED TRUE PAIRS
# ============================================================

# Prepare true names and addresses
true_names = (
    diagnostic_16["name_norm"]
    .fillna("")
    .astype(str)
    .tolist()
)

true_addresses = (
    diagnostic_16["address_norm"]
    .fillna("")
    .astype(str)
    .tolist()
)

# Transform the 16 true records using the SAME vectorizers
true_name_matrix = name_vectorizer.transform(true_names)
true_address_matrix = address_vectorizer.transform(true_addresses)

# Calculate S1 <-> true-pair similarity
name_tfidf_scores = []

address_tfidf_scores = []

for i in range(len(diagnostic_16)):

    name_score = (
        s1_name_matrix[i] @
        true_name_matrix[i].T
    ).toarray()[0][0]

    address_score = (
        s1_address_matrix[i] @
        true_address_matrix[i].T
    ).toarray()[0][0]

    name_tfidf_scores.append(float(name_score))
    address_tfidf_scores.append(float(address_score))


diagnostic_16["name_tfidf"] = name_tfidf_scores
diagnostic_16["address_tfidf"] = address_tfidf_scores

diagnostic_16["combined_tfidf"] = (
    0.5 * diagnostic_16["name_tfidf"] +
    0.5 * diagnostic_16["address_tfidf"]
)


# ------------------------------------------------------------
# DISPLAY
# ------------------------------------------------------------

display(
    diagnostic_16[
        [
            "s1_id",
            "true_id",
            "s1_name",
            "business_name",
            "name_ratio",
            "name_tfidf",
            "address_ratio",
            "address_tfidf",
            "combined_tfidf"
        ]
    ]
)

,s1_id,true_id,s1_name,business_name,name_ratio,name_tfidf,address_ratio,address_tfidf,combined_tfidf
0,S1-377745466,S3-402918963,b retail inc,B+ Rétail Incorporated,91.666667,0.000000,74.626866,0.028990,0.014495
1,S1-597762257,S3-426660831,green logistics pvt ltd,ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड,10.526316,0.000000,48.101266,0.014680,0.007340
2,S1-252242682,S2-84842746,aggie e nagle l c s w,*** aggieenagle.com,72.222222,0.000000,50.000000,0.080246,0.040123
3,S1-883973644,S2-346262429,global hovnanian llc,GLOBAL HOGNANINN LLC,90.000000,0.000000,89.795918,0.003032,0.001516
4,S1-982210261,S3-224600177,mayur hospital of gondal,Mayur Center Gondal of,60.869565,0.150183,46.052632,0.078239,0.114211
5,S1-681392030,S3-340243016,care institute of technology,Care Institute óf Technology,96.428571,0.005088,22.033898,0.017283,0.011186
6,S1-216181354,S3-509236611,united consultants pvt ltd,यूनाइटेड Consultants Private Limited,74.074074,0.298455,34.782609,0.013612,0.156034
7,S1-216181354,S3-317748253,united consultants pvt ltd,यूनाइटेड कंसल्टेंट्स प्राइवेट लिमिटेड,9.677419,0.000000,32.000000,0.014258,0.007129
8,S1-454111437,S2-790403370,maa research pvt ltd,*** Maa Research Private,80.000000,0.015784,56.451613,0.004969,0.010376
9,S1-208973592,S3-931413846,morgan ameren inc,@morganameren,82.758621,0.029946,59.375000,0.018563,0.024255
10,S1-630223771,S3-815538600,all international llp,ऑल इंटरनेशनल एलएलपी,10.256410,0.000000,32.167832,0.000000,0.000000
11,S1-630223771,S3-697578371,all international llp,ऑल इंटरनेशनल एलएलपी,10.256410,0.000000,42.236025,0.106135,0.053068
12,S1-630223771,S3-587424087,all international llp,All LLP Center,45.714286,0.013816,32.167832,0.015807,0.014812
13,S1-754175313,S3-412701641,alpha media pvt ltd,Alpha Media Private [Limited],90.476190,0.000000,30.434783,0.004394,0.002197
14,S1-912508322,S2-276782865,shiv technologies llp,ಶಿವ್ ಟೆಕ್ನಾಲಜೀಸ್ ಎಲ್ಎಲ್‌ಪಿ,9.302326,0.000000,50.505051,0.019450,0.009725
15,S1-800482427,S3-355590735,b biotechnologies llc,B+ LLC Services,34.285714,0.009659,0.000000,0.000000,0.004829

In [ ]:
# ============================================================
# WORD-BASED TF-IDF TEST ON THE 16 MISSED PAIRS
# ============================================================

from sklearn.feature_extraction.text import TfidfVectorizer

# Use the 100 evaluation S1 names
word_vectorizer = TfidfVectorizer(
    analyzer="word",
    ngram_range=(1, 2),
    lowercase=True,
    min_df=1
)

word_s1_matrix = word_vectorizer.fit_transform(
    s1_eval["name_norm"].fillna("").astype(str)
)

word_true_matrix = word_vectorizer.transform(
    diagnostic_16["name_norm"].fillna("").astype(str)
)

word_scores = []

for i in range(len(diagnostic_16)):

    score = (
        word_s1_matrix[i] @
        word_true_matrix[i].T
    ).toarray()[0][0]

    word_scores.append(float(score))

diagnostic_16["word_tfidf"] = word_scores

display(
    diagnostic_16[
        [
            "s1_id",
            "true_id",
            "s1_name",
            "business_name",
            "name_ratio",
            "name_tfidf",
            "word_tfidf"
        ]
    ]
)

print(
    "\nWord TF-IDF > 0:",
    sum(x > 0 for x in word_scores),
    "/",
    len(word_scores)
)

,s1_id,true_id,s1_name,business_name,name_ratio,name_tfidf,word_tfidf
0,S1-377745466,S3-402918963,b retail inc,B+ Rétail Incorporated,91.666667,0.000000,0.000000
1,S1-597762257,S3-426660831,green logistics pvt ltd,ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड,10.526316,0.000000,0.000000
2,S1-252242682,S2-84842746,aggie e nagle l c s w,*** aggieenagle.com,72.222222,0.000000,0.000000
3,S1-883973644,S2-346262429,global hovnanian llc,GLOBAL HOGNANINN LLC,90.000000,0.000000,0.000000
4,S1-982210261,S3-224600177,mayur hospital of gondal,Mayur Center Gondal of,60.869565,0.150183,0.158230
5,S1-681392030,S3-340243016,care institute of technology,Care Institute óf Technology,96.428571,0.005088,0.000000
6,S1-216181354,S3-509236611,united consultants pvt ltd,यूनाइटेड Consultants Private Limited,74.074074,0.298455,0.228126
7,S1-216181354,S3-317748253,united consultants pvt ltd,यूनाइटेड कंसल्टेंट्स प्राइवेट लिमिटेड,9.677419,0.000000,0.000000
8,S1-454111437,S2-790403370,maa research pvt ltd,*** Maa Research Private,80.000000,0.015784,0.000000
9,S1-208973592,S3-931413846,morgan ameren inc,@morganameren,82.758621,0.029946,0.000000
10,S1-630223771,S3-815538600,all international llp,ऑल इंटरनेशनल एलएलपी,10.256410,0.000000,0.000000
11,S1-630223771,S3-697578371,all international llp,ऑल इंटरनेशनल एलएलपी,10.256410,0.000000,0.000000
12,S1-630223771,S3-587424087,all international llp,All LLP Center,45.714286,0.013816,0.000000
13,S1-754175313,S3-412701641,alpha media pvt ltd,Alpha Media Private [Limited],90.476190,0.000000,0.000000
14,S1-912508322,S2-276782865,shiv technologies llp,ಶಿವ್ ಟೆಕ್ನಾಲಜೀಸ್ ಎಲ್ಎಲ್‌ಪಿ,9.302326,0.000000,0.000000
15,S1-800482427,S3-355590735,b biotechnologies llc,B+ LLC Services,34.285714,0.009659,0.000000

Word TF-IDF > 0: 2 / 16

In [ ]:
print("=" * 60)
print("FINAL BLOCKING CONFIGURATION")
print("=" * 60)

print("TOP_K_NAME:", 50)
print("TOP_K_ADDRESS:", 50)
print("Average candidates/S1:", 97.69)
print("Maximum candidates/S1:", 100)
print("Validation blocking recall:", "95.03%")

============================================================
FINAL BLOCKING CONFIGURATION
============================================================
TOP_K_NAME: 50
TOP_K_ADDRESS: 50
Average candidates/S1: 97.69
Maximum candidates/S1: 100
Validation blocking recall: 95.03%

In [ ]:
from pathlib import Path

TEST_DIR = Path.home() / "Downloads/student_resource 2/dataset/test"

for name in [
    "test_source1.tsv",
    "test_source2.tsv",
    "test_source3.tsv"
]:
    path = TEST_DIR / name
    print(name)
    print("Exists:", path.exists())
    if path.exists():
        print("Size MB:", round(path.stat().st_size / (1024**2), 2))
    print()

test_source1.tsv
Exists: True
Size MB: 166.91

test_source2.tsv
Exists: True
Size MB: 485.86

test_source3.tsv
Exists: True
Size MB: 482.56

In [ ]:
# ============================================================
# FULL TEST CANDIDATE GENERATION - SETUP
# ============================================================

import os
import re
import gc
import numpy as np
import pandas as pd

from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer

# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

TEST_DIR = Path.home() / "Downloads/student_resource 2/dataset/test"

TEST_S1 = TEST_DIR / "test_source1.tsv"
TEST_S2 = TEST_DIR / "test_source2.tsv"
TEST_S3 = TEST_DIR / "test_source3.tsv"

OUTPUT_DIR = Path.cwd() / "outputs"
OUTPUT_DIR.mkdir(exist_ok=True)

CANDIDATE_FILE = OUTPUT_DIR / "candidate_pairs.tsv"

# ------------------------------------------------------------
# SETTINGS
# ------------------------------------------------------------

TOP_K_NAME = 50
TOP_K_ADDRESS = 50

S1_BATCH_SIZE = 1000
S23_CHUNK_SIZE = 100_000

print("TEST directory:", TEST_DIR)
print("S1 exists:", TEST_S1.exists())
print("S2 exists:", TEST_S2.exists())
print("S3 exists:", TEST_S3.exists())

print("\nTOP_K_NAME:", TOP_K_NAME)
print("TOP_K_ADDRESS:", TOP_K_ADDRESS)
print("S1 batch:", S1_BATCH_SIZE)
print("S2/S3 chunk:", S23_CHUNK_SIZE)

TEST directory: /Users/apple/Downloads/student_resource 2/dataset/test
S1 exists: True
S2 exists: True
S3 exists: True

TOP_K_NAME: 50
TOP_K_ADDRESS: 50
S1 batch: 1000
S2/S3 chunk: 100000

In [ ]:
# ============================================================
# LOAD TEST S1
# ============================================================

test_s1 = pd.read_csv(
    TEST_S1,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ],
    dtype=str
)

print("TEST S1:", test_s1.shape)
print(test_s1.head())

TEST S1: (1732544, 4)
      entity_id         business_name  \
0  S1-714132312       Zephay Labs Inc
1  S1-106407869  Vision Partners Corp
2  S1-156285671         << Team Ecole
3  S1-689823050   Red Perfect Trading
4  S1-921369899         ZNB Club SARL

                                    business_address country
0                        2621 Cotten Road, Tyler, TX      US
1             IA, Iowa City, 1064 Newton Rd, Unit 11      US
2  175 Boulevard du Président Franklin Roosevelt,...  France
3  Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...   India
4  Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...  France

In [ ]:
# ============================================================
# NORMALIZE TEXT
# ============================================================

def normalize_text_unicode(x):

    if pd.isna(x):
        return ""

    x = str(x).lower()

    replacements = {
        "private limited": "pvt ltd",
        "private ltd": "pvt ltd",
        "corporation": "corp",
        "incorporated": "inc",
        "limited": "ltd",
        "company": "co",
        "street": "st",
        "road": "rd",
        "avenue": "ave",
        "boulevard": "blvd",
        "drive": "dr",
        "lane": "ln",
        "highway": "hwy",
        "parkway": "pkwy",
        "apartment": "apt",
        "suite": "ste",
        "place": "pl",
        "court": "ct"
    }

    for old, new in replacements.items():
        x = x.replace(old, new)

    x = re.sub(
        r"[^\w\s]",
        " ",
        x,
        flags=re.UNICODE
    )

    x = re.sub(
        r"\s+",
        " ",
        x
    ).strip()

    return x


test_s1["name_norm"] = (
    test_s1["business_name"]
    .fillna("")
    .apply(normalize_text_unicode)
)

test_s1["address_norm"] = (
    test_s1["business_address"]
    .fillna("")
    .apply(normalize_text_unicode)
)

print("Normalization completed.")
print(test_s1.shape)

Normalization completed.
(1732544, 6)

In [ ]:
# Check whether the required TEST S1 columns are ready

print("TEST S1 rows:", len(test_s1))
print("Columns:", test_s1.columns.tolist())

print("\nSample normalized names:")
print(test_s1[["business_name", "name_norm"]].head())

print("\nSample normalized addresses:")
print(test_s1[["business_address", "address_norm"]].head())

TEST S1 rows: 1732544
Columns: ['entity_id', 'business_name', 'business_address', 'country', 'name_norm', 'address_norm']

Sample normalized names:
          business_name             name_norm
0       Zephay Labs Inc       zephay labs inc
1  Vision Partners Corp  vision partners corp
2         << Team Ecole            team ecole
3   Red Perfect Trading   red perfect trading
4         ZNB Club SARL         znb club sarl

Sample normalized addresses:
                                    business_address  \
0                        2621 Cotten Road, Tyler, TX
1             IA, Iowa City, 1064 Newton Rd, Unit 11
2  175 Boulevard du Président Franklin Roosevelt,...
3  Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...
4  Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...

                                        address_norm
0                            2621 cotten rd tyler tx
1                ia iowa city 1064 newton rd unit 11
2  175 blvd du président franklin roosevelt borde...
3  mirzapur ews 12 uttar pradesh mirzapursadar aw...
4  nouvelle aquitaine la teste de buch 5 bis rue ...

In [ ]:
# ============================================================
# BUILD DISK-BASED TEST CANDIDATE INDEX
# ============================================================

import sqlite3
import os
import gc
from pathlib import Path

INDEX_DIR = Path.cwd() / "test_index"
INDEX_DIR.mkdir(exist_ok=True)

DB_PATH = INDEX_DIR / "entity_index.db"

# Remove old incomplete index if one exists
if DB_PATH.exists():
    print("Existing index found:", DB_PATH)
else:
    print("Creating new index:", DB_PATH)

conn = sqlite3.connect(str(DB_PATH))

# Speed/safety settings
conn.execute("PRAGMA journal_mode=WAL")
conn.execute("PRAGMA synchronous=NORMAL")
conn.execute("PRAGMA temp_store=FILE")

# Main entity table
conn.execute("""
CREATE TABLE IF NOT EXISTS entities (
    entity_id TEXT PRIMARY KEY,
    business_name TEXT,
    business_address TEXT,
    name_norm TEXT,
    address_norm TEXT,
    country TEXT,
    source TEXT
)
""")

# Indexes for country + exact normalized fields
conn.execute("""
CREATE INDEX IF NOT EXISTS idx_country
ON entities(country)
""")

conn.execute("""
CREATE INDEX IF NOT EXISTS idx_name_norm
ON entities(name_norm)
""")

conn.execute("""
CREATE INDEX IF NOT EXISTS idx_address_norm
ON entities(address_norm)
""")

conn.commit()

print("Database ready:")
print(DB_PATH)

Creating new index: /Users/apple/Downloads/student_resource/dataset/train/test_index/entity_index.db
Database ready:
/Users/apple/Downloads/student_resource/dataset/train/test_index/entity_index.db

In [ ]:
print(
    "Database exists:",
    DB_PATH.exists()
)

if DB_PATH.exists():
    print(
        "Database size MB:",
        round(DB_PATH.stat().st_size / (1024**2), 2)
    )

Database exists: True
Database size MB: 0.0

In [ ]:
# ============================================================
# LOAD TEST S2 + S3 INTO SQLITE INDEX
# ============================================================

import pandas as pd
import sqlite3
import gc
from pathlib import Path

TEST_DIR = Path("/Users/apple/Downloads/student_resource 2/dataset/test")

TEST_S2 = TEST_DIR / "test_source2.tsv"
TEST_S3 = TEST_DIR / "test_source3.tsv"

CHUNK_SIZE = 100_000

print("S2 exists:", TEST_S2.exists())
print("S3 exists:", TEST_S3.exists())

conn = sqlite3.connect(str(DB_PATH))

def load_source_into_db(file_path, source_name):

    print("\n" + "=" * 60)
    print(f"Loading {source_name}")
    print("=" * 60)

    total = 0

    for chunk in pd.read_csv(
        file_path,
        sep="\t",
        dtype=str,
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ],
        chunksize=CHUNK_SIZE
    ):

        # Normalize
        chunk["name_norm"] = chunk["business_name"].apply(
            normalize_text_unicode
        )

        chunk["address_norm"] = chunk["business_address"].apply(
            normalize_text_unicode
        )

        # Add source
        chunk["source"] = source_name

        # Insert
        rows = chunk[
            [
                "entity_id",
                "business_name",
                "business_address",
                "name_norm",
                "address_norm",
                "country",
                "source"
            ]
        ].itertuples(index=False, name=None)

        conn.executemany(
            """
            INSERT OR IGNORE INTO entities
            (
                entity_id,
                business_name,
                business_address,
                name_norm,
                address_norm,
                country,
                source
            )
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            rows
        )

        conn.commit()

        total += len(chunk)

        print(
            f"Processed {total:,} rows",
            flush=True
        )

        del chunk
        gc.collect()

    print(f"{source_name} COMPLETE: {total:,} rows")


# Load S2
load_source_into_db(TEST_S2, "S2")

# Load S3
load_source_into_db(TEST_S3, "S3")

print("\n" + "=" * 60)
print("DATABASE LOADING COMPLETE")
print("=" * 60)

count = conn.execute(
    "SELECT COUNT(*) FROM entities"
).fetchone()[0]

print("Total entities in database:", f"{count:,}")

conn.close()

S2 exists: True
S3 exists: True

============================================================
Loading S2
============================================================
Processed 100,000 rows
Processed 200,000 rows
Processed 300,000 rows
Processed 400,000 rows
Processed 500,000 rows
Processed 600,000 rows
Processed 700,000 rows
Processed 800,000 rows
Processed 900,000 rows
Processed 1,000,000 rows
Processed 1,100,000 rows
Processed 1,200,000 rows
Processed 1,300,000 rows
Processed 1,400,000 rows
Processed 1,500,000 rows
Processed 1,600,000 rows
Processed 1,700,000 rows
Processed 1,800,000 rows
Processed 1,900,000 rows
Processed 2,000,000 rows
Processed 2,100,000 rows
Processed 2,200,000 rows
Processed 2,300,000 rows
Processed 2,400,000 rows
Processed 2,500,000 rows
Processed 2,600,000 rows
Processed 2,700,000 rows
Processed 2,800,000 rows
Processed 2,900,000 rows
Processed 3,000,000 rows
Processed 3,100,000 rows
Processed 3,200,000 rows
Processed 3,300,000 rows
Processed 3,400,000 rows
Processed 3,500,000 rows
Processed 3,600,000 rows
Processed 3,700,000 rows
Processed 3,800,000 rows
Processed 3,900,000 rows
Processed 4,000,000 rows
Processed 4,100,000 rows
Processed 4,200,000 rows
Processed 4,300,000 rows
Processed 4,400,000 rows
Processed 4,500,000 rows
Processed 4,600,000 rows
Processed 4,700,000 rows
Processed 4,800,000 rows
Processed 4,887,273 rows
S2 COMPLETE: 4,887,273 rows

============================================================
Loading S3
============================================================
Processed 100,000 rows
Processed 200,000 rows
Processed 300,000 rows
Processed 400,000 rows
Processed 500,000 rows
Processed 600,000 rows
Processed 700,000 rows
Processed 800,000 rows
Processed 900,000 rows
Processed 1,000,000 rows
Processed 1,100,000 rows
Processed 1,200,000 rows
Processed 1,300,000 rows
Processed 1,400,000 rows
Processed 1,500,000 rows
Processed 1,600,000 rows
Processed 1,700,000 rows
Processed 1,800,000 rows
Processed 1,900,000 rows
Processed 2,000,000 rows
Processed 2,100,000 rows
Processed 2,200,000 rows
Processed 2,300,000 rows
Processed 2,400,000 rows
Processed 2,500,000 rows
Processed 2,600,000 rows
Processed 2,700,000 rows
Processed 2,800,000 rows
Processed 2,900,000 rows
Processed 3,000,000 rows
Processed 3,100,000 rows
Processed 3,200,000 rows
Processed 3,300,000 rows
Processed 3,400,000 rows
Processed 3,500,000 rows
Processed 3,600,000 rows
Processed 3,700,000 rows
Processed 3,800,000 rows
Processed 3,900,000 rows
Processed 4,000,000 rows
Processed 4,100,000 rows
Processed 4,200,000 rows
Processed 4,300,000 rows
Processed 4,400,000 rows
Processed 4,500,000 rows
Processed 4,600,000 rows
Processed 4,700,000 rows
Processed 4,800,000 rows
Processed 4,900,000 rows
Processed 5,000,000 rows
Processed 5,082,316 rows
S3 COMPLETE: 5,082,316 rows

============================================================
DATABASE LOADING COMPLETE
============================================================
Total entities in database: 9,969,589

In [ ]:
import sqlite3

conn = sqlite3.connect(str(DB_PATH))

print("S2 in database:",
      conn.execute(
          "SELECT COUNT(*) FROM entities WHERE source='S2'"
      ).fetchone()[0])

print("S3 in database:",
      conn.execute(
          "SELECT COUNT(*) FROM entities WHERE source='S3'"
      ).fetchone()[0])

conn.close()

S2 in database: 4887273
S3 in database: 5082316

In [ ]:
import sqlite3

conn = sqlite3.connect(str(DB_PATH))

print("TABLE SCHEMA:")
schema = conn.execute(
    "SELECT sql FROM sqlite_master WHERE type='table' AND name='entities'"
).fetchone()

print(schema[0])

print("\nINDEXES:")
indexes = conn.execute(
    "SELECT name, sql FROM sqlite_master WHERE type='index' AND tbl_name='entities'"
).fetchall()

for idx in indexes:
    print(idx)

print("\nDATABASE COUNTS:")
print("Total:", conn.execute(
    "SELECT COUNT(*) FROM entities"
).fetchone()[0])

print("S2:", conn.execute(
    "SELECT COUNT(*) FROM entities WHERE source='S2'"
).fetchone()[0])

print("S3:", conn.execute(
    "SELECT COUNT(*) FROM entities WHERE source='S3'"
).fetchone()[0])

conn.close()

TABLE SCHEMA:
CREATE TABLE entities (
    entity_id TEXT PRIMARY KEY,
    business_name TEXT,
    business_address TEXT,
    name_norm TEXT,
    address_norm TEXT,
    country TEXT,
    source TEXT
)

INDEXES:
('sqlite_autoindex_entities_1', None)
('idx_country', 'CREATE INDEX idx_country\nON entities(country)\n')
('idx_name_norm', 'CREATE INDEX idx_name_norm\nON entities(name_norm)\n')
('idx_address_norm', 'CREATE INDEX idx_address_norm\nON entities(address_norm)\n')

DATABASE COUNTS:
Total: 9969589
S2: 4887273
S3: 5082316

In [ ]:
import pandas as pd

for name, path in [
    ("S2", TEST_S2),
    ("S3", TEST_S3)
]:

    print("\nChecking", name)

    total = 0
    unique_ids = set()

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id"],
        dtype=str,
        chunksize=200_000
    ):
        total += len(chunk)
        unique_ids.update(chunk["entity_id"].dropna())

    print("Total rows:", total)
    print("Unique IDs:", len(unique_ids))
    print("Duplicate rows:", total - len(unique_ids))

    del unique_ids

Checking S2
Total rows: 4887273
Unique IDs: 4887273
Duplicate rows: 0

Checking S3
Total rows: 5082316
Unique IDs: 5082316
Duplicate rows: 0

In [ ]:
import pandas as pd

s2_ids = set()

for chunk in pd.read_csv(
    TEST_S2,
    sep="\t",
    usecols=["entity_id"],
    dtype=str,
    chunksize=200_000
):
    s2_ids.update(chunk["entity_id"].dropna())

print("S2 IDs loaded:", len(s2_ids))

overlap_count = 0

for chunk in pd.read_csv(
    TEST_S3,
    sep="\t",
    usecols=["entity_id"],
    dtype=str,
    chunksize=200_000
):
    overlap_count += chunk["entity_id"].isin(s2_ids).sum()

print("S2-S3 overlapping IDs:", overlap_count)

del s2_ids

S2 IDs loaded: 4887273
S2-S3 overlapping IDs: 0

In [ ]:
import pandas as pd

for name, path in [
    ("S2", TEST_S2),
    ("S3", TEST_S3)
]:
    print("\nChecking", name)

    total = 0
    missing = 0
    blank = 0

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id"],
        dtype=str,
        chunksize=200_000
    ):
        total += len(chunk)

        missing += chunk["entity_id"].isna().sum()

        blank += (
            chunk["entity_id"]
            .fillna("")
            .str.strip()
            .eq("")
            .sum()
        )

    print("Total rows :", total)
    print("Missing IDs:", missing)
    print("Blank IDs  :", blank)
    print("Valid IDs  :", total - missing - blank)

Checking S2
Total rows : 4887273
Missing IDs: 0
Blank IDs  : 0
Valid IDs  : 4887273

Checking S3
Total rows : 5082316
Missing IDs: 0
Blank IDs  : 0
Valid IDs  : 5082316

In [ ]:
# Check exactly what SQLite contains

print("Expected S2:", 4_887_273)
print("Expected S3:", 5_082_316)
print("Expected total:", 4_887_273 + 5_082_316)

print("\nActual database:")

for source in ["S2", "S3"]:
    result = conn.execute(
        "SELECT COUNT(*) FROM entities WHERE source = ?",
        (source,)
    ).fetchone()[0]

    print(f"{source}:", result)

total_db = conn.execute(
    "SELECT COUNT(*) FROM entities"
).fetchone()[0]

print("Total:", total_db)

print("\nSQLite integrity check:")
print(conn.execute("PRAGMA integrity_check").fetchone()[0])

Expected S2: 4887273
Expected S3: 5082316
Expected total: 9969589

Actual database:

ProgrammingError: Cannot operate on a closed database.

In [ ]:
import sqlite3

DB_PATH = Path.cwd() / "test_index" / "entity_index.db"

conn = sqlite3.connect(DB_PATH)

print("Database reopened successfully.")
print("Database path:", DB_PATH)

Database reopened successfully.
Database path: /Users/apple/Downloads/student_resource/dataset/train/test_index/entity_index.db

In [ ]:
print("Expected S2:", 4_887_273)
print("Expected S3:", 5_082_316)
print("Expected total:", 9_969_589)

print("\nActual database:")

for source in ["S2", "S3"]:
    result = conn.execute(
        "SELECT COUNT(*) FROM entities WHERE source = ?",
        (source,)
    ).fetchone()[0]

    print(f"{source}:", result)

total_db = conn.execute(
    "SELECT COUNT(*) FROM entities"
).fetchone()[0]

print("Total:", total_db)

print("\nSQLite integrity check:")
print(conn.execute("PRAGMA integrity_check").fetchone()[0])

Expected S2: 4887273
Expected S3: 5082316
Expected total: 9969589

Actual database:
S2: 4887273
S3: 5082316
Total: 9969589

SQLite integrity check:
ok

In [ ]:
# Quick database content check

sample = conn.execute("""
    SELECT entity_id, business_name, business_address,
           name_norm, address_norm, country, source
    FROM entities
    LIMIT 5
""").fetchall()

for row in sample:
    print(row)

('S2-192345572', 'Brahma Infosoft', 'COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karnataka', 'brahma infosoft', 'coimatore colony hunsur tqmysore dist karnataka', 'India', 'S2')
('S2-566025912', 'Marina Ecole France Sarl', '63 R. DE DIEPPE, LILLE, Hauts-de-France', 'marina ecole france sarl', '63 r de dieppe lille hauts de france', 'France', 'S2')
('S2-158121477', 'SCI Ptit Àmicale', '18 RUE JEN ZAY, Dunkerque, Nord', 'sci ptit àmicale', '18 rue jen zay dunkerque nord', 'France', 'S2')
('S2-89663826', 'Apex Summit', '67 KENTUCKY ST, SALYERSVILLE, KY', 'apex summit', '67 kentucky st salyersville ky', 'US', 'S2')
('S2-884102769', 'Fresh Truist', '8264 FILLY COURT, ROANOKE COUNTY, VA', 'fresh truist', '8264 filly ct roanoke county va', 'US', 'S2')

In [ ]:
# Check whether SQLite FTS5 is available

try:
    conn.execute("""
        CREATE VIRTUAL TABLE IF NOT EXISTS fts_test
        USING fts5(entity_id, name_norm, address_norm)
    """)
    
    print("✅ SQLite FTS5 is available.")
    
    conn.execute("DROP TABLE IF EXISTS fts_test")
    conn.commit()

except Exception as e:
    print("❌ SQLite FTS5 is NOT available.")
    print("Error:", e)

✅ SQLite FTS5 is available.

In [ ]:
import time

start = time.time()

# Remove any previous FTS table
conn.execute("DROP TABLE IF EXISTS entity_fts")

# Create FTS5 index
conn.execute("""
    CREATE VIRTUAL TABLE entity_fts
    USING fts5(
        entity_id UNINDEXED,
        name_norm,
        address_norm,
        country UNINDEXED,
        source UNINDEXED
    )
""")

conn.commit()

print("✅ FTS5 table created.")
print("Time:", round(time.time() - start, 2), "seconds")

✅ FTS5 table created.
Time: 0.0 seconds

In [ ]:
import time

start = time.time()

# Populate FTS5 from the existing SQLite table
conn.execute("""
    INSERT INTO entity_fts (
        entity_id,
        name_norm,
        address_norm,
        country,
        source
    )
    SELECT
        entity_id,
        name_norm,
        address_norm,
        country,
        source
    FROM entities
""")

conn.commit()

elapsed = time.time() - start

count = conn.execute(
    "SELECT COUNT(*) FROM entity_fts"
).fetchone()[0]

print("✅ FTS5 populated")
print("Rows:", count)
print("Time:", round(elapsed / 60, 2), "minutes")

✅ FTS5 populated
Rows: 9969589
Time: 3.54 minutes

In [ ]:
# Test FTS5 search using the first S1 record

row = test_s1.iloc[0]

print("S1 ID:", row["entity_id"])
print("Name:", row["business_name"])
print("Address:", row["business_address"])
print("Country:", row["country"])

query = row["name_norm"]

print("\nFTS query:", query)

results = conn.execute("""
    SELECT entity_id, name_norm, address_norm, country, source
    FROM entity_fts
    WHERE entity_fts MATCH ?
    LIMIT 10
""", (query,)).fetchall()

print("\nCandidates found:", len(results))

for r in results:
    print(r)

S1 ID: S1-714132312
Name: Zephay Labs Inc
Address: 2621 Cotten Road, Tyler, TX
Country: US

FTS query: zephay labs inc

Candidates found: 2
('S2-786029403', 'zephay labs central inc', '2622 cotten rd tylr tx', 'US', 'S2')
('S3-625880872', 'inc zephay labs', '2621 cotten rd tyler texas', 'US', 'S3')

In [ ]:
row = test_s1.iloc[0]

name_query = row["name_norm"]
address_query = row["address_norm"]

print("S1:", row["entity_id"])
print("Name:", name_query)
print("Address:", address_query)

# Name search
name_results = conn.execute("""
    SELECT entity_id, name_norm, address_norm, country, source, bm25(entity_fts)
    FROM entity_fts
    WHERE entity_fts MATCH ?
    ORDER BY bm25(entity_fts)
    LIMIT 10
""", (name_query,)).fetchall()

# Address search
address_results = conn.execute("""
    SELECT entity_id, name_norm, address_norm, country, source, bm25(entity_fts)
    FROM entity_fts
    WHERE entity_fts MATCH ?
    ORDER BY bm25(entity_fts)
    LIMIT 10
""", (address_query,)).fetchall()

print("\nNAME candidates:", len(name_results))
for r in name_results:
    print(r)

print("\nADDRESS candidates:", len(address_results))
for r in address_results:
    print(r)

S1: S1-714132312
Name: zephay labs inc
Address: 2621 cotten rd tyler tx

NAME candidates: 2
('S3-625880872', 'inc zephay labs', '2621 cotten rd tyler texas', 'US', 'S3', -24.943392499998048)
('S2-786029403', 'zephay labs central inc', '2622 cotten rd tylr tx', 'US', 'S2', -24.05248871139219)

ADDRESS candidates: 0

In [ ]:
row = test_s1.iloc[0]

# Take useful address tokens
address_tokens = [
    token for token in row["address_norm"].split()
    if len(token) >= 3
]

print("Address tokens:", address_tokens)

# Search using OR between address terms
address_query = " OR ".join(address_tokens)

print("FTS address query:", address_query)

address_results = conn.execute("""
    SELECT entity_id, name_norm, address_norm, country, source, bm25(entity_fts)
    FROM entity_fts
    WHERE entity_fts MATCH ?
    ORDER BY bm25(entity_fts)
    LIMIT 20
""", (address_query,)).fetchall()

print("\nAddress candidates:", len(address_results))

for r in address_results:
    print(r)

Address tokens: ['2621', 'cotten', 'tyler']
FTS address query: 2621 OR cotten OR tyler

Address candidates: 20
('S3-625880872', 'inc zephay labs', '2621 cotten rd tyler texas', 'US', 'S3', -34.94478431068295)
('S3-867809779', 'zephix labs inc', '2621 cotten rd tyler texas', 'US', 'S3', -34.94478431068295)
('S2-187020300', 'zephay lesai inc', '2622 cotten rd tyler tx', 'US', 'S2', -23.117466824961273)
('S2-637340732', 'zephay inc services', '2622 cotten rd tyler tx', 'US', 'S2', -23.117466824961273)
('S3-153999999', 'eaves wheeler', '2621 caldwell circle tyler texas', 'US', 'S3', -21.787011832448464)
('S2-866350613', 'tyler walton and metayer corp', '2621 angier ave durham nc', 'US', 'S2', -19.533016078073146)
('S2-578943822', 'tyler walton and metayer co', '2621 angier ave durham nc', 'US', 'S2', -19.533016078073146)
('S2-728762551', 'pate cotten and price', '', 'US', 'S2', -16.39364430893702)
('S2-921668346', 'cotten s custom ínsurance llc', '', 'US', 'S2', -15.710514658528755)
('S2-992475810', 'health cóuncil', 'cotten dr morrisville nc', 'US', 'S2', -15.08204007591935)
('S2-794384326', 'herrera japan', 'nc 1076 cotten rd sanford', 'US', 'S2', -14.501913686108994)
('S2-876779872', 'quality investment', 'nc morrisville 0156 cotten dr', 'US', 'S2', -14.501913686108994)
('S2-309644025', 'stewart gen', '13345 cotten rd savannah ny', 'US', 'S2', -14.501913686108994)
('S2-921166671', 'cotten excavation', 'mo independence 1207 swope dr', 'US', 'S2', -14.501913686108994)
('S2-208410357', 'herrera jasf', '1076 cotten rd sanford nc', 'US', 'S2', -14.501913686108994)
('S2-577128168', 'stewart gen', '13345 cotten rd savannah ny', 'US', 'S2', -14.501913686108994)
('S3-9659746', 'psenergy com', '179 cotten ln malvern arkansas', 'US', 'S3', -14.501913686108994)
('S2-549930125', 'health cóuncil co', '212 cotten dr morrisville nc', 'US', 'S2', -13.96476304028537)
('S2-656924768', 'llc quality ínvestment systems', 'cotten dr morrisville nc', 'US', 'S2', -13.96476304028537)
('S2-428798303', 'stewart dental inc', '13354 cotten rd savnanah ny', 'US', 'S2', -13.96476304028537)

In [ ]:
from rapidfuzz import fuzz
import pandas as pd

row = test_s1.iloc[0]

# -----------------------------
# 1. Get name candidates
# -----------------------------
name_results = conn.execute("""
    SELECT entity_id, name_norm, address_norm, country, source
    FROM entity_fts
    WHERE entity_fts MATCH ?
    ORDER BY bm25(entity_fts)
    LIMIT 50
""", (row["name_norm"],)).fetchall()

# -----------------------------
# 2. Get address candidates
# -----------------------------
address_tokens = [
    t for t in row["address_norm"].split()
    if len(t) >= 3
]

address_query = " OR ".join(address_tokens)

address_results = conn.execute("""
    SELECT entity_id, name_norm, address_norm, country, source
    FROM entity_fts
    WHERE entity_fts MATCH ?
    ORDER BY bm25(entity_fts)
    LIMIT 50
""", (address_query,)).fetchall()

# -----------------------------
# 3. Combine and deduplicate
# -----------------------------
candidates = {}

for r in name_results + address_results:
    candidates[r[0]] = r

print("Name candidates   :", len(name_results))
print("Address candidates:", len(address_results))
print("Unique candidates :", len(candidates))

# -----------------------------
# 4. Calculate similarities
# -----------------------------
rows = []

for entity_id, name, address, country, source in candidates.values():

    name_similarity = fuzz.ratio(
        row["name_norm"],
        name
    ) / 100

    address_similarity = fuzz.ratio(
        row["address_norm"],
        address
    ) / 100

    country_match = int(
        str(row["country"]).lower() ==
        str(country).lower()
    )

    rows.append({
        "entity_id": entity_id,
        "source": source,
        "name": name,
        "address": address,
        "name_similarity": name_similarity,
        "address_similarity": address_similarity,
        "country_match": country_match
    })

candidate_df = pd.DataFrame(rows)

candidate_df = candidate_df.sort_values(
    ["name_similarity", "address_similarity"],
    ascending=False
)

print("\nTop candidates:")
display(candidate_df.head(15))

Name candidates   : 2
Address candidates: 50
Unique candidates : 50

Top candidates:

,entity_id,source,name,address,name_similarity,address_similarity,country_match
2,S3-867809779,S3,zephix labs inc,2621 cotten rd tyler texas,0.866667,0.938776,1
3,S2-187020300,S2,zephay lesai inc,2622 cotten rd tyler tx,0.838710,0.956522,1
1,S2-786029403,S2,zephay labs central inc,2622 cotten rd tylr tx,0.789474,0.933333,1
23,S2-435263846,S2,zephay labs west,tylr 2622 cotten rd tx,0.774194,0.711111,1
0,S3-625880872,S3,inc zephay labs,2621 cotten rd tyler texas,0.733333,0.938776,1
4,S2-637340732,S2,zephay inc services,2622 cotten rd tyler tx,0.588235,0.956522,1
20,S2-428798303,S2,stewart dental inc,13354 cotten rd savnanah ny,0.484848,0.520000,1
10,S2-992475810,S2,health cóuncil,cotten dr morrisville nc,0.413793,0.510638,1
33,S3-545322804,S3,health cóuncil,212 cotten dr moorrisville north carolina,0.413793,0.500000,1
36,S2-82281142,S2,the stewart gen inc,13345 cotten rd savannah ny,0.411765,0.520000,1
8,S2-728762551,S2,pate cotten and price,,0.388889,0.000000,1
18,S2-549930125,S2,health cóuncil co,212 cotten dr morrisville nc,0.375000,0.588235,1
21,S2-389810062,S2,health council co,212 cotten dr nc morrisville,0.375000,0.549020,1
43,S3-153757746,S3,herrera japan llc,1080 cotten rd sanford north carolina,0.375000,0.500000,1
15,S2-208410357,S2,herrera jasf,1076 cotten rd sanford nc,0.370370,0.583333,1

In [ ]:
import time

N = 1000
TOP_K_NAME = 50
TOP_K_ADDRESS = 50

start = time.time()

candidate_counts = []
zero_candidates = 0

for i in range(N):

    row = test_s1.iloc[i]

    # -------------------------
    # Name candidates
    # -------------------------
    name_results = conn.execute("""
        SELECT entity_id
        FROM entity_fts
        WHERE entity_fts MATCH ?
        ORDER BY bm25(entity_fts)
        LIMIT ?
    """, (row["name_norm"], TOP_K_NAME)).fetchall()

    # -------------------------
    # Address candidates
    # -------------------------
    tokens = [
        t for t in row["address_norm"].split()
        if len(t) >= 3
    ]

    address_results = []

    if tokens:
        address_query = " OR ".join(tokens)

        address_results = conn.execute("""
            SELECT entity_id
            FROM entity_fts
            WHERE entity_fts MATCH ?
            ORDER BY bm25(entity_fts)
            LIMIT ?
        """, (address_query, TOP_K_ADDRESS)).fetchall()

    # -------------------------
    # Combine
    # -------------------------
    candidate_ids = set(
        x[0] for x in name_results
    )

    candidate_ids.update(
        x[0] for x in address_results
    )

    count = len(candidate_ids)

    candidate_counts.append(count)

    if count == 0:
        zero_candidates += 1

elapsed = time.time() - start

print("================================")
print("FTS5 Candidate Benchmark")
print("================================")
print("S1 records tested :", N)
print("Average candidates:", round(sum(candidate_counts) / N, 2))
print("Maximum candidates:", max(candidate_counts))
print("Minimum candidates:", min(candidate_counts))
print("Zero candidates   :", zero_candidates)
print("Total candidates  :", sum(candidate_counts))
print("Time              :", round(elapsed / 60, 2), "minutes")
print("Time per S1       :", round(elapsed / N, 4), "seconds")
print("================================")

================================
FTS5 Candidate Benchmark
================================
S1 records tested : 1000
Average candidates: 66.51
Maximum candidates: 100
Minimum candidates: 50
Zero candidates   : 0
Total candidates  : 66511
Time              : 14.97 minutes
Time per S1       : 0.8984 seconds
================================

In [ ]:
import time

start = time.time()

# Remove old temporary S1 table
conn.execute("DROP TABLE IF EXISTS test_s1_index")

# Create S1 table
conn.execute("""
CREATE TABLE test_s1_index (
    entity_id TEXT PRIMARY KEY,
    name_norm TEXT,
    address_norm TEXT,
    country TEXT
)
""")

conn.commit()

print("Loading S1 into SQLite...")

rows = [
    (
        str(r.entity_id),
        str(r.name_norm),
        str(r.address_norm),
        str(r.country)
    )
    for r in test_s1.itertuples(index=False)
]

conn.executemany("""
INSERT INTO test_s1_index
(entity_id, name_norm, address_norm, country)
VALUES (?, ?, ?, ?)
""", rows)

conn.commit()

# Indexes
conn.execute("""
CREATE INDEX idx_s1_name_country
ON test_s1_index(name_norm, country)
""")

conn.execute("""
CREATE INDEX idx_s1_address_country
ON test_s1_index(address_norm, country)
""")

conn.commit()

print("S1 rows:", conn.execute(
    "SELECT COUNT(*) FROM test_s1_index"
).fetchone()[0])

print("Time:", round((time.time() - start) / 60, 2), "minutes")

Loading S1 into SQLite...
S1 rows: 1732544
Time: 0.6 minutes

In [ ]:
import time
from pathlib import Path

start = time.time()

OUTPUT_DIR = Path("output")
OUTPUT_DIR.mkdir(exist_ok=True)

CANDIDATE_FILE = OUTPUT_DIR / "candidate_pairs.tsv"

# Remove previous file if it exists
if CANDIDATE_FILE.exists():
    CANDIDATE_FILE.unlink()

# Create temporary candidate table
conn.execute("DROP TABLE IF EXISTS candidate_pairs_temp")

conn.execute("""
CREATE TABLE candidate_pairs_temp (
    source1_entity_id TEXT,
    candidate_entity_id TEXT,
    PRIMARY KEY (source1_entity_id, candidate_entity_id)
)
""")

conn.commit()

print("1. Matching exact normalized NAME + country...")

conn.execute("""
INSERT OR IGNORE INTO candidate_pairs_temp
(source1_entity_id, candidate_entity_id)

SELECT
    s1.entity_id,
    e.entity_id
FROM test_s1_index s1
JOIN entities e
    ON s1.name_norm = e.name_norm
   AND s1.country = e.country
WHERE s1.name_norm <> ''
  AND e.name_norm <> ''
""")

conn.commit()

print(
    "After name matching:",
    conn.execute("SELECT COUNT(*) FROM candidate_pairs_temp").fetchone()[0]
)

print("2. Matching exact normalized ADDRESS + country...")

conn.execute("""
INSERT OR IGNORE INTO candidate_pairs_temp
(source1_entity_id, candidate_entity_id)

SELECT
    s1.entity_id,
    e.entity_id
FROM test_s1_index s1
JOIN entities e
    ON s1.address_norm = e.address_norm
   AND s1.country = e.country
WHERE s1.address_norm <> ''
  AND e.address_norm <> ''
""")

conn.commit()

total = conn.execute(
    "SELECT COUNT(*) FROM candidate_pairs_temp"
).fetchone()[0]

print("Final candidate pairs:", f"{total:,}")

# Export TSV
print("\nWriting candidate_pairs.tsv...")

with open(CANDIDATE_FILE, "w", encoding="utf-8") as f:

    f.write("source1_entity_id\tcandidate_entity_id\n")

    cursor = conn.execute("""
        SELECT source1_entity_id, candidate_entity_id
        FROM candidate_pairs_temp
    """)

    batch = []

    for source1_id, candidate_id in cursor:
        batch.append(f"{source1_id}\t{candidate_id}\n")

        if len(batch) >= 100000:
            f.writelines(batch)
            batch.clear()

    if batch:
        f.writelines(batch)

elapsed = time.time() - start

print("\n================================")
print("CANDIDATE GENERATION COMPLETE")
print("================================")
print("Candidate pairs:", f"{total:,}")
print("Time:", round(elapsed / 60, 2), "minutes")
print("File:", CANDIDATE_FILE)
print("================================")

1. Matching exact normalized NAME + country...
After name matching: 12910158
2. Matching exact normalized ADDRESS + country...
Final candidate pairs: 13,590,750

Writing candidate_pairs.tsv...

================================
CANDIDATE GENERATION COMPLETE
================================
Candidate pairs: 13,590,750
Time: 10.95 minutes
File: output/candidate_pairs.tsv
================================

In [ ]:
from pathlib import Path

print(Path("output/candidate_pairs.tsv").resolve())

/Users/apple/Downloads/student_resource/dataset/train/output/candidate_pairs.tsv

In [ ]:
from pathlib import Path

p = Path("output/candidate_pairs.tsv")

print("Exists:", p.exists())
print("Size:", round(p.stat().st_size / (1024**3), 2), "GB")

Exists: True
Size: 0.33 GB

In [ ]:


import pandas as pd
import joblib
import time
from pathlib import Path

# Paths
MODEL_PATH = Path("entity_matching_model.pkl")
CANDIDATE_FILE = Path("output/candidate_pairs.tsv")
RESULT_FILE = Path("output/matching_results.tsv")

# Load model
model = joblib.load(MODEL_PATH)

print("✅ Model loaded")

# Check model
print("Model:", type(model).__name__)

✅ Model loaded
Model: HistGradientBoostingClassifier

In [ ]:
import pandas as pd
import numpy as np
import time
from rapidfuzz import fuzz
from pathlib import Path

CANDIDATE_FILE = Path("output/candidate_pairs.tsv")

THRESHOLD = 0.10
CHUNK_SIZE = 100_000

start = time.time()
total_candidates = 0
total_matches = 0

# Create temporary scored-pairs table
conn.execute("DROP TABLE IF EXISTS scored_pairs")

conn.execute("""
CREATE TABLE scored_pairs (
    source1_entity_id TEXT,
    candidate_entity_id TEXT
)
""")

conn.commit()

print("Starting candidate scoring...")

for chunk_no, chunk in enumerate(
    pd.read_csv(
        CANDIDATE_FILE,
        sep="\t",
        dtype=str,
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    # Join candidate pairs with S1 and candidate entity information
    ids = chunk["candidate_entity_id"].tolist()

    # Get candidate entity information in batches
    placeholders = ",".join(["?"] * len(ids))

    candidate_data = pd.read_sql_query(
        f"""
        SELECT
            entity_id,
            name_norm,
            address_norm,
            country
        FROM entities
        WHERE entity_id IN ({placeholders})
        """,
        conn,
        params=ids
    )

    candidate_data = candidate_data.drop_duplicates("entity_id")

    chunk = chunk.merge(
        candidate_data,
        left_on="candidate_entity_id",
        right_on="entity_id",
        how="inner"
    )

    # Get S1 information
    s1_data = pd.read_sql_query(
        f"""
        SELECT
            entity_id,
            name_norm,
            address_norm,
            country
        FROM test_s1_index
        WHERE entity_id IN ({",".join(["?"] * chunk["source1_entity_id"].nunique())})
        """,
        conn,
        params=chunk["source1_entity_id"].unique().tolist()
    )

    s1_data = s1_data.drop_duplicates("entity_id")

    chunk = chunk.merge(
        s1_data,
        left_on="source1_entity_id",
        right_on="entity_id",
        how="inner",
        suffixes=("_candidate", "_s1")
    )

    # Model features
    chunk["name_exact"] = (
        chunk["name_norm_s1"] == chunk["name_norm_candidate"]
    ).astype(int)

    chunk["address_exact"] = (
        chunk["address_norm_s1"] == chunk["address_norm_candidate"]
    ).astype(int)

    chunk["name_similarity"] = [
        fuzz.ratio(a, b) / 100
        for a, b in zip(
            chunk["name_norm_s1"],
            chunk["name_norm_candidate"]
        )
    ]

    chunk["address_similarity"] = [
        fuzz.ratio(a, b) / 100
        for a, b in zip(
            chunk["address_norm_s1"],
            chunk["address_norm_candidate"]
        )
    ]

    chunk["country_match"] = (
        chunk["country_s1"].str.lower() ==
        chunk["country_candidate"].str.lower()
    ).astype(int)

    features = [
        "name_exact",
        "name_similarity",
        "address_exact",
        "address_similarity",
        "country_match"
    ]

    probabilities = model.predict_proba(
        chunk[features]
    )[:, 1]

    chunk["probability"] = probabilities

    matches = chunk[
        chunk["probability"] >= THRESHOLD
    ][[
        "source1_entity_id",
        "candidate_entity_id"
    ]]

    if len(matches):
        matches.to_sql(
            "scored_pairs",
            conn,
            if_exists="append",
            index=False
        )

        total_matches += len(matches)

    total_candidates += len(chunk)

    if chunk_no % 10 == 0:
        elapsed = time.time() - start
        print(
            f"Processed: {total_candidates:,} | "
            f"Matches: {total_matches:,} | "
            f"Time: {elapsed/60:.1f} min"
        )

conn.commit()

elapsed = time.time() - start

print("\n================================")
print("SCORING COMPLETE")
print("================================")
print("Candidates scored:", f"{total_candidates:,}")
print("Predicted matches:", f"{total_matches:,}")
print("Time:", round(elapsed / 60, 2), "minutes")

Starting candidate scoring...

DatabaseError: Execution failed on sql '
        SELECT
            entity_id,
            name_norm,
            address_norm,
            country
        FROM entities

In [ ]:
import pandas as pd
import numpy as np
import time
from rapidfuzz import fuzz
from pathlib import Path

CANDIDATE_FILE = Path("output/candidate_pairs.tsv")

THRESHOLD = 0.10
CHUNK_SIZE = 100_000

start = time.time()
total_candidates = 0
total_matches = 0

# Reset temporary tables
conn.execute("DROP TABLE IF EXISTS candidate_chunk")
conn.execute("DROP TABLE IF EXISTS scored_pairs")

conn.execute("""
CREATE TEMP TABLE candidate_chunk (
    source1_entity_id TEXT,
    candidate_entity_id TEXT,
    PRIMARY KEY (source1_entity_id, candidate_entity_id)
)
""")

conn.execute("""
CREATE TABLE scored_pairs (
    source1_entity_id TEXT,
    candidate_entity_id TEXT
)
""")

conn.commit()

print("Starting candidate scoring...")

for chunk_no, chunk in enumerate(
    pd.read_csv(
        CANDIDATE_FILE,
        sep="\t",
        dtype=str,
        chunksize=CHUNK_SIZE
    ),
    start=1
):

    # Clear previous chunk
    conn.execute("DELETE FROM candidate_chunk")

    # Insert candidate pairs into SQLite
    conn.executemany(
        """
        INSERT OR IGNORE INTO candidate_chunk
        (source1_entity_id, candidate_entity_id)
        VALUES (?, ?)
        """,
        list(
            chunk[
                ["source1_entity_id", "candidate_entity_id"]
            ].itertuples(index=False, name=None)
        )
    )

    conn.commit()

    # Retrieve both S1 and candidate records through JOIN
    data = pd.read_sql_query(
        """
        SELECT
            cp.source1_entity_id,
            cp.candidate_entity_id,

            s1.name_norm AS s1_name,
            s1.address_norm AS s1_address,
            s1.country AS s1_country,

            e.name_norm AS candidate_name,
            e.address_norm AS candidate_address,
            e.country AS candidate_country

        FROM candidate_chunk cp

        JOIN test_s1_index s1
          ON cp.source1_entity_id = s1.entity_id

        JOIN entities e
          ON cp.candidate_entity_id = e.entity_id
        """,
        conn
    )

    if len(data) == 0:
        continue

    # -----------------------------
    # Model features
    # -----------------------------

    data["name_exact"] = (
        data["s1_name"] == data["candidate_name"]
    ).astype(int)

    data["address_exact"] = (
        data["s1_address"] == data["candidate_address"]
    ).astype(int)

    data["country_match"] = (
        data["s1_country"].str.lower()
        ==
        data["candidate_country"].str.lower()
    ).astype(int)

    # RapidFuzz similarities
    data["name_similarity"] = [
        fuzz.ratio(a, b) / 100
        for a, b in zip(
            data["s1_name"],
            data["candidate_name"]
        )
    ]

    data["address_similarity"] = [
        fuzz.ratio(a, b) / 100
        for a, b in zip(
            data["s1_address"],
            data["candidate_address"]
        )
    ]

    features = [
        "name_exact",
        "name_similarity",
        "address_exact",
        "address_similarity",
        "country_match"
    ]

    # Model prediction
    probabilities = model.predict_proba(
        data[features]
    )[:, 1]

    data["probability"] = probabilities

    matches = data[
        data["probability"] >= THRESHOLD
    ][[
        "source1_entity_id",
        "candidate_entity_id"
    ]]

    if len(matches):
        conn.executemany(
            """
            INSERT INTO scored_pairs
            (source1_entity_id, candidate_entity_id)
            VALUES (?, ?)
            """,
            list(
                matches.itertuples(
                    index=False,
                    name=None
                )
            )
        )

        conn.commit()

        total_matches += len(matches)

    total_candidates += len(data)

    if chunk_no % 10 == 0:
        elapsed = time.time() - start
        print(
            f"Chunk {chunk_no:,} | "
            f"Candidates: {total_candidates:,} | "
            f"Matches: {total_matches:,} | "
            f"Time: {elapsed/60:.1f} min"
        )

conn.commit()

elapsed = time.time() - start

print("\n================================")
print("SCORING COMPLETE")
print("================================")
print("Candidates scored:", f"{total_candidates:,}")
print("Predicted matches:", f"{total_matches:,}")
print("Time:", round(elapsed / 60, 2), "minutes")
print("================================")

Starting candidate scoring...
Chunk 10 | Candidates: 1,000,000 | Matches: 1,000,000 | Time: 1.3 min
Chunk 20 | Candidates: 2,000,000 | Matches: 2,000,000 | Time: 2.3 min
Chunk 30 | Candidates: 3,000,000 | Matches: 3,000,000 | Time: 3.0 min
Chunk 40 | Candidates: 4,000,000 | Matches: 4,000,000 | Time: 3.7 min
Chunk 50 | Candidates: 5,000,000 | Matches: 5,000,000 | Time: 4.3 min
Chunk 60 | Candidates: 6,000,000 | Matches: 6,000,000 | Time: 5.0 min
Chunk 70 | Candidates: 7,000,000 | Matches: 7,000,000 | Time: 5.6 min
Chunk 80 | Candidates: 8,000,000 | Matches: 8,000,000 | Time: 6.2 min
Chunk 90 | Candidates: 9,000,000 | Matches: 9,000,000 | Time: 6.9 min
Chunk 100 | Candidates: 10,000,000 | Matches: 10,000,000 | Time: 7.5 min
Chunk 110 | Candidates: 11,000,000 | Matches: 11,000,000 | Time: 8.1 min
Chunk 120 | Candidates: 12,000,000 | Matches: 12,000,000 | Time: 8.8 min
Chunk 130 | Candidates: 13,000,000 | Matches: 13,000,000 | Time: 9.5 min

================================
SCORING COMPLETE
================================
Candidates scored: 13,590,750
Predicted matches: 13,590,750
Time: 10.16 minutes
================================

In [ ]:
# Check how many matches each S1 received

stats = pd.read_sql_query("""
    SELECT
        source1_entity_id,
        COUNT(*) AS match_count
    FROM scored_pairs
    GROUP BY source1_entity_id
""", conn)

print("S1 entities with predictions:", len(stats))
print("Total S1 entities:", len(test_s1))

print("\nMatch-count statistics:")
print(stats["match_count"].describe())

print("\nDistribution:")
print(stats["match_count"].value_counts().sort_index().head(20))

print("\nMaximum matches for one S1:", stats["match_count"].max())

S1 entities with predictions: 1391765
Total S1 entities: 1732544

Match-count statistics:
count    1.391765e+06
mean     9.765118e+00
std      2.020700e+01
min      1.000000e+00
25%      1.000000e+00
50%      3.000000e+00
75%      1.000000e+01
max      4.800000e+02
Name: match_count, dtype: float64

Distribution:
match_count
1     392000
2     282566
3     156413
4      80701
5      45225
6      29273
7      21615
8      17130
9      13832
10     12428
11     11523
12     11598
13     11781
14     11738
15     13110
16     14252
17     15886
18     17754
19     17749
20     18499
Name: count, dtype: int64

Maximum matches for one S1: 480

In [ ]:
# Check model probability distribution on candidate pairs

import pandas as pd
import numpy as np
from rapidfuzz import fuzz

sample = pd.read_csv(
    "output/candidate_pairs.tsv",
    sep="\t",
    dtype=str,
    nrows=100_000
)

# Load S1 data
sample = sample.merge(
    test_s1[[
        "entity_id",
        "name_norm",
        "address_norm",
        "country"
    ]],
    left_on="source1_entity_id",
    right_on="entity_id",
    how="left"
).drop(columns=["entity_id"])

# Candidate IDs
candidate_info = pd.read_sql_query("""
    SELECT entity_id, name_norm, address_norm, country
    FROM entities
""", conn)

# Only keep candidates appearing in sample
candidate_info = candidate_info[
    candidate_info["entity_id"].isin(
        sample["candidate_entity_id"]
    )
].drop_duplicates("entity_id")

sample = sample.merge(
    candidate_info,
    left_on="candidate_entity_id",
    right_on="entity_id",
    how="left",
    suffixes=("_s1", "_candidate")
)

# Features
sample["name_exact"] = (
    sample["name_norm_s1"] ==
    sample["name_norm_candidate"]
).astype(int)

sample["address_exact"] = (
    sample["address_norm_s1"] ==
    sample["address_norm_candidate"]
).astype(int)

sample["country_match"] = (
    sample["country_s1"].str.lower() ==
    sample["country_candidate"].str.lower()
).astype(int)

sample["name_similarity"] = [
    fuzz.ratio(a, b) / 100
    for a, b in zip(
        sample["name_norm_s1"],
        sample["name_norm_candidate"]
    )
]

sample["address_similarity"] = [
    fuzz.ratio(a, b) / 100
    for a, b in zip(
        sample["address_norm_s1"],
        sample["address_norm_candidate"]
    )
]

features = [
    "name_exact",
    "name_similarity",
    "address_exact",
    "address_similarity",
    "country_match"
]

sample["probability"] = model.predict_proba(
    sample[features]
)[:, 1]

print("Probability distribution:")
print(sample["probability"].describe(
    percentiles=[.01, .05, .10, .25, .50, .75, .90, .95, .99]
))

print("\nThreshold counts:")
for t in [0.10, 0.50, 0.70, 0.90, 0.95, 0.99]:
    print(
        f"{t:.2f}:",
        (sample["probability"] >= t).sum()
    )

Probability distribution:
count    100000.000000
mean          0.999994
std           0.000002
min           0.999983
1%            0.999983
5%            0.999990
10%           0.999993
25%           0.999993
50%           0.999994
75%           0.999995
90%           0.999996
95%           0.999998
99%           0.999998
max           0.999998
Name: probability, dtype: float64

Threshold counts:
0.10: 100000
0.50: 100000
0.70: 100000
0.90: 100000
0.95: 100000
0.99: 100000

In [ ]:
# Inspect candidate quality for a few S1 entities

check = pd.read_sql_query("""
SELECT
    cp.source1_entity_id,
    cp.candidate_entity_id,

    s1.name_norm AS s1_name,
    e.name_norm AS candidate_name,

    s1.address_norm AS s1_address,
    e.address_norm AS candidate_address,

    s1.country AS s1_country,
    e.country AS candidate_country

FROM scored_pairs cp

JOIN test_s1_index s1
    ON cp.source1_entity_id = s1.entity_id

JOIN entities e
    ON cp.candidate_entity_id = e.entity_id

LIMIT 20
""", conn)

check["name_similarity"] = [
    fuzz.ratio(a, b) / 100
    for a, b in zip(
        check["s1_name"],
        check["candidate_name"]
    )
]

check["address_similarity"] = [
    fuzz.ratio(a, b) / 100
    for a, b in zip(
        check["s1_address"],
        check["candidate_address"]
    )
]

display(
    check[[
        "source1_entity_id",
        "candidate_entity_id",
        "s1_name",
        "candidate_name",
        "name_similarity",
        "s1_address",
        "candidate_address",
        "address_similarity"
    ]]
)

,source1_entity_id,candidate_entity_id,s1_name,candidate_name,name_similarity,s1_address,candidate_address,address_similarity
0,S1-106407869,S2-47475427,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,613 elm dr maryville tn,0.275862
1,S1-106407869,S2-886540563,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,248 locust st canby or,0.315789
2,S1-106407869,S2-997023970,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,4119 port tobacco rd nanjemoy md,0.358209
3,S1-106407869,S2-571602010,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,2250 chatterton ave bronx ity ny,0.388060
4,S1-106407869,S2-352931092,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,722 windover dr brevard nc,0.327869
5,S1-106407869,S2-705547832,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,ia 1064 netwon rd iowa cityc ity,0.597015
6,S1-106407869,S2-104974637,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,2602 185th st douglas county ne,0.333333
7,S1-106407869,S2-794512883,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,415 river st ar benton,0.350877
8,S1-106407869,S2-114144622,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,100 wilses ave buffalo ny,0.266667
9,S1-106407869,S2-92136030,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,245 hampshire dr hoyt lakes mn,0.276923
10,S1-106407869,S2-181714769,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,va 1060 grande vista dr albemarle county,0.400000
11,S1-106407869,S2-724378516,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,1109 monitor ave wenatchhee wa,0.338462
12,S1-106407869,S2-570778034,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,221 stonybrook dr norristown pa,0.363636
13,S1-106407869,S2-908403586,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,117 wessling ln bethesda md,0.290323
14,S1-106407869,S2-384676749,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,2004 183rd st po box 3480 homewood il,0.333333
15,S1-106407869,S2-537475802,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,143 woodview ln kinston nc,0.360656
16,S1-106407869,S2-885551878,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,415 river st benton ar,0.385965
17,S1-106407869,S3-943074147,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,136 oregon ave luisville ohio,0.343750
18,S1-106407869,S3-696641691,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,village of hobart 1577 berkshire dr wisconsin,0.375000
19,S1-106407869,S3-245724670,vision partners corp,vision partners corp,1.0,ia iowa city 1064 newton rd unit 11,220 13th ave city of menomonie wisconsin,0.400000

In [ ]:
import pandas as pd
from rapidfuzz import fuzz
from pathlib import Path
import time

CANDIDATE_FILE = Path("output/candidate_pairs.tsv")
RESULT_FILE = Path("output/matching_results.tsv")

CHUNK_SIZE = 100_000

start = time.time()
total_candidates = 0
total_matches = 0

# Remove old result
if RESULT_FILE.exists():
    RESULT_FILE.unlink()

# Write header
with open(RESULT_FILE, "w", encoding="utf-8") as f:
    f.write("source1_entity_id\tmatched_entity_ids\n")

    for chunk_no, chunk in enumerate(
        pd.read_csv(
            CANDIDATE_FILE,
            sep="\t",
            dtype=str,
            chunksize=CHUNK_SIZE
        ),
        start=1
    ):

        # Put candidate chunk into SQLite
        conn.execute("DELETE FROM candidate_chunk")

        conn.executemany(
            """
            INSERT OR IGNORE INTO candidate_chunk
            (source1_entity_id, candidate_entity_id)
            VALUES (?, ?)
            """,
            list(
                chunk[
                    ["source1_entity_id", "candidate_entity_id"]
                ].itertuples(index=False, name=None)
            )
        )

        conn.commit()

        data = pd.read_sql_query(
            """
            SELECT
                cp.source1_entity_id,
                cp.candidate_entity_id,
                s1.name_norm AS s1_name,
                s1.address_norm AS s1_address,
                e.name_norm AS candidate_name,
                e.address_norm AS candidate_address

            FROM candidate_chunk cp

            JOIN test_s1_index s1
              ON cp.source1_entity_id = s1.entity_id

            JOIN entities e
              ON cp.candidate_entity_id = e.entity_id
            """,
            conn
        )

        if len(data) == 0:
            continue

        # Similarities
        data["name_similarity"] = [
            fuzz.ratio(a, b) / 100
            for a, b in zip(
                data["s1_name"],
                data["candidate_name"]
            )
        ]

        data["address_similarity"] = [
            fuzz.ratio(a, b) / 100
            for a, b in zip(
                data["s1_address"],
                data["candidate_address"]
            )
        ]

        data["address_exact"] = (
            data["s1_address"] ==
            data["candidate_address"]
        )

        # Strong matching rule
        keep = (
            data["address_exact"]
            |
            (
                (data["name_similarity"] >= 0.90) &
                (data["address_similarity"] >= 0.60)
            )
            |
            (
                (data["name_similarity"] >= 0.80) &
                (data["address_similarity"] >= 0.75)
            )
        )

        matches = data[keep][[
            "source1_entity_id",
            "candidate_entity_id"
        ]]

        total_candidates += len(data)
        total_matches += len(matches)

        # Group by S1
        if len(matches):
            grouped = (
                matches
                .groupby("source1_entity_id")["candidate_entity_id"]
                .apply(lambda x: ",".join(dict.fromkeys(x)))
            )

            for s1_id, ids in grouped.items():
                f.write(f"{s1_id}\t{ids}\n")

        if chunk_no % 10 == 0:
            elapsed = time.time() - start
            print(
                f"Chunk {chunk_no:,} | "
                f"Candidates: {total_candidates:,} | "
                f"Matches: {total_matches:,} | "
                f"Time: {elapsed/60:.1f} min"
            )

print("\n================================")
print("MATCHING RESULTS CREATED")
print("================================")
print("Candidates processed:", f"{total_candidates:,}")
print("Matched pairs:", f"{total_matches:,}")
print("Time:", round((time.time() - start) / 60, 2), "minutes")
print("File:", RESULT_FILE)
print("================================")

Chunk 10 | Candidates: 1,000,000 | Matches: 128,407 | Time: 0.5 min
Chunk 20 | Candidates: 2,000,000 | Matches: 254,244 | Time: 1.0 min
Chunk 30 | Candidates: 3,000,000 | Matches: 381,694 | Time: 1.4 min
Chunk 40 | Candidates: 4,000,000 | Matches: 507,333 | Time: 1.9 min
Chunk 50 | Candidates: 5,000,000 | Matches: 633,430 | Time: 2.4 min
Chunk 60 | Candidates: 6,000,000 | Matches: 760,476 | Time: 2.9 min
Chunk 70 | Candidates: 7,000,000 | Matches: 888,282 | Time: 3.5 min
Chunk 80 | Candidates: 8,000,000 | Matches: 1,015,454 | Time: 4.0 min
Chunk 90 | Candidates: 9,000,000 | Matches: 1,142,919 | Time: 4.5 min
Chunk 100 | Candidates: 10,000,000 | Matches: 1,270,800 | Time: 5.0 min
Chunk 110 | Candidates: 11,000,000 | Matches: 1,397,452 | Time: 5.5 min
Chunk 120 | Candidates: 12,000,000 | Matches: 1,524,176 | Time: 6.0 min
Chunk 130 | Candidates: 13,000,000 | Matches: 1,730,707 | Time: 6.6 min

================================
MATCHING RESULTS CREATED
================================
Candidates processed: 13,590,750
Matched pairs: 2,321,457
Time: 7.22 minutes
File: output/matching_results.tsv
================================

In [ ]:
import pandas as pd
from pathlib import Path
import time

RESULT_FILE = Path("output/matching_results.tsv")
FINAL_FILE = Path("output/matching_results_final.tsv")

start = time.time()

# Read existing predicted matches
pred = pd.read_csv(
    RESULT_FILE,
    sep="\t",
    dtype=str
)

print("Existing prediction rows:", len(pred))

# All test S1 IDs
all_s1 = test_s1[["entity_id"]].copy()
all_s1 = all_s1.rename(columns={
    "entity_id": "source1_entity_id"
})

# Left join so every S1 is present
final = all_s1.merge(
    pred,
    on="source1_entity_id",
    how="left"
)

# No-match entities get an empty matched_entity_ids field
final["matched_entity_ids"] = (
    final["matched_entity_ids"]
    .fillna("")
)

# Keep exact required columns
final = final[
    ["source1_entity_id", "matched_entity_ids"]
]

# Check uniqueness and coverage
print("Final rows:", len(final))
print("Expected S1:", len(test_s1))
print("Unique S1:", final["source1_entity_id"].nunique())
print(
    "No-match S1:",
    (final["matched_entity_ids"] == "").sum()
)

# Write final file
final.to_csv(
    FINAL_FILE,
    sep="\t",
    index=False
)

print("\n================================")
print("FINAL MATCHING FILE CREATED")
print("================================")
print("File:", FINAL_FILE)
print("Rows:", len(final))
print("Time:", round((time.time() - start) / 60, 2), "minutes")

Existing prediction rows: 1265684
Final rows: 1957782
Expected S1: 1732544
Unique S1: 1732544
No-match S1: 692098

================================
FINAL MATCHING FILE CREATED
================================
File: output/matching_results_final.tsv
Rows: 1957782
Time: 0.12 minutes

In [ ]:
import pandas as pd
from pathlib import Path
import time

start = time.time()

RESULT_FILE = Path("output/matching_results.tsv")
FINAL_FILE = Path("output/matching_results_final.tsv")

print("Reading predicted matches...")

pred = pd.read_csv(
    RESULT_FILE,
    sep="\t",
    dtype=str
)

print("Raw prediction rows:", len(pred))
print("Unique S1 IDs:", pred["source1_entity_id"].nunique())

# -------------------------------------------------
# Combine all rows belonging to the same S1
# -------------------------------------------------

def combine_ids(series):
    seen = set()
    result = []

    for value in series.dropna():
        for entity_id in str(value).split(","):
            entity_id = entity_id.strip()

            if entity_id and entity_id not in seen:
                seen.add(entity_id)
                result.append(entity_id)

    return ",".join(result)

pred_combined = (
    pred
    .groupby("source1_entity_id", sort=False)["matched_entity_ids"]
    .agg(combine_ids)
    .reset_index()
)

print("After combining duplicate S1 IDs:", len(pred_combined))

# -------------------------------------------------
# Add every test S1 exactly once
# -------------------------------------------------

all_s1 = test_s1[["entity_id"]].rename(
    columns={"entity_id": "source1_entity_id"}
)

final = all_s1.merge(
    pred_combined,
    on="source1_entity_id",
    how="left"
)

final["matched_entity_ids"] = (
    final["matched_entity_ids"]
    .fillna("")
)

final = final[
    ["source1_entity_id", "matched_entity_ids"]
]

# -------------------------------------------------
# Validation
# -------------------------------------------------

print("\nVALIDATION")
print("--------------------------------")
print("Expected S1 rows :", len(test_s1))
print("Final rows       :", len(final))
print("Unique S1 IDs    :", final["source1_entity_id"].nunique())
print(
    "No-match S1      :",
    (final["matched_entity_ids"] == "").sum()
)

print(
    "Duplicate S1 IDs :",
    final["source1_entity_id"].duplicated().sum()
)

# -------------------------------------------------
# Save
# -------------------------------------------------

final.to_csv(
    FINAL_FILE,
    sep="\t",
    index=False
)

elapsed = time.time() - start

print("\n================================")
print("FINAL FILE CREATED")
print("================================")
print("File:", FINAL_FILE)
print("Rows:", len(final))
print("Time:", round(elapsed / 60, 2), "minutes")
print("================================")

Reading predicted matches...
Raw prediction rows: 1265684
Unique S1 IDs: 1040446
After combining duplicate S1 IDs: 1040446

VALIDATION
--------------------------------
Expected S1 rows : 1732544
Final rows       : 1732544
Unique S1 IDs    : 1732544
No-match S1      : 692098
Duplicate S1 IDs : 0

================================
FINAL FILE CREATED
================================
File: output/matching_results_final.tsv
Rows: 1732544
Time: 2.78 minutes
================================

In [ ]:
import pandas as pd
import time

start = time.time()

FINAL_FILE = "output/matching_results_final.tsv"

# --------------------------------------------------
# 1. Read final results
# --------------------------------------------------

final = pd.read_csv(
    FINAL_FILE,
    sep="\t",
    dtype=str
)

print("Final rows:", len(final))
print("Unique S1:", final["source1_entity_id"].nunique())

# --------------------------------------------------
# 2. Check S1 coverage
# --------------------------------------------------

expected_s1 = set(test_s1["entity_id"])

actual_s1 = set(final["source1_entity_id"])

print("\nS1 coverage:")
print("Missing S1:", len(expected_s1 - actual_s1))
print("Extra S1:", len(actual_s1 - expected_s1))

# --------------------------------------------------
# 3. Check matched IDs exist in S2/S3
# --------------------------------------------------

print("\nChecking matched IDs...")

matched_ids = set()

for value in final["matched_entity_ids"]:
    if pd.notna(value) and str(value).strip():
        matched_ids.update(
            x.strip()
            for x in str(value).split(",")
            if x.strip()
        )

print("Unique predicted matched IDs:", len(matched_ids))

existing_ids = set()

for chunk in pd.read_csv(
    TEST_S2,
    sep="\t",
    usecols=["entity_id"],
    dtype=str,
    chunksize=200_000
):
    existing_ids.update(chunk["entity_id"])

for chunk in pd.read_csv(
    TEST_S3,
    sep="\t",
    usecols=["entity_id"],
    dtype=str,
    chunksize=200_000
):
    existing_ids.update(chunk["entity_id"])

invalid_ids = matched_ids - existing_ids

print("Invalid matched IDs:", len(invalid_ids))

# --------------------------------------------------
# 4. Check S1 IDs accidentally used as matches
# --------------------------------------------------

s1_as_matches = matched_ids & expected_s1

print("S1 IDs used as matches:", len(s1_as_matches))

# --------------------------------------------------
# 5. Check duplicate IDs within each S1
# --------------------------------------------------

duplicate_match_lists = 0

for value in final["matched_entity_ids"]:
    if pd.notna(value) and str(value).strip():
        ids = [
            x.strip()
            for x in str(value).split(",")
            if x.strip()
        ]

        if len(ids) != len(set(ids)):
            duplicate_match_lists += 1

print("S1 rows with duplicate matched IDs:", duplicate_match_lists)

# --------------------------------------------------
# FINAL STATUS
# --------------------------------------------------

elapsed = time.time() - start

passed = (
    len(expected_s1 - actual_s1) == 0
    and len(actual_s1 - expected_s1) == 0
    and len(invalid_ids) == 0
    and len(s1_as_matches) == 0
    and duplicate_match_lists == 0
)

print("\n================================")
print("FINAL VALIDATION")
print("================================")

if passed:
    print("✅ PASS")
else:
    print("❌ FAIL")

print("Time:", round(elapsed / 60, 2), "minutes")
print("================================")

Final rows: 1732544
Unique S1: 1732544

S1 coverage:
Missing S1: 0
Extra S1: 0

Checking matched IDs...
Unique predicted matched IDs: 1728047
Invalid matched IDs: 0
S1 IDs used as matches: 0
S1 rows with duplicate matched IDs: 0

================================
FINAL VALIDATION
================================
✅ PASS
Time: 0.6 minutes
================================

In [ ]:
from pathlib import Path
import shutil

src = Path("output/matching_results_final.tsv")
dst = Path("output/matching_results.tsv")

shutil.copy2(src, dst)

print("✅ Created:", dst.resolve())
print("Size:", round(dst.stat().st_size / (1024**3), 2), "GB")

✅ Created: /Users/apple/Downloads/student_resource/dataset/train/output/matching_results.tsv
Size: 0.05 GB

In [ ]:
python3 utils/validate_submission.py \
  --matching output/matching_results.tsv \
  --candidate output/candidate_pairs.tsv \
  --test-dir dataset/test

SyntaxError: invalid syntax (3692521468.py, line 1)

In [ ]:
python3 ../../utils/validate_submission.py \
  --matching output/matching_results.tsv \
  --candidate output/candidate_pairs.tsv \
  --test-dir dataset/test

SyntaxError: invalid syntax (3985820226.py, line 1)

In [ ]:
python3 - <<'PY'
import pandas as pd

inp = "output/candidate_pairs.tsv"
out = "output/candidate_pairs_fixed.tsv"

df = pd.read_csv(inp, sep="\t", dtype=str)

grouped = (
    df.groupby("source1_entity_id")["candidate_entity_ids"]
      .agg(",".join)
      .reset_index()
)

grouped.to_csv(out, sep="\t", index=False)

print("Created:", out)
print("Rows:", len(grouped))
PY

SyntaxError: invalid syntax (2261717092.py, line 1)

In [ ]:
import pandas as pd

inp = "output/candidate_pairs.tsv"
out = "output/candidate_pairs_fixed.tsv"

df = pd.read_csv(inp, sep="\t", dtype=str)

print("Loaded rows:", len(df))

grouped = (
    df.groupby("source1_entity_id")["candidate_entity_ids"]
      .agg(",".join)
      .reset_index()
)

grouped.to_csv(out, sep="\t", index=False)

print("Created:", out)
print("Rows:", len(grouped))
print(grouped.head())

Loaded rows: 13590750
Created: output/candidate_pairs_fixed.tsv
Rows: 1391765
  source1_entity_id                               candidate_entity_ids
0      S1-100000556  S2-119912657,S2-212044530,S2-739963531,S2-3501...
1      S1-100001013  S2-824273314,S2-613035716,S2-10453354,S2-70320...
2      S1-100001295  S2-334300764,S2-560501252,S3-409832146,S3-3677...
3      S1-100001834                                       S2-900957143
4      S1-100003037                          S2-207887213,S3-906059588

In [ ]:
import pandas as pd

test_s1_path = "/Users/apple/Downloads/student_resource 2/dataset/test/test_source1.tsv"

test_s1 = pd.read_csv(
    test_s1_path,
    sep="\t",
    usecols=["entity_id"],
    dtype=str
)

candidate_fixed = pd.read_csv(
    "output/candidate_pairs_fixed.tsv",
    sep="\t",
    dtype=str
)

candidate_fixed = test_s1.rename(
    columns={"entity_id": "source1_entity_id"}
).merge(
    candidate_fixed,
    on="source1_entity_id",
    how="left"
)

candidate_fixed["candidate_entity_ids"] = (
    candidate_fixed["candidate_entity_ids"].fillna("")
)

candidate_fixed.to_csv(
    "output/candidate_pairs_final.tsv",
    sep="\t",
    index=False
)

print("Final rows:", len(candidate_fixed))
print("Expected:", len(test_s1))
print("Missing S1 rows:", candidate_fixed["source1_entity_id"].isna().sum())
print("Empty candidate lists:", (candidate_fixed["candidate_entity_ids"] == "").sum())
print("Saved: output/candidate_pairs_final.tsv")

Final rows: 1732544
Expected: 1732544
Missing S1 rows: 0
Empty candidate lists: 340779
Saved: output/candidate_pairs_final.tsv

In [ ]:
import shutil

shutil.copy(
    "output/candidate_pairs_final.tsv",
    "output/candidate_pairs.tsv"
)

print("candidate_pairs.tsv updated successfully")

candidate_pairs.tsv updated successfully

In [ ]:
import pandas as pd
from sklearn.metrics import precision_score, recall_score, fbeta_score

pos = pd.read_csv("positive_features.tsv", sep="\t")
neg = pd.read_csv("negative_features.tsv", sep="\t")

df = pd.concat([pos, neg], ignore_index=True)

y = df["label"].astype(int)

name = df["name_similarity"].fillna(0)
addr = df["address_similarity"].fillna(0)
addr_exact = df["address_exact"].fillna(0)

results = []

for n in [0.80, 0.85, 0.90, 0.92, 0.95, 0.97]:
    for a in [0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90]:
        
        pred = (
            (addr_exact == 1) |
            ((name >= n) & (addr >= a))
        ).astype(int)
        
        f05 = fbeta_score(y, pred, beta=0.5, zero_division=0)
        precision = precision_score(y, pred, zero_division=0)
        recall = recall_score(y, pred, zero_division=0)
        
        results.append((f05, precision, recall, n, a))

results = pd.DataFrame(
    results,
    columns=["F0.5", "Precision", "Recall", "Name_Threshold", "Address_Threshold"]
)

print(results.sort_values("F0.5", ascending=False).head(10).to_string(index=False))

    F0.5  Precision   Recall  Name_Threshold  Address_Threshold
0.868664        1.0 0.569486            0.80               0.60
0.856284        1.0 0.543719            0.80               0.65
0.842023        1.0 0.515975            0.80               0.70
0.834272        1.0 0.501693            0.85               0.60
0.822401        1.0 0.480824            0.80               0.75
0.821851        1.0 0.479886            0.85               0.65
0.807604        1.0 0.456380            0.85               0.70
0.790798        1.0 0.430529            0.80               0.80
0.788121        1.0 0.426584            0.85               0.75
0.783679        1.0 0.420139            0.90               0.60

In [ ]:
from pathlib import Path

db = Path("test_index/entity_index.db")

print("SQLite index exists:", db.exists())
if db.exists():
    print("Size GB:", round(db.stat().st_size / 1024**3, 2))

SQLite index exists: True
Size GB: 6.68

In [ ]:
import sqlite3
import pandas as pd
from rapidfuzz import fuzz
from pathlib import Path
import time

DB = "test_index/entity_index.db"
CANDIDATES = "output/candidate_pairs.tsv"
TEST_S1 = "/Users/apple/Downloads/student_resource 2/dataset/test/test_source1.tsv"
OUT = "output/matching_results_v2.tsv"

t0 = time.time()

# Load S1 data
s1 = pd.read_csv(
    TEST_S1,
    sep="\t",
    dtype=str,
    usecols=["entity_id", "business_name", "business_address"]
).fillna("")

s1 = s1.rename(columns={"entity_id": "source1_entity_id"})

s1["name_norm"] = s1["business_name"].str.lower()
s1["address_norm"] = s1["business_address"].str.lower()

s1_lookup = s1.set_index("source1_entity_id")[
    ["name_norm", "address_norm"]
]

conn = sqlite3.connect(DB)

# Check candidate count
cand = pd.read_csv(
    CANDIDATES,
    sep="\t",
    dtype=str,
    chunksize=10000
)

results = []

total = 0
matched = 0

for chunk_no, chunk in enumerate(cand, 1):

    # Convert grouped candidate IDs back to individual pairs
    pairs = chunk.assign(
        candidate_entity_ids=chunk["candidate_entity_ids"]
        .fillna("")
        .str.split(",")
    ).explode("candidate_entity_ids")

    pairs = pairs[
        pairs["candidate_entity_ids"].notna() &
        (pairs["candidate_entity_ids"] != "")
    ]

    if len(pairs) == 0:
        continue

    # Add S1 normalized fields
    pairs = pairs.join(
        s1_lookup,
        on="source1_entity_id"
    )

    # Create temporary SQLite table for this batch
    conn.execute("DROP TABLE IF EXISTS candidate_chunk")
    pairs[["candidate_entity_ids"]].drop_duplicates().to_sql(
        "candidate_chunk",
        conn,
        index=False,
        if_exists="replace"
    )

    # Retrieve candidate entity text
    ids = pairs["candidate_entity_ids"].drop_duplicates().tolist()

    # Query in manageable batches
    rows = []

    for i in range(0, len(ids), 50000):
        batch = ids[i:i+50000]
        placeholders = ",".join(["?"] * len(batch))

        q = f"""
        SELECT entity_id, name_norm, address_norm
        FROM entities
        WHERE entity_id IN ({placeholders})
        """

        rows.append(pd.read_sql_query(q, conn, params=batch))

    cand_info = pd.concat(rows, ignore_index=True)

    pairs = pairs.merge(
        cand_info,
        left_on="candidate_entity_ids",
        right_on="entity_id",
        how="left"
    )

    # Similarities
    pairs["name_similarity"] = [
        fuzz.ratio(a, b) / 100
        for a, b in zip(
            pairs["name_norm_x"],
            pairs["name_norm_y"]
        )
    ]

    pairs["address_similarity"] = [
        fuzz.ratio(a, b) / 100
        for a, b in zip(
            pairs["address_norm_x"],
            pairs["address_norm_y"]
        )
    ]

    # Exact address
    pairs["address_exact"] = (
        (pairs["address_norm_x"] != "") &
        (pairs["address_norm_x"] == pairs["address_norm_y"])
    )

    # BEST VALIDATED RULE
    keep = (
        pairs["address_exact"] |
        (
            (pairs["name_similarity"] >= 0.80) &
            (pairs["address_similarity"] >= 0.60)
        )
    )

    selected = pairs.loc[
        keep,
        ["source1_entity_id", "candidate_entity_ids"]
    ]

    if len(selected):
        results.append(selected)

    total += len(pairs)
    matched += len(selected)

    if chunk_no % 20 == 0:
        print(
            f"Chunk {chunk_no} | "
            f"Candidates processed: {total:,} | "
            f"Matches: {matched:,} | "
            f"Time: {(time.time()-t0)/60:.1f} min"
        )

# Combine predictions
if results:
    pred = pd.concat(results, ignore_index=True)

    pred = (
        pred.groupby("source1_entity_id")["candidate_entity_ids"]
        .agg(",".join)
        .reset_index()
    )
else:
    pred = pd.DataFrame(
        columns=["source1_entity_id", "candidate_entity_ids"]
    )

# Rename output column
pred = pred.rename(
    columns={"candidate_entity_ids": "matched_entity_ids"}
)

# Ensure EVERY S1 entity appears
final = s1[["source1_entity_id"]].merge(
    pred,
    on="source1_entity_id",
    how="left"
)

final["matched_entity_ids"] = (
    final["matched_entity_ids"].fillna("")
)

final.to_csv(
    OUT,
    sep="\t",
    index=False
)

print("\nDONE")
print("Rows:", len(final))
print("Expected:", len(s1))
print("Non-empty:", (final["matched_entity_ids"] != "").sum())
print("Empty:", (final["matched_entity_ids"] == "").sum())
print("Saved:", OUT)
print("Time:", round((time.time()-t0)/60, 1), "minutes")

DatabaseError: Execution failed on sql '
        SELECT entity_id, name_norm, address_norm
        FROM entities

In [ ]:
import sqlite3
import pandas as pd
from rapidfuzz import fuzz
import time

DB = "test_index/entity_index.db"
CANDIDATES = "output/candidate_pairs.tsv"
TEST_S1 = "/Users/apple/Downloads/student_resource 2/dataset/test/test_source1.tsv"
OUT = "output/matching_results_v2.tsv"

t0 = time.time()

# -----------------------------
# Load Test Source 1
# -----------------------------
s1 = pd.read_csv(
    TEST_S1,
    sep="\t",
    dtype=str,
    usecols=["entity_id", "business_name", "business_address"]
).fillna("")

s1 = s1.rename(columns={"entity_id": "source1_entity_id"})

s1["name_norm"] = s1["business_name"].str.lower()
s1["address_norm"] = s1["business_address"].str.lower()

s1_lookup = s1.set_index("source1_entity_id")[
    ["name_norm", "address_norm"]
]

# -----------------------------
# SQLite connection
# -----------------------------
conn = sqlite3.connect(DB)

results = []
total_pairs = 0
total_matches = 0

# -----------------------------
# Process candidate file
# -----------------------------
for chunk_no, chunk in enumerate(
    pd.read_csv(
        CANDIDATES,
        sep="\t",
        dtype=str,
        chunksize=5000
    ),
    1
):

    # Convert grouped candidates into individual pairs
    pairs = chunk.assign(
        candidate_entity_id=
        chunk["candidate_entity_ids"]
        .fillna("")
        .str.split(",")
    ).explode("candidate_entity_id")

    pairs = pairs[
        pairs["candidate_entity_id"].notna()
        & (pairs["candidate_entity_id"] != "")
    ].copy()

    if pairs.empty:
        continue

    # Add S1 normalized text
    pairs = pairs.join(
        s1_lookup,
        on="source1_entity_id"
    )

    # -----------------------------------------
    # Put candidate IDs into temporary SQLite table
    # -----------------------------------------
    conn.execute("DROP TABLE IF EXISTS candidate_chunk")

    unique_ids = pairs[["candidate_entity_id"]].drop_duplicates()

    unique_ids.to_sql(
        "candidate_chunk",
        conn,
        index=False,
        if_exists="replace"
    )

    # -----------------------------------------
    # JOIN instead of huge IN(...)
    # -----------------------------------------
    cand_info = pd.read_sql_query(
        """
        SELECT
            c.candidate_entity_id,
            e.name_norm AS candidate_name_norm,
            e.address_norm AS candidate_address_norm
        FROM candidate_chunk c
        INNER JOIN entities e
            ON e.entity_id = c.candidate_entity_id
        """,
        conn
    )

    pairs = pairs.merge(
        cand_info,
        on="candidate_entity_id",
        how="inner"
    )

    # -----------------------------------------
    # Similarities
    # -----------------------------------------
    pairs["name_similarity"] = [
        fuzz.ratio(a, b) / 100.0
        for a, b in zip(
            pairs["name_norm"],
            pairs["candidate_name_norm"]
        )
    ]

    pairs["address_similarity"] = [
        fuzz.ratio(a, b) / 100.0
        for a, b in zip(
            pairs["address_norm"],
            pairs["candidate_address_norm"]
        )
    ]

    pairs["address_exact"] = (
        (pairs["address_norm"] != "") &
        (pairs["address_norm"] == pairs["candidate_address_norm"])
    )

    # -----------------------------------------
    # BEST VALIDATED RULE
    # -----------------------------------------
    keep = (
        pairs["address_exact"]
        |
        (
            (pairs["name_similarity"] >= 0.80) &
            (pairs["address_similarity"] >= 0.60)
        )
    )

    selected = pairs.loc[
        keep,
        ["source1_entity_id", "candidate_entity_id"]
    ]

    if not selected.empty:
        results.append(selected)

    total_pairs += len(pairs)
    total_matches += len(selected)

    if chunk_no % 20 == 0:
        print(
            f"Chunk {chunk_no} | "
            f"Pairs: {total_pairs:,} | "
            f"Matches: {total_matches:,} | "
            f"Time: {(time.time()-t0)/60:.1f} min"
        )

# -----------------------------
# Combine results
# -----------------------------
if results:
    pred = pd.concat(results, ignore_index=True)

    pred = (
        pred.groupby("source1_entity_id")["candidate_entity_id"]
        .agg(",".join)
        .reset_index()
    )

    pred = pred.rename(
        columns={"candidate_entity_id": "matched_entity_ids"}
    )
else:
    pred = pd.DataFrame(
        columns=["source1_entity_id", "matched_entity_ids"]
    )

# -----------------------------
# Ensure every S1 is present
# -----------------------------
final = s1[["source1_entity_id"]].merge(
    pred,
    on="source1_entity_id",
    how="left"
)

final["matched_entity_ids"] = (
    final["matched_entity_ids"].fillna("")
)

# -----------------------------
# Save V2
# -----------------------------
final.to_csv(
    OUT,
    sep="\t",
    index=False
)

print("\n==============================")
print("DONE")
print("==============================")
print("Rows:", len(final))
print("Expected:", len(s1))
print(
    "Non-empty:",
    (final["matched_entity_ids"] != "").sum()
)
print(
    "Empty:",
    (final["matched_entity_ids"] == "").sum()
)
print("Saved:", OUT)
print(
    "Time:",
    round((time.time()-t0)/60, 1),
    "minutes"
)

Chunk 20 | Pairs: 792,686 | Matches: 101,714 | Time: 2.8 min
Chunk 40 | Pairs: 1,581,130 | Matches: 200,844 | Time: 4.4 min
Chunk 60 | Pairs: 2,369,406 | Matches: 301,809 | Time: 5.6 min
Chunk 80 | Pairs: 3,159,083 | Matches: 402,388 | Time: 6.9 min
Chunk 100 | Pairs: 3,942,104 | Matches: 501,267 | Time: 8.0 min
Chunk 120 | Pairs: 4,720,986 | Matches: 599,794 | Time: 9.1 min
Chunk 140 | Pairs: 5,499,318 | Matches: 699,187 | Time: 10.1 min
Chunk 160 | Pairs: 6,286,650 | Matches: 798,562 | Time: 10.8 min
Chunk 180 | Pairs: 7,071,719 | Matches: 899,283 | Time: 11.6 min
Chunk 200 | Pairs: 7,852,489 | Matches: 999,205 | Time: 12.4 min
Chunk 220 | Pairs: 8,634,987 | Matches: 1,098,435 | Time: 13.1 min
Chunk 240 | Pairs: 9,420,606 | Matches: 1,198,755 | Time: 13.7 min
Chunk 260 | Pairs: 10,212,686 | Matches: 1,299,776 | Time: 14.5 min
Chunk 280 | Pairs: 10,992,817 | Matches: 1,399,610 | Time: 15.2 min
Chunk 300 | Pairs: 11,778,082 | Matches: 1,499,751 | Time: 15.9 min
Chunk 320 | Pairs: 12,562,942 | Matches: 1,598,751 | Time: 16.5 min
Chunk 340 | Pairs: 13,343,908 | Matches: 1,698,504 | Time: 17.2 min

==============================
DONE
==============================
Rows: 1732544
Expected: 1732544
Non-empty: 882233
Empty: 850311
Saved: output/matching_results_v2.tsv
Time: 17.9 minutes

In [ ]:
import pandas as pd

v2 = pd.read_csv(
    "output/matching_results_v2.tsv",
    sep="\t",
    dtype=str,
    keep_default_na=False
)

print("Rows:", len(v2))
print("Unique S1:", v2["source1_entity_id"].nunique())
print("Duplicate S1:", v2["source1_entity_id"].duplicated().sum())
print("Empty matches:", (v2["matched_entity_ids"] == "").sum())
print("Columns:", list(v2.columns))

Rows: 1732544
Unique S1: 1732544
Duplicate S1: 0
Empty matches: 850311
Columns: ['source1_entity_id', 'matched_entity_ids']

In [ ]:
import shutil

shutil.copy(
    "output/matching_results_v2.tsv",
    "output/matching_results.tsv"
)

print("V2 copied to matching_results.tsv")

V2 copied to matching_results.tsv

In [ ]:
import shutil

shutil.copy(
    "output/matching_results_final.tsv",
    "output/matching_results.tsv"
)

print("Original 0.482 solution restored.")

Original 0.482 solution restored.

In [ ]:
import pandas as pd

df = pd.read_csv(
    "output/matching_results.tsv",
    sep="\t",
    dtype=str
)

print("Rows:", len(df))
print("Unique S1:", df["source1_entity_id"].nunique())
print("Duplicate S1:", df["source1_entity_id"].duplicated().sum())

Rows: 1732544
Unique S1: 1732544
Duplicate S1: 0

In [ ]:
import pandas as pd
import time

t0 = time.time()

MATCH = "output/matching_results.tsv"
CAND = "output/candidate_pairs.tsv"
OUT = "output/candidate_pairs_compact.tsv"

# Load final matches
matches = pd.read_csv(
    MATCH,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

# Load candidate file
candidates = pd.read_csv(
    CAND,
    sep="\t",
    dtype=str,
    keep_default_na=False
)

# Create lookup of final matched IDs
match_map = dict(
    zip(
        matches["source1_entity_id"],
        matches["matched_entity_ids"]
    )
)

# Keep ONLY candidates that are actually in our final matching result
def filter_candidates(row):

    matched = match_map.get(
        row["source1_entity_id"],
        ""
    )

    if not matched:
        return ""

    matched_set = set(matched.split(","))

    ids = [
        x for x in row["candidate_entity_ids"].split(",")
        if x and x in matched_set
    ]

    return ",".join(ids)

candidates["candidate_entity_ids"] = candidates.apply(
    filter_candidates,
    axis=1
)

# Save
candidates.to_csv(
    OUT,
    sep="\t",
    index=False
)

print("DONE")
print("Rows:", len(candidates))
print(
    "Non-empty:",
    (candidates["candidate_entity_ids"] != "").sum()
)
print(
    "Empty:",
    (candidates["candidate_entity_ids"] == "").sum()
)
print(
    "Original candidate rows:",
    len(candidates)
)
print("Saved:", OUT)
print("Time:", round((time.time()-t0)/60, 2), "min")

DONE
Rows: 1732544
Non-empty: 1040446
Empty: 692098
Original candidate rows: 1732544
Saved: output/candidate_pairs_compact.tsv
Time: 1.3 min